## PANDAS CLEANING

In [1]:
import pandas as pd

In [168]:
df = pd.read_csv(r"C:\Users\SANDESH\Downloads\dirty_rows.csv")
df

           Date   Product       City    Sales  Quantity
0    2025-01-01   Monitor  Bangalore      NaN         1
1    2025-01-02   Printer       Pune  37719.0         6
2    2025-01-03  Keyboard    Chennai  65144.0         3
3    2025-01-04   Printer      Delhi  60779.0         7
4    2025-01-05   Printer      Delhi  53528.0         2
..          ...       ...        ...      ...       ...
505  2025-01-06     Mouse       Pune    626.0         2
506  2025-01-07  Keyboard  Bangalore  52829.0         4
507  2025-01-08  Keyboard  Bangalore  28132.0         1
508  2025-01-09  Keyboard    Chennai  65810.0         3
509  2025-01-10   Printer       Pune  55676.0         9

[510 rows x 5 columns]

### Total Rows And Column

In [80]:
df.shape

(510, 5)

### Structure of dataframe

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      510 non-null    object
 1   Product   510 non-null    object
 2   City      510 non-null    object
 3   Sales     484 non-null    float64
 4   Quantity  510 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 20.1+ KB

### Statistics Information Of Numerical Column

In [82]:
df.describe()

              Sales    Quantity
count    484.000000  510.000000
mean   40870.787190    4.960784
std    22781.547623    2.598630
min      560.000000    1.000000
25%    22282.500000    3.000000
50%    40117.000000    5.000000
75%    60359.750000    7.000000
max    79773.000000    9.000000

### Missing Value

In [83]:
df.isnull()

      Date  Product   City  Sales  Quantity
0    False    False  False   True     False
1    False    False  False  False     False
2    False    False  False  False     False
3    False    False  False  False     False
4    False    False  False  False     False
..     ...      ...    ...    ...       ...
505  False    False  False  False     False
506  False    False  False  False     False
507  False    False  False  False     False
508  False    False  False  False     False
509  False    False  False  False     False

[510 rows x 5 columns]

In [84]:
df.isnull().sum()

Date         0
Product      0
City         0
Sales       26
Quantity     0
dtype: int64

### Fill Missing Values

In [85]:
df["Sales"] = df["Sales"].fillna("0") # Filled O

In [169]:
df.head(10)

         Date   Product       City    Sales  Quantity
0  2025-01-01   Monitor  Bangalore      NaN         1
1  2025-01-02   Printer       Pune  37719.0         6
2  2025-01-03  Keyboard    Chennai  65144.0         3
3  2025-01-04   Printer      Delhi  60779.0         7
4  2025-01-05   Printer      Delhi  53528.0         2
5  2025-01-06     Mouse      pune     626.0         2
6  2025-01-07  Keyboard  Bangalore  52829.0         4
7  2025-01-08  Keyboard  Bangalore  28132.0         1
8  2025-01-09  Keyboard    Chennai  65810.0         3
9  2025-01-10   Printer       Pune  55676.0         9

In [170]:
df.tail(10)

           Date   Product       City    Sales  Quantity
500  2025-01-01   Monitor  Bangalore      NaN         1
501  2025-01-02   Printer       Pune  37719.0         6
502  2025-01-03  Keyboard    Chennai  65144.0         3
503  2025-01-04   Printer      Delhi  60779.0         7
504  2025-01-05   Printer      Delhi  53528.0         2
505  2025-01-06     Mouse       Pune    626.0         2
506  2025-01-07  Keyboard  Bangalore  52829.0         4
507  2025-01-08  Keyboard  Bangalore  28132.0         1
508  2025-01-09  Keyboard    Chennai  65810.0         3
509  2025-01-10   Printer       Pune  55676.0         9

In [90]:
df["Sales"] = df["Sales"].fillna(df["Sales"].mean())  #Fill Mean Value

In [41]:
df.head(4)

         Date   Product       City        Sales  Quantity
0  2025-01-01   Monitor  Bangalore  40870.78719         1
1  2025-01-02   Printer       Pune  37719.00000         6
2  2025-01-03  Keyboard    Chennai  65144.00000         3
3  2025-01-04   Printer      Delhi  60779.00000         7

### Check Datatypes

In [126]:
df.dtypes

Date        datetime64[ns]
Product             object
City                object
Sales              float64
Quantity             int64
Year                 int32
Month                int32
dtype: object

### Check Duplicate

In [91]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
505    False
506     True
507     True
508     True
509     True
Length: 510, dtype: bool

In [92]:
df.duplicated().any()

np.True_

### Count Duplicate

In [93]:
df.duplicated().sum()

np.int64(9)

### Round Sales Column

In [142]:
df['Sales']=df["Sales"].round(2)
df.head()

        Date   Product       City     Sales  Quantity  Year  Month
0 2025-01-01   Monitor  Bangalore  40870.79         1  2025      1
1 2025-01-02   Printer       Pune  37719.00         6  2025      1
2 2025-01-03  Keyboard    Chennai  65144.00         3  2025      1
3 2025-01-04   Printer      Delhi  60779.00         7  2025      1
4 2025-01-05   Printer      Delhi  53528.00         2  2025      1

### Delete Duplicatese

In [94]:
df.drop_duplicates(inplace=True)

In [141]:
df.head()

        Date   Product       City     Sales  Quantity  Year  Month
0 2025-01-01   Monitor  Bangalore  40870.79         1  2025      1
1 2025-01-02   Printer       Pune  37719.00         6  2025      1
2 2025-01-03  Keyboard    Chennai  65144.00         3  2025      1
3 2025-01-04   Printer      Delhi  60779.00         7  2025      1
4 2025-01-05   Printer      Delhi  53528.00         2  2025      1

### Clean Text Column

In [140]:
df["City"] = df["City"].str.strip()
df.head()

        Date   Product       City     Sales  Quantity  Year  Month
0 2025-01-01   Monitor  Bangalore  40870.79         1  2025      1
1 2025-01-02   Printer       Pune  37719.00         6  2025      1
2 2025-01-03  Keyboard    Chennai  65144.00         3  2025      1
3 2025-01-04   Printer      Delhi  60779.00         7  2025      1
4 2025-01-05   Printer      Delhi  53528.00         2  2025      1

In [135]:
df["Product"] = df["Product"].str.lower()
df.head()

        Date   Product       City     Sales  Quantity  Year  Month
0 2025-01-01   monitor  Bangalore  40870.79         1  2025      1
1 2025-01-02   printer       Pune  37719.00         6  2025      1
2 2025-01-03  keyboard    Chennai  65144.00         3  2025      1
3 2025-01-04   printer      Delhi  60779.00         7  2025      1
4 2025-01-05   printer      Delhi  53528.00         2  2025      1

In [134]:
df["Product"] = df["Product"].str.upper()
df.head()

        Date   Product       City     Sales  Quantity  Year  Month
0 2025-01-01   MONITOR  Bangalore  40870.79         1  2025      1
1 2025-01-02   PRINTER       Pune  37719.00         6  2025      1
2 2025-01-03  KEYBOARD    Chennai  65144.00         3  2025      1
3 2025-01-04   PRINTER      Delhi  60779.00         7  2025      1
4 2025-01-05   PRINTER      Delhi  53528.00         2  2025      1

In [139]:
df["Product"] = df["Product"].str.title()
df.head()

        Date   Product       City     Sales  Quantity  Year  Month
0 2025-01-01   Monitor  Bangalore  40870.79         1  2025      1
1 2025-01-02   Printer       Pune  37719.00         6  2025      1
2 2025-01-03  Keyboard    Chennai  65144.00         3  2025      1
3 2025-01-04   Printer      Delhi  60779.00         7  2025      1
4 2025-01-05   Printer      Delhi  53528.00         2  2025      1

### Remove Extra Space

In [167]:
df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)
df.head(10)

        Date   Product       City     Sales  Quantity  Year  Month
0 2025-01-01   Monitor  Bangalore  40870.79         1  2025      1
1 2025-01-02   Printer       Pune  37719.00         6  2025      1
2 2025-01-03  Keyboard    Chennai  65144.00         3  2025      1
3 2025-01-04   Printer      Delhi  60779.00         7  2025      1
4 2025-01-05   Printer      Delhi  53528.00         2  2025      1
5 2025-01-06     Mouse       Pune    626.00         2  2025      1
6 2025-01-07  Keyboard  Bangalore  52829.00         4  2025      1
7 2025-01-08  Keyboard  Bangalore  28132.00         1  2025      1
8 2025-01-09  Keyboard    Chennai  65810.00         3  2025      1
9 2025-01-10   Printer       Pune  55676.00         9  2025      1

### Inconsistent Cleaning

In [128]:
df['City']=df['City'].replace(
    {
        "pune":"Pune"
    }
)
df.head(6)

        Date   Product       City        Sales  Quantity  Year  Month
0 2025-01-01   Monitor  Bangalore  40870.78719         1  2025      1
1 2025-01-02   Printer       Pune  37719.00000         6  2025      1
2 2025-01-03  Keyboard    Chennai  65144.00000         3  2025      1
3 2025-01-04   Printer      Delhi  60779.00000         7  2025      1
4 2025-01-05   Printer      Delhi  53528.00000         2  2025      1
5 2025-01-06     Mouse       Pune    626.00000         2  2025      1

### Check Unique Values

In [131]:
print(df["City"].unique())

print("\n",df.nunique())

['Bangalore' 'Pune' 'Chennai' 'Delhi' 'Mumbai']

 Date        500
Product       5
City          5
Sales       475
Quantity      9
Year          2
Month        12
dtype: int64

In [132]:
print(df["Product"].unique())

['Monitor' 'Printer' 'Keyboard' 'Mouse' 'Laptop']

### To Change Date Column

In [100]:
df["Date"] = pd.to_datetime(df["Date"])
df.head()

        Date   Product       City        Sales  Quantity
0 2025-01-01   Monitor  Bangalore  40870.78719         1
1 2025-01-02   Printer       Pune  37719.00000         6
2 2025-01-03  Keyboard    Chennai  65144.00000         3
3 2025-01-04   Printer      Delhi  60779.00000         7
4 2025-01-05   Printer      Delhi  53528.00000         2

In [101]:
df["Year"] = df["Date"].dt.year
df.head()

        Date   Product       City        Sales  Quantity  Year
0 2025-01-01   Monitor  Bangalore  40870.78719         1  2025
1 2025-01-02   Printer       Pune  37719.00000         6  2025
2 2025-01-03  Keyboard    Chennai  65144.00000         3  2025
3 2025-01-04   Printer      Delhi  60779.00000         7  2025
4 2025-01-05   Printer      Delhi  53528.00000         2  2025

In [102]:
df["Month"] = df["Date"].dt.month
df.head()

        Date   Product       City        Sales  Quantity  Year  Month
0 2025-01-01   Monitor  Bangalore  40870.78719         1  2025      1
1 2025-01-02   Printer       Pune  37719.00000         6  2025      1
2 2025-01-03  Keyboard    Chennai  65144.00000         3  2025      1
3 2025-01-04   Printer      Delhi  60779.00000         7  2025      1
4 2025-01-05   Printer      Delhi  53528.00000         2  2025      1

### Summarize Data

In [130]:
pd.pivot_table(
    df,
    values="Sales",
    index="Product",
    columns="City",
    aggfunc="sum",
    fill_value=0
)

City      Bangalore     Chennai      Delhi      Mumbai        Pune
Product
Keyboard  815982.79   793396.79  805462.37   694106.00   758568.00
Laptop    851956.37   915137.79  577892.58   881598.58   807511.00
Monitor   986420.79   566541.79  850725.37  1239922.79  1101104.37
Mouse     904280.00  1013974.00  556464.79   653863.79   856328.00
Printer   629716.00  1267239.00  711616.79   550060.00   593744.00

In [150]:
df[df.duplicated()]

          Date Product  City  Sales  Quantity  Year  Month
505 2025-01-06   Mouse  Pune  626.0         2  2025      1

In [156]:
df.drop_duplicates(inplace=True)

print(df.duplicated().sum())

0

In [153]:
df.duplicated().any()

np.False_

### Top Products

In [166]:
df.groupby("Product")["Sales"].sum().sort_values(ascending=False)

Product
Monitor     4744715.11
Laptop      4034096.32
Mouse       3984284.58
Keyboard    3867515.95
Printer     3752375.79
Name: Sales, dtype: float64

### Top Sales By City

In [164]:
df.groupby("City")["Sales"].sum().sort_values(ascending=False)

City
Chennai      4556289.37
Bangalore    4188355.95
Pune         4116629.37
Mumbai       4019551.16
Delhi        3502161.90
Name: Sales, dtype: float64

In [165]:
df.shape

(500, 7)

### SAVE CSV

In [172]:
df.to_csv("Cleaned.csv",index=False)
print("CSV Saved Successfully")

CSV Saved Successfully