### Pandas Sorting & Duplicate Handling

In [1]:
import pandas as pd

In [2]:
data = {
    'Name':['Ram','Sham','Ram','Amit'],
    'Marks':[85,90,85,70]
}

df = pd.DataFrame(data)

print(df)

   Name  Marks
0   Ram     85
1  Sham     90
2   Ram     85
3  Amit     70

### sort_values()
    Sort values In Ascending

In [3]:
print(
    df.sort_values('Marks')
)

   Name  Marks
3  Amit     70
0   Ram     85
2   Ram     85
1  Sham     90

### Descending

In [4]:
print(
    df.sort_values('Marks',ascending=False)
)

   Name  Marks
1  Sham     90
0   Ram     85
2   Ram     85
3  Amit     70

### sort_index()
    Sorts the Index

In [5]:
print(df.sort_index())

   Name  Marks
0   Ram     85
1  Sham     90
2   Ram     85
3  Amit     70

### duplicated()
    Checks duplicate rows

In [7]:
print(df.duplicated()) # 2 Index Row is duplicate

0    False
1    False
2     True
3    False
dtype: bool

### drop_duplicates()
    Removes duplicate rows

In [8]:
print(df.drop_duplicates())

   Name  Marks
0   Ram     85
1  Sham     90
3  Amit     70

### unique()
    Shows unique values

In [10]:
print(df['Name'].unique())

['Ram' 'Sham' 'Amit']

### value_counts()
    Counts occurrences

In [12]:
print(df['Name'].value_counts())

Name
Ram     2
Sham    1
Amit    1
Name: count, dtype: int64

## Aggregating Data
    Summarize your Data

In [13]:
import pandas as pd

data = {
    'Department':['IT','HR','IT','Sales','HR'],
    'Employee':['Ram','Sham','Amit','Riya','Kiran'],
    'Salary':[50000,40000,60000,45000,42000]
}

df = pd.DataFrame(data)

print(df)

  Department Employee  Salary
0         IT      Ram   50000
1         HR     Sham   40000
2         IT     Amit   60000
3      Sales     Riya   45000
4         HR    Kiran   42000

### groupby()
    Groups data based on common values

#### Group by  Salary Sum

In [18]:
print(
    df.groupby('Department')['Salary'].sum()
)
# department wise salary added

Department
HR        82000
IT       110000
Sales     45000
Name: Salary, dtype: int64

### Group by Mean

In [15]:
print(
    df.groupby('Department')['Salary'].mean()
) 
# department wise average salary

Department
HR       41000.0
IT       55000.0
Sales    45000.0
Name: Salary, dtype: float64

### Group by Count

In [17]:
print(
    df.groupby('Department')['Employee'].count()
)
# department wise employee count

Department
HR       2
IT       2
Sales    1
Name: Employee, dtype: int64

### Multiple Aggregation

In [19]:
print(
    df.groupby('Department')['Salary']
    .agg(['sum','mean','max'])
)

               sum     mean    max
Department
HR           82000  41000.0  42000
IT          110000  55000.0  60000
Sales        45000  45000.0  45000

### Group by multiple column

In [26]:
print(
    df.groupby(['Department','Employee'])
    ['Salary'] 
    .agg(['sum'])
)

                       sum
Department Employee
HR         Kiran     42000
           Sham      40000
IT         Amit      60000
           Ram       50000
Sales      Riya      45000

### Reset Index
    Convert grouped index into columns

In [30]:
result = df.groupby('Department')['Salary'].sum()
print(result,"\n")

print(result.reset_index())

Department
HR        82000
IT       110000
Sales     45000
Name: Salary, dtype: int64

  Department  Salary
0         HR   82000
1         IT  110000
2      Sales   45000

## Pandas Merge & Join
    Combine dataframes using Comman Columns

### First Dataframe

In [31]:
import pandas as pd

df1 = pd.DataFrame({
    'ID':[1,2,3],
    'Name':['Ram','Sham','Amit']
})

print(df1)

   ID  Name
0   1   Ram
1   2  Sham
2   3  Amit

### Second Dataframe

In [33]:
df2 = pd.DataFrame({
    'ID':[1,2,4],
    'Salary':[50000,60000,70000]
})

print(df2)

   ID  Salary
0   1   50000
1   2   60000
2   4   70000

### merge() OR Inner Join

In [34]:
pd.merge(df1, df2, on='ID')

   ID  Name  Salary
0   1   Ram   50000
1   2  Sham   60000

In [37]:
pd.merge(df1, df2, on='ID',how ='inner')

   ID  Name  Salary
0   1   Ram   50000
1   2  Sham   60000

### Left Join
    Left table gets priority
    Match not found in second table then put it as null

In [38]:
pd.merge(df1, df2, on='ID',how="left")

   ID  Name   Salary
0   1   Ram  50000.0
1   2  Sham  60000.0
2   3  Amit      NaN

### Right Join
    Right table gets priority
    Match not found in first table puts null

In [40]:
pd.merge(df1, df2, on='ID',how ='right')

   ID  Name  Salary
0   1   Ram   50000
1   2  Sham   60000
2   4   NaN   70000

### Outer OR Full Join
    Priority goes for both tables
    Gets Everything from both tables
    Match not found then puts null values

In [43]:
pd.merge(df1, df2, on='ID',how='outer')

   ID  Name   Salary
0   1   Ram  50000.0
1   2  Sham  60000.0
2   3  Amit      NaN
3   4   NaN  70000.0