## HANLING MISSING DATAS
      Deal with missing values

In [3]:
import pandas as pd

import numpy as np

In [8]:
# Adding Null Value np.nan
data = {
    'Name':['Ram','Sham','Amit'],
    'Marks':[85,np.nan,70],          
    'Age':[21,22,np.nan]
       }                       

df = pd.DataFrame(data)

print(df)

   Name  Marks   Age
0   Ram   85.0  21.0
1  Sham    NaN  22.0
2  Amit   70.0   NaN

### isnull()
    Checks missing values

In [9]:
print(df.isnull())

    Name  Marks    Age
0  False  False  False
1  False   True  False
2  False  False   True

### Count missing value

In [10]:
print(df.isnull().sum())

Name     0
Marks    1
Age      1
dtype: int64

### notnull()
    Checks available values

In [11]:
print(df.notnull())

   Name  Marks    Age
0  True   True   True
1  True  False   True
2  True   True  False

### dropna()
    Removes missing values rows

In [12]:
print(df.dropna())

  Name  Marks   Age
0  Ram   85.0  21.0

### fillna()
    Fills missing values

In [15]:
print(df.fillna(0))

   Name  Marks   Age
0   Ram   85.0  21.0
1  Sham    0.0  22.0
2  Amit   70.0   0.0

### Fill Using mean

In [16]:
df['Marks'] = df['Marks'].fillna(
    df['Marks'].mean()
)

print(df)

   Name  Marks   Age
0   Ram   85.0  21.0
1  Sham   77.5  22.0
2  Amit   70.0   NaN

### replace()
    Replace Values

In [17]:
print(df.replace(70,75)) # Change 70 To 80

   Name  Marks   Age
0   Ram   85.0  21.0
1  Sham   77.5  22.0
2  Amit   75.0   NaN

### interpolate()
    Missing Values Fills Approximately

In [20]:
df = df.infer_objects(copy=False) # It Works Mainly On Numeric Data

print(df.interpolate())

   Name  Marks   Age
0   Ram   85.0  21.0
1  Sham   77.5  22.0
2  Amit   70.0  22.0

C:\Users\SANDESH\AppData\Local\Temp\ipykernel_11168\1207680619.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  print(df.interpolate())

### READING DATA
    Load data from different format

### pd.read_csv('data.csv')
### pd.read_excel('data.xlsx')
### pd.read_json('data.json')
### pd.read_sql('query',conn)

In [25]:
import pandas as pd

cols = [
    "State","Y2002","Y2003","Y2004",
    "Y2005","Y2006","Y2007","Y2008","Y2009",
    "Y2010","Y2011","Y2012","Y2013","Y2014","Y2015"
]

df = pd.read_csv(
    r"C:\Users\SANDESH\Downloads\dplyr.csv",
    header=None,
    names=cols
)


df

,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
5,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
7,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
8,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
9,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
13,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
16,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
19,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
20,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
21,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
22,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
23,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
24,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
25,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
26,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
27,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
28,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
29,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
30,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
31,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
32,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
33,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
35,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
36,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
38,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
40,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
41,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
42,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

### First Five Rows

In [21]:
df.head()

,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607

### Last Five Rows

In [22]:
df.tail()

,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
46,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

### Shape Of DataFrame

In [23]:
df.shape

(51, 15)

### Column Names

In [24]:
df.columns

Index(['State', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007', 'Y2008',
       'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015'],
      dtype='object')

### To Save Changes

In [29]:
df.to_csv(r"C:\Users\SANDESH\Downloads\new_dplyr.csv")

In [32]:
df = pd.read_csv(
    r"C:\Users\SANDESH\Downloads\new_dplyr.csv",index_col=0)
df

,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
5,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
7,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
8,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
9,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
13,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
16,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
19,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
20,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
21,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
22,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
23,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
24,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
25,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
26,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
27,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
28,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
29,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
30,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
31,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
32,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
33,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
35,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
36,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
38,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
40,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
41,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
42,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858