## Text/String Cleaning

In [1]:
import pandas as pd

### Reading File

In [3]:
dfm=pd.read_csv(r"C:\Users\SANDESH\Downloads\dirty_rows_02.csv")

### Copy File

In [4]:
df=dfm.copy()
df.head()

,Employee_ID,Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,sandesh patil,Data Analyst,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,pooja patil,DATA ANALYST,BELGAUM,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul Sharma,Business Analyst,belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay Kumar,Data Analyst,PUNE,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay Kumar,Data Analyst,BELGAUM,40000.0,4.0,employee@company.com,9.876543e+09

In [5]:
df.tail()

,Employee_ID,Name,Department,City,Salary,Experience_Years,Email,Phone
495,1496,Akshay Kumar,data analyst,BELGAUM,40000.0,5.0,TEST@MAIL.COM,NaN
496,1497,SANJAY PATIL,Business Analyst,Bangalore,NaN,2.0,user@example.com,NaN
497,1498,Akshay Kumar,Business Analyst,Bangalore,25000.0,2.0,user@example.com,9.876543e+09
498,1499,pooja patil,data analyst,BELGAUM,NaN,1.0,employee@company.com,9.876543e+09
499,1500,sandesh patil,Business Analyst,belgaum,NaN,2.0,user@example.com,9.876543e+09

### Rows And Column Shape

In [6]:
df.shape

(500, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       500 non-null    int64
 1   Name              500 non-null    object
 2   Department        500 non-null    object
 3   City              500 non-null    object
 4   Salary            397 non-null    float64
 5   Experience_Years  429 non-null    float64
 6   Email             500 non-null    object
 7   Phone             330 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 31.4+ KB

### Check Data Types

In [54]:
df.dtypes

Employee_ID           int64
First_Name           object
Last_Name            object
Department           object
City                 object
Salary              float64
Experience_Years    float64
Email                object
Phone               float64
dtype: object

### Change Fhone Column Data Type

In [ ]:
df["Phone"] = df["Phone"].fillna("Not Available")

df["Phone"] = df["Phone"].astype("string")

### Columns Striping

In [8]:
df.columns = df.columns.str.strip()
df.head()

,Employee_ID,Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,sandesh patil,Data Analyst,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,pooja patil,DATA ANALYST,BELGAUM,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul Sharma,Business Analyst,belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay Kumar,Data Analyst,PUNE,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay Kumar,Data Analyst,BELGAUM,40000.0,4.0,employee@company.com,9.876543e+09

### Name Column Strip

In [9]:
df["Name"] = df["Name"].str.strip()
df.head()

,Employee_ID,Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,sandesh patil,Data Analyst,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,pooja patil,DATA ANALYST,BELGAUM,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul Sharma,Business Analyst,belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay Kumar,Data Analyst,PUNE,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay Kumar,Data Analyst,BELGAUM,40000.0,4.0,employee@company.com,9.876543e+09

### Proper Name

In [10]:
df["Name"] = df["Name"].str.title()
df.head(10)

,Employee_ID,Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh Patil,Data Analyst,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,Pooja Patil,DATA ANALYST,BELGAUM,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul Sharma,Business Analyst,belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay Kumar,Data Analyst,PUNE,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay Kumar,Data Analyst,BELGAUM,40000.0,4.0,employee@company.com,9.876543e+09
5,1006,Akshay Kumar,data analyst,PUNE,35000.0,4.0,TEST@MAIL.COM,NaN
6,1007,Sanjay Patil,DATA ANALYST,Bangalore,25000.0,5.0,TEST@MAIL.COM,NaN
7,1008,Akshay Kumar,DATA ANALYST,belgaum,35000.0,4.0,user@example.com,9.123457e+09
8,1009,Rahul Sharma,Business Analyst,mumbai,NaN,NaN,employee@company.com,9.876543e+09
9,1010,Akshay Kumar,Data Analyst,hyderabad,NaN,1.0,user@example.com,9.123457e+09

### Spliting Name

In [25]:
Name_split=df[["First_Name", "Last_Name"]] = df["Name"].str.split(" ",n=1, expand=True)
print(Name_split)

           0        1
0    Sandesh    Patil
1      Pooja    Patil
2      Rahul   Sharma
3     Akshay    Kumar
4     Akshay    Kumar
..       ...      ...
495   Akshay    Kumar
496   Sanjay    Patil
497   Akshay    Kumar
498    Pooja    Patil
499  Sandesh    Patil

[500 rows x 2 columns]

In [27]:
df.head()

,Employee_ID,Name,Department,City,Salary,Experience_Years,Email,Phone,First_Name,Last_Name
0,1001,Sandesh Patil,DATA ANALYST,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09,Sandesh,Patil
1,1002,Pooja Patil,DATA ANALYST,Belgaum,NaN,2.0,user@example.com,9.876543e+09,Pooja,Patil
2,1003,Rahul Sharma,BUSINESS ANALYST,Belgaum,NaN,5.0,user@example.com,NaN,Rahul,Sharma
3,1004,Akshay Kumar,DATA ANALYST,Pune,30000.0,4.0,TEST@MAIL.COM,9.123457e+09,Akshay,Kumar
4,1005,Akshay Kumar,DATA ANALYST,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09,Akshay,Kumar

### Insert At Postion

In [29]:
print(df.columns.tolist())

['Employee_ID', 'Name', 'Department', 'City', 'Salary', 'Experience_Years', 'Email', 'Phone', 'First_Name', 'Last_Name']

In [31]:
first = df.pop("First_Name")
last = df.pop("Last_Name")

df.insert(1, "First_Name", first)
df.insert(2, "Last_Name", last)

df.head()

,Employee_ID,First_Name,Last_Name,Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,Sandesh Patil,DATA ANALYST,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,Pooja,Patil,Pooja Patil,DATA ANALYST,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,Rahul Sharma,BUSINESS ANALYST,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,Akshay Kumar,DATA ANALYST,Pune,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay,Kumar,Akshay Kumar,DATA ANALYST,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09

### Drop Full Name

In [33]:
df.drop("Name", axis=1, inplace=True)

df.head()

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,DATA ANALYST,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,Pooja,Patil,DATA ANALYST,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,BUSINESS ANALYST,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,DATA ANALYST,Pune,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay,Kumar,DATA ANALYST,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09

### Department Clean

### Unique Values

In [21]:
print(df["Department"].unique())

['DATA ANALYST' 'BUSINESS ANALYST']

In [34]:
df["Department"] = df["Department"].str.strip()
df.head()

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,DATA ANALYST,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,Pooja,Patil,DATA ANALYST,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,BUSINESS ANALYST,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,DATA ANALYST,Pune,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay,Kumar,DATA ANALYST,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09

### Lower Case

In [35]:
df["Department"] = df["Department"].str.lower()
df.head(10)

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,data analyst,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,Pooja,Patil,data analyst,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,business analyst,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,data analyst,Pune,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay,Kumar,data analyst,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09
5,1006,Akshay,Kumar,data analyst,Pune,35000.0,4.0,TEST@MAIL.COM,NaN
6,1007,Sanjay,Patil,data analyst,Bangalore,25000.0,5.0,TEST@MAIL.COM,NaN
7,1008,Akshay,Kumar,data analyst,Belgaum,35000.0,4.0,user@example.com,9.123457e+09
8,1009,Rahul,Sharma,business analyst,Mumbai,NaN,NaN,employee@company.com,9.876543e+09
9,1010,Akshay,Kumar,data analyst,Hyderabad,NaN,1.0,user@example.com,9.123457e+09

### Upper Case

In [36]:
df["Department"] = df["Department"].str.upper()
df.head(10)

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,DATA ANALYST,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,Pooja,Patil,DATA ANALYST,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,BUSINESS ANALYST,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,DATA ANALYST,Pune,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay,Kumar,DATA ANALYST,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09
5,1006,Akshay,Kumar,DATA ANALYST,Pune,35000.0,4.0,TEST@MAIL.COM,NaN
6,1007,Sanjay,Patil,DATA ANALYST,Bangalore,25000.0,5.0,TEST@MAIL.COM,NaN
7,1008,Akshay,Kumar,DATA ANALYST,Belgaum,35000.0,4.0,user@example.com,9.123457e+09
8,1009,Rahul,Sharma,BUSINESS ANALYST,Mumbai,NaN,NaN,employee@company.com,9.876543e+09
9,1010,Akshay,Kumar,DATA ANALYST,Hyderabad,NaN,1.0,user@example.com,9.123457e+09

In [37]:
df["Department"] = df["Department"].replace(
    {
      "data analyst":"Data Analyst"
    }
)
df.head(10)

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,DATA ANALYST,Bangalore,30000.0,1.0,TEST@MAIL.COM,9.876543e+09
1,1002,Pooja,Patil,DATA ANALYST,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,BUSINESS ANALYST,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,DATA ANALYST,Pune,30000.0,4.0,TEST@MAIL.COM,9.123457e+09
4,1005,Akshay,Kumar,DATA ANALYST,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09
5,1006,Akshay,Kumar,DATA ANALYST,Pune,35000.0,4.0,TEST@MAIL.COM,NaN
6,1007,Sanjay,Patil,DATA ANALYST,Bangalore,25000.0,5.0,TEST@MAIL.COM,NaN
7,1008,Akshay,Kumar,DATA ANALYST,Belgaum,35000.0,4.0,user@example.com,9.123457e+09
8,1009,Rahul,Sharma,BUSINESS ANALYST,Mumbai,NaN,NaN,employee@company.com,9.876543e+09
9,1010,Akshay,Kumar,DATA ANALYST,Hyderabad,NaN,1.0,user@example.com,9.123457e+09

### In Title

In [46]:
df["Department"] = df["Department"].str.title()
df.head(10)

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,Data Analyst,Bangalore,30000.0,1.0,test@mail.com,9.876543e+09
1,1002,Pooja,Patil,Data Analyst,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,Business Analyst,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,Data Analyst,Pune,30000.0,4.0,test@mail.com,9.123457e+09
4,1005,Akshay,Kumar,Data Analyst,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09
5,1006,Akshay,Kumar,Data Analyst,Pune,35000.0,4.0,test@mail.com,NaN
6,1007,Sanjay,Patil,Data Analyst,Bangalore,25000.0,5.0,test@mail.com,NaN
7,1008,Akshay,Kumar,Data Analyst,Belgaum,35000.0,4.0,user@example.com,9.123457e+09
8,1009,Rahul,Sharma,Business Analyst,Mumbai,NaN,NaN,employee@company.com,9.876543e+09
9,1010,Akshay,Kumar,Data Analyst,Hyderabad,NaN,1.0,user@example.com,9.123457e+09

### City Column

### Checking Unique Values

In [38]:
print(df["City"].unique())
print("\n")

[' Bangalore ' 'Belgaum' 'Pune' 'Mumbai' ' Hyderabad ']

### Convert As Title

In [47]:
df["City"] = df["City"].str.title()
df.head(10)

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,Data Analyst,Bangalore,30000.0,1.0,test@mail.com,9.876543e+09
1,1002,Pooja,Patil,Data Analyst,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,Business Analyst,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,Data Analyst,Pune,30000.0,4.0,test@mail.com,9.123457e+09
4,1005,Akshay,Kumar,Data Analyst,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09
5,1006,Akshay,Kumar,Data Analyst,Pune,35000.0,4.0,test@mail.com,NaN
6,1007,Sanjay,Patil,Data Analyst,Bangalore,25000.0,5.0,test@mail.com,NaN
7,1008,Akshay,Kumar,Data Analyst,Belgaum,35000.0,4.0,user@example.com,9.123457e+09
8,1009,Rahul,Sharma,Business Analyst,Mumbai,NaN,NaN,employee@company.com,9.876543e+09
9,1010,Akshay,Kumar,Data Analyst,Hyderabad,NaN,1.0,user@example.com,9.123457e+09

### Email Column

In [48]:
df["Email"] = df["Email"].str.lower()
df.head(10)

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,Data Analyst,Bangalore,30000.0,1.0,test@mail.com,9.876543e+09
1,1002,Pooja,Patil,Data Analyst,Belgaum,NaN,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,Business Analyst,Belgaum,NaN,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,Data Analyst,Pune,30000.0,4.0,test@mail.com,9.123457e+09
4,1005,Akshay,Kumar,Data Analyst,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09
5,1006,Akshay,Kumar,Data Analyst,Pune,35000.0,4.0,test@mail.com,NaN
6,1007,Sanjay,Patil,Data Analyst,Bangalore,25000.0,5.0,test@mail.com,NaN
7,1008,Akshay,Kumar,Data Analyst,Belgaum,35000.0,4.0,user@example.com,9.123457e+09
8,1009,Rahul,Sharma,Business Analyst,Mumbai,NaN,NaN,employee@company.com,9.876543e+09
9,1010,Akshay,Kumar,Data Analyst,Hyderabad,NaN,1.0,user@example.com,9.123457e+09

### Check Duplicates

In [42]:
df.duplicated().any()

np.False_

In [45]:
print(df["Employee_ID"].duplicated().sum())

0

### Salary Fill Null Value

In [51]:
df["Salary"] = df["Salary"].fillna(0)
df.head()

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,Data Analyst,Bangalore,30000.0,1.0,test@mail.com,9.876543e+09
1,1002,Pooja,Patil,Data Analyst,Belgaum,0.0,2.0,user@example.com,9.876543e+09
2,1003,Rahul,Sharma,Business Analyst,Belgaum,0.0,5.0,user@example.com,NaN
3,1004,Akshay,Kumar,Data Analyst,Pune,30000.0,4.0,test@mail.com,9.123457e+09
4,1005,Akshay,Kumar,Data Analyst,Belgaum,40000.0,4.0,employee@company.com,9.876543e+09

### Proper Phone Number

In [56]:
df["Phone"] = df["Phone"].astype("Int64")
df.head()

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,Data Analyst,Bangalore,30000.0,1.0,test@mail.com,9876543210
1,1002,Pooja,Patil,Data Analyst,Belgaum,0.0,2.0,user@example.com,9876543210
2,1003,Rahul,Sharma,Business Analyst,Belgaum,0.0,5.0,user@example.com,<NA>
3,1004,Akshay,Kumar,Data Analyst,Pune,30000.0,4.0,test@mail.com,9123456780
4,1005,Akshay,Kumar,Data Analyst,Belgaum,40000.0,4.0,employee@company.com,9876543210

In [60]:
print(df['Phone'].isnull().sum)

<bound method Series.sum of 0      False
1      False
2       True
3      False
4      False
       ...
495     True
496     True
497    False
498    False
499    False
Name: Phone, Length: 500, dtype: bool>

### Filled Null Phone Number 0

In [61]:
df["Phone"] = df["Phone"].fillna(0)
df.head()

,Employee_ID,First_Name,Last_Name,Department,City,Salary,Experience_Years,Email,Phone
0,1001,Sandesh,Patil,Data Analyst,Bangalore,30000.0,1.0,test@mail.com,9876543210
1,1002,Pooja,Patil,Data Analyst,Belgaum,0.0,2.0,user@example.com,9876543210
2,1003,Rahul,Sharma,Business Analyst,Belgaum,0.0,5.0,user@example.com,0
3,1004,Akshay,Kumar,Data Analyst,Pune,30000.0,4.0,test@mail.com,9123456780
4,1005,Akshay,Kumar,Data Analyst,Belgaum,40000.0,4.0,employee@company.com,9876543210

#### Save the File

In [62]:
df.to_csv("Cleaned_02.csv", index=False)