## JSON Handling
    -Javascript Object Notation
    -Common in API'S And Web Data

In [1]:
import pandas as pd
import json

In [2]:
data = {
    "Name": ["Aman", "Rahul", "Sneha"],
    
    "Age": [23, 25, 24],
    
    "City": ["Pune", "Mumbai", "Delhi"]
}

data

{'Name': ['Aman', 'Rahul', 'Sneha'],
 'Age': [23, 25, 24],
 'City': ['Pune', 'Mumbai', 'Delhi']}

### Convert Dictionary To Dataframe

In [4]:
df=pd.DataFrame(data)
df

    Name  Age    City
0   Aman   23    Pune
1  Rahul   25  Mumbai
2  Sneha   24   Delhi

### Create JSON File

In [7]:
sample = {
    "Name": ["Aman", "Rahul","Ram","Akash","Sham"],
    "Salary": [50000, 60000,70000,80000,90000]
}

with open("employee.json", "w") as f:
    json.dump(sample, f)

#### Read JSON File

In [8]:
pd.read_json("employee.json")

    Name  Salary
0   Aman   50000
1  Rahul   60000
2    Ram   70000
3  Akash   80000
4   Sham   90000

### Saved Dataframe as JSON

In [9]:
df.to_json("output.json")

#### Read Saved JSON File

In [11]:
pd.read_json("output.json")

    Name  Age    City
0   Aman   23    Pune
1  Rahul   25  Mumbai
2  Sneha   24   Delhi

### JSON Orients

#### records
    -Row wise JSON Dictionary
    -Each row becomes dictionary

In [12]:
df.to_json(orient="records")

'[{"Name":"Aman","Age":23,"City":"Pune"},{"Name":"Rahul","Age":25,"City":"Mumbai"},{"Name":"Sneha","Age":24,"City":"Delhi"}]'

#### Columns

In [13]:
df.to_json(orient="columns")

'{"Name":{"0":"Aman","1":"Rahul","2":"Sneha"},"Age":{"0":23,"1":25,"2":24},"City":{"0":"Pune","1":"Mumbai","2":"Delhi"}}'

### index
    Index becomes key

In [14]:
df.to_json(orient="index")

'{"0":{"Name":"Aman","Age":23,"City":"Pune"},"1":{"Name":"Rahul","Age":25,"City":"Mumbai"},"2":{"Name":"Sneha","Age":24,"City":"Delhi"}}'

### split
    Separate Column Index Data

In [16]:
df.to_json(orient="split")

'{"columns":["Name","Age","City"],"index":[0,1,2],"data":[["Aman",23,"Pune"],["Rahul",25,"Mumbai"],["Sneha",24,"Delhi"]]}'

#### Table
    JSON table schema format

In [17]:
df.to_json(orient="table")

'{"schema":{"fields":[{"name":"index","type":"integer"},{"name":"Name","type":"string"},{"name":"Age","type":"integer"},{"name":"City","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":0,"Name":"Aman","Age":23,"City":"Pune"},{"index":1,"Name":"Rahul","Age":25,"City":"Mumbai"},{"index":2,"Name":"Sneha","Age":24,"City":"Delhi"}]}'

#### Values
    Only Values

In [33]:
df.to_json(orient="values")

'[["Aman",23.0,"Pune"],["Rahul",25.0,"Mumbai"],["Sneha",24.0,"Delhi"]]'

### Create JSON String

In [18]:
json_data = '''
[
    {"Name":"Aman","Salary":50000},
    {"Name":"Rahul","Salary":60000}
]
'''

#### Load JSON 
    Reads JSON file using JSON Module

    loads :- Reads Strings
    load :- Reads File

In [19]:
data = json.loads(json_data)

data

[{'Name': 'Aman', 'Salary': 50000}, {'Name': 'Rahul', 'Salary': 60000}]

### Conversion To DataFrame

In [20]:
df2 = pd.DataFrame(data)

df2

    Name  Salary
0   Aman   50000
1  Rahul   60000

#### NORMALIZE 
    Used for Nested JSON

### Nested JSON

In [25]:
nested_data = [
    {
        "id": 1,
        "Name": "Aman",
        "Education": {
            "Degree": "BCA",
            "Year": 2025
        }
    },

    {
        "id": 2,
        "Name": "Ram",
        "Education": {
            "Degree": "BSC",
            "Year": 2026
        }
    },

    {
        "id": 3,
        "Name": "Sham",
        "Education": {
            "Degree": "MCA",
            "Year": 2024
        }
    }
]

#### json_normalize
    -Converts nested JSON into Flat Table

In [26]:
pd.json_normalize(nested_data)

   id  Name Education.Degree  Education.Year
0   1  Aman              BCA            2025
1   2   Ram              BSC            2026
2   3  Sham              MCA            2024

#### API Style

In [27]:
api_data = {
    "users": [
        {"id":1, "name":"Aman"},
        {"id":2, "name":"Rahul"}
    ]
}

#### Extract Users

In [28]:
users_df = pd.DataFrame(api_data["users"])

users_df

   id   name
0   1   Aman
1   2  Rahul

### Write JSON Line

In [34]:
df.to_json(
    "json_lines.json",
    
    orient="records",
    
    lines=True
)

#### Read JSON Line

In [35]:
pd.read_json(
    "json_lines.json",
    
    lines=True
)

    Name  Age    City
0   Aman   23    Pune
1  Rahul   25  Mumbai
2  Sneha   24   Delhi

#### Print JSON
    -dumps :- Writes String
    -dump :- Writes File

In [36]:
print(
    json.dumps(
        nested_data,
        indent=4
    )
)

[
    {
        "id": 1,
        "Name": "Aman",
        "Education": {
            "Degree": "BCA",
            "Year": 2025
        }
    },
    {
        "id": 2,
        "Name": "Ram",
        "Education": {
            "Degree": "BSC",
            "Year": 2026
        }
    },
    {
        "id": 3,
        "Name": "Sham",
        "Education": {
            "Degree": "MCA",
            "Year": 2024
        }
    }
]

#### Missing values In JSON

In [29]:
data4 = {
    "Name": ["Aman", None],
    
    "Salary": [50000, None]
}

df4 = pd.DataFrame(data4)

df4

   Name   Salary
0  Aman  50000.0
1  None      NaN

In [30]:
df4.to_json()

'{"Name":{"0":"Aman","1":null},"Salary":{"0":50000.0,"1":null}}'

#### Check JSON Datatypes

In [31]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

### Convert Datatype

In [32]:
df["Age"] = df["Age"].astype(float)

df.dtypes

Name     object
Age     float64
City     object
dtype: object