## Pandas Binning,Sampling,Custom Function

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Aman", "Rahul", "Sneha", "Priya",
             "Karan", "Rohit", "Neha", "Pooja"],

    "Marks": [45, 67, 89, 90, 55, 72, 38, 81],

    "Salary": [25000, 40000, 60000, 80000,
               35000, 50000, 22000, 75000]
}

df = pd.DataFrame(data)

df

    Name  Marks  Salary
0   Aman     45   25000
1  Rahul     67   40000
2  Sneha     89   60000
3  Priya     90   80000
4  Karan     55   35000
5  Rohit     72   50000
6   Neha     38   22000
7  Pooja     81   75000

#### BINNING
    Divide Data In Groups

### pd.cut()
    Divide data into Fixed Intervals/Bins

In [3]:
df["Marks_Category"] = pd.cut(
    df["Marks"],
    
    bins=[0, 40, 60, 80, 100],
    
    labels=["Fail", "Average", "Good", "Excellent"]
)

df

    Name  Marks  Salary Marks_Category
0   Aman     45   25000        Average
1  Rahul     67   40000           Good
2  Sneha     89   60000      Excellent
3  Priya     90   80000      Excellent
4  Karan     55   35000        Average
5  Rohit     72   50000           Good
6   Neha     38   22000           Fail
7  Pooja     81   75000      Excellent

### Right Parameter 
    - right decides which side interval is included.
    
        right = False Included Symbol { ] } [0,50) Left Value Included i.e 0

        right = True Excluded Symbol  { ( } (0,50] Right Value Included i.e 50

In [4]:
pd.cut(
    df["Marks"],
    
    bins=[0, 50, 100],
    
    right=False
)

0      [0, 50)
1    [50, 100)
2    [50, 100)
3    [50, 100)
4    [50, 100)
5    [50, 100)
6      [0, 50)
7    [50, 100)
Name: Marks, dtype: category
Categories (2, interval[int64, left]): [[0, 50) < [50, 100)]

### Include Lowest :-To include minimum boundary value in first interval.
        include_lowest = True :- Includes first lowest values

        Include_lowest = False :- lowest value excluded

In [35]:
pd.cut(
    df["Marks"],
    
    bins=[0, 50, 100],
    
    include_lowest=True
)

0    (-0.001, 50.0]
1     (50.0, 100.0]
2     (50.0, 100.0]
3     (50.0, 100.0]
4     (50.0, 100.0]
5     (50.0, 100.0]
6    (-0.001, 50.0]
7     (50.0, 100.0]
Name: Marks, dtype: category
Categories (2, interval[float64, right]): [(-0.001, 50.0] < (50.0, 100.0]]

#### Value Count Of Bins
    Count Frequency Of Values

In [6]:
df["Marks_Category"].value_counts()

Marks_Category
Excellent    3
Average      2
Good         2
Fail         1
Name: count, dtype: int64

### qcut()
    -Divides Data into Equal-Size Distribution Bins

In [7]:
df["Salary_Group"] = pd.qcut(
    df["Salary"],
    
    q=4,
    
    labels=["Low", "Medium", "High", "Very High"]
)

df

    Name  Marks  Salary Marks_Category Salary_Group
0   Aman     45   25000        Average          Low
1  Rahul     67   40000           Good       Medium
2  Sneha     89   60000      Excellent         High
3  Priya     90   80000      Excellent    Very High
4  Karan     55   35000        Average       Medium
5  Rohit     72   50000           Good         High
6   Neha     38   22000           Fail          Low
7  Pooja     81   75000      Excellent    Very High

### SAMPLING
    Used to get random sample
    Random Sample()

In [10]:
df.sample(3)

    Name  Marks  Salary Marks_Category Salary_Group
3  Priya     90   80000      Excellent    Very High
7  Pooja     81   75000      Excellent    Very High
1  Rahul     67   40000           Good       Medium

### Fixed Random State
    Everytime gets Same output

In [12]:
df.sample(
    3,
    
    random_state=1
)

    Name  Marks  Salary Marks_Category Salary_Group
7  Pooja     81   75000      Excellent    Very High
2  Sneha     89   60000      Excellent         High
1  Rahul     67   40000           Good       Medium

### Fraction Sampling
    Fraction sampling selects percentage/fraction of rows.

In [34]:
df.sample(frac=0.5) #Returns 50% rows randomly

,Name,Marks,Salary,Marks_Category,Salary_Group,Updated_Salary,Double_Marks,Grade,Total
7,Pooja,86,77000,Excellent,Very High,80000,162,A,75081
1,Rahul,72,42000,Good,Medium,45000,134,B,40067
3,Priya,95,82000,Excellent,Very High,85000,180,A,80090
5,Rohit,77,52000,Good,High,55000,144,B,50072

### Sampling with Replacement
    Same row can repeat

In [16]:
df.sample(
    5,
    replace=True
)

    Name  Marks  Salary Marks_Category Salary_Group
0   Aman     45   25000        Average          Low
4  Karan     55   35000        Average       Medium
4  Karan     55   35000        Average       Medium
4  Karan     55   35000        Average       Medium
7  Pooja     81   75000      Excellent    Very High

### Weigheted Sampling
    Weighted sampling gives higher chance to selected rows
    1 =Lower Chance
    5 =Higher Chance

In [17]:
weights = [1,2,1,5,1,1,1,3]

df.sample(
    3,
    
    weights=weights
)

    Name  Marks  Salary Marks_Category Salary_Group
6   Neha     38   22000           Fail          Low
7  Pooja     81   75000      Excellent    Very High
2  Sneha     89   60000      Excellent         High

### Custom Function
    Function created by user

### Sample Function

In [18]:
def bonus(salary):
    
    return salary + 5000

#### Apply custom Function

In [19]:
df["Updated_Salary"] = df["Salary"].apply(bonus)

df

    Name  Marks  Salary Marks_Category Salary_Group  Updated_Salary
0   Aman     45   25000        Average          Low           30000
1  Rahul     67   40000           Good       Medium           45000
2  Sneha     89   60000      Excellent         High           65000
3  Priya     90   80000      Excellent    Very High           85000
4  Karan     55   35000        Average       Medium           40000
5  Rohit     72   50000           Good         High           55000
6   Neha     38   22000           Fail          Low           27000
7  Pooja     81   75000      Excellent    Very High           80000

### Lambada function

In [20]:
df["Double_Marks"] = df["Marks"].apply(
    lambda x: x * 2
)

df

,Name,Marks,Salary,Marks_Category,Salary_Group,Updated_Salary,Double_Marks
0,Aman,45,25000,Average,Low,30000,90
1,Rahul,67,40000,Good,Medium,45000,134
2,Sneha,89,60000,Excellent,High,65000,178
3,Priya,90,80000,Excellent,Very High,85000,180
4,Karan,55,35000,Average,Medium,40000,110
5,Rohit,72,50000,Good,High,55000,144
6,Neha,38,22000,Fail,Low,27000,76
7,Pooja,81,75000,Excellent,Very High,80000,162

#### With Condition Forms Grade

In [21]:
def grade(marks):
    
    if marks >= 80:
        return "A"
    
    elif marks >= 60:
        return "B"
    
    elif marks >= 40:
        return "C"
    
    else:
        return "Fail"

#### Apply on multiple column

In [23]:
def total(row):
    
    return row["Marks"] + row["Salary"]

In [24]:
df["Total"] = df.apply(
    total,
    
    axis=1
)

df

,Name,Marks,Salary,Marks_Category,Salary_Group,Updated_Salary,Double_Marks,Grade,Total
0,Aman,45,25000,Average,Low,30000,90,C,25045
1,Rahul,67,40000,Good,Medium,45000,134,B,40067
2,Sneha,89,60000,Excellent,High,65000,178,A,60089
3,Priya,90,80000,Excellent,Very High,85000,180,A,80090
4,Karan,55,35000,Average,Medium,40000,110,C,35055
5,Rohit,72,50000,Good,High,55000,144,B,50072
6,Neha,38,22000,Fail,Low,27000,76,Fail,22038
7,Pooja,81,75000,Excellent,Very High,80000,162,A,75081

### map() with Custom Function

In [25]:
df["Marks"] = df["Marks"].map(
    lambda x: x + 5
)

df

,Name,Marks,Salary,Marks_Category,Salary_Group,Updated_Salary,Double_Marks,Grade,Total
0,Aman,50,25000,Average,Low,30000,90,C,25045
1,Rahul,72,40000,Good,Medium,45000,134,B,40067
2,Sneha,94,60000,Excellent,High,65000,178,A,60089
3,Priya,95,80000,Excellent,Very High,85000,180,A,80090
4,Karan,60,35000,Average,Medium,40000,110,C,35055
5,Rohit,77,50000,Good,High,55000,144,B,50072
6,Neha,43,22000,Fail,Low,27000,76,Fail,22038
7,Pooja,86,75000,Excellent,Very High,80000,162,A,75081

### applymap() With custom function

In [26]:
num_df = pd.DataFrame({
    "A": [1,2],
    "B": [3,4]
})

num_df.map(lambda x: x * 10)

    A   B
0  10  30
1  20  40

### pipe() With custom function

In [27]:
def add_bonus(data):
    
    data["Salary"] = data["Salary"] + 2000
    
    return data

In [28]:
df.pipe(add_bonus)

,Name,Marks,Salary,Marks_Category,Salary_Group,Updated_Salary,Double_Marks,Grade,Total
0,Aman,50,27000,Average,Low,30000,90,C,25045
1,Rahul,72,42000,Good,Medium,45000,134,B,40067
2,Sneha,94,62000,Excellent,High,65000,178,A,60089
3,Priya,95,82000,Excellent,Very High,85000,180,A,80090
4,Karan,60,37000,Average,Medium,40000,110,C,35055
5,Rohit,77,52000,Good,High,55000,144,B,50072
6,Neha,43,24000,Fail,Low,27000,76,Fail,22038
7,Pooja,86,77000,Excellent,Very High,80000,162,A,75081

#### Advance Binning

#### BIN LABELS
    Labels give custom names to bins/categories.

In [29]:
bins = [0,40,60,80,100]

labels = ["Fail","Average","Good","Excellent"]

pd.cut(
    df["Marks"],
    
    bins=bins,
    
    labels=labels
)

0      Average
1         Good
2    Excellent
3    Excellent
4      Average
5         Good
6      Average
7    Excellent
Name: Marks, dtype: category
Categories (4, object): ['Fail' < 'Average' < 'Good' < 'Excellent']

#### WITHOUT LABELS

In [30]:
pd.cut(
    df["Marks"],
    
    bins=4
)

0    (42.948, 56.0]
1      (69.0, 82.0]
2      (82.0, 95.0]
3      (82.0, 95.0]
4      (56.0, 69.0]
5      (69.0, 82.0]
6    (42.948, 56.0]
7      (82.0, 95.0]
Name: Marks, dtype: category
Categories (4, interval[float64, right]): [(42.948, 56.0] < (56.0, 69.0] < (69.0, 82.0] < (82.0, 95.0]]