## METHOD CHAINING & VECTORIZATION

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Aman", "Rahul", "Sneha", "Priya"],
    
    "Department": ["IT", "HR", "Finance", "IT"],
    
    "Salary": [50000, 60000, 70000, 80000],
    
    "Bonus": [5000, 6000, 7000, 8000]
}

df = pd.DataFrame(data)

df

    Name Department  Salary  Bonus
0   Aman         IT   50000   5000
1  Rahul         HR   60000   6000
2  Sneha    Finance   70000   7000
3  Priya         IT   80000   8000

### CHAINING 
    Means Connecting Multiple Methods Together.

### Without Chaining

In [3]:
df1 = df.sort_values(by="Salary")

df2 = df1.head(2)

df2

    Name Department  Salary  Bonus
0   Aman         IT   50000   5000
1  Rahul         HR   60000   6000

### With Chaining

In [4]:
df.sort_values(
    by="Salary"
).head(2)

    Name Department  Salary  Bonus
0   Aman         IT   50000   5000
1  Rahul         HR   60000   6000

### Multiple Chaining

In [5]:
df.query(
    "Salary > 55000"
).sort_values(
    by="Salary"
).head(2)

    Name Department  Salary  Bonus
1  Rahul         HR   60000   6000
2  Sneha    Finance   70000   7000

### Chaining With assign()
    create new column during chaining

In [6]:
df.assign(
    Tax = df["Salary"] * 0.1
)

    Name Department  Salary  Bonus     Tax
0   Aman         IT   50000   5000  5000.0
1  Rahul         HR   60000   6000  6000.0
2  Sneha    Finance   70000   7000  7000.0
3  Priya         IT   80000   8000  8000.0

### Chaining With rename()

In [7]:
df.rename(
    columns={"Salary":"Income"}
).head()

    Name Department  Income  Bonus
0   Aman         IT   50000   5000
1  Rahul         HR   60000   6000
2  Sneha    Finance   70000   7000
3  Priya         IT   80000   8000

### Chaining With drop()

In [8]:
df.drop(
    columns=["Bonus"]
).head()

    Name Department  Salary
0   Aman         IT   50000
1  Rahul         HR   60000
2  Sneha    Finance   70000
3  Priya         IT   80000

### Chaining with pipe()

In [9]:
def add_bonus(data):
    
    data["Salary"] = data["Salary"] + 5000
    
    return data

In [10]:
df.pipe(add_bonus)

    Name Department  Salary  Bonus
0   Aman         IT   55000   5000
1  Rahul         HR   65000   6000
2  Sneha    Finance   75000   7000
3  Priya         IT   85000   8000

### Advance Chaining

In [11]:
(
    df
    .query("Salary > 50000")
    .assign(Tax = lambda x: x["Salary"] * 0.1)
    .sort_values(by="Salary")
)

    Name Department  Salary  Bonus     Tax
0   Aman         IT   55000   5000  5500.0
1  Rahul         HR   65000   6000  6500.0
2  Sneha    Finance   75000   7000  7500.0
3  Priya         IT   85000   8000  8500.0

## VECTORIZATION
    Performs operations on entire column at once.

### Simple Addition

In [13]:
df["Salary"] + 1000

0    56000
1    66000
2    76000
3    86000
Name: Salary, dtype: int64

### Vector Multiplecation

In [14]:
df["Salary"] * 2

0    110000
1    130000
2    150000
3    170000
Name: Salary, dtype: int64

### Creation Of New Column

In [15]:
df["Total"] = df["Salary"] + df["Bonus"]

df

    Name Department  Salary  Bonus  Total
0   Aman         IT   55000   5000  60000
1  Rahul         HR   65000   6000  71000
2  Sneha    Finance   75000   7000  82000
3  Priya         IT   85000   8000  93000

### Vector Comparison

In [16]:
df["Salary"] > 60000

0    False
1     True
2     True
3     True
Name: Salary, dtype: bool

### Vector filtering

In [17]:
df[df["Salary"] > 60000]

    Name Department  Salary  Bonus  Total
1  Rahul         HR   65000   6000  71000
2  Sneha    Finance   75000   7000  82000
3  Priya         IT   85000   8000  93000

### Vector String Operation
    str :- String Vector

In [18]:
df["Name"].str.upper()

0     AMAN
1    RAHUL
2    SNEHA
3    PRIYA
Name: Name, dtype: object

### String length

In [20]:
df["Name"].str.len()

0    4
1    5
2    5
3    5
Name: Name, dtype: int64

### Vector Date Operations
    dt :- Date Vector

In [21]:
date_df = pd.DataFrame({
    "Date": pd.to_datetime([
        "2025-01-01",
        "2025-02-01"
    ])
})

date_df

        Date
0 2025-01-01
1 2025-02-01

### Extract Year

In [22]:
date_df["Date"].dt.year

0    2025
1    2025
Name: Date, dtype: int32

### Extract Month

In [23]:
date_df["Date"].dt.month

0    1
1    2
Name: Date, dtype: int32

### Numpy Vectorization

In [24]:
arr = np.array([1,2,3,4])

arr * 10

array([10, 20, 30, 40])

### where()

In [25]:
df["Status"] = np.where(
    df["Salary"] > 60000,
    
    "High",
    
    "Low"
)

df

    Name Department  Salary  Bonus  Total Status
0   Aman         IT   55000   5000  60000    Low
1  Rahul         HR   65000   6000  71000   High
2  Sneha    Finance   75000   7000  82000   High
3  Priya         IT   85000   8000  93000   High

### Vector Conditional

In [26]:
df["Bonus_10%"] = df["Salary"] * 0.10

df

    Name Department  Salary  Bonus  Total Status  Bonus_10%
0   Aman         IT   55000   5000  60000    Low     5500.0
1  Rahul         HR   65000   6000  71000   High     6500.0
2  Sneha    Finance   75000   7000  82000   High     7500.0
3  Priya         IT   85000   8000  93000   High     8500.0

### apply() VS Vectorization

In [49]:
print("Using Apply:-\n",df["Salary"].apply(lambda x: x + 1000))


print("Using Vectorization:-\n",df["Salary"] + 1000) # Vectorization,its Faster

Using Apply:-
 0    56000
1    66000
2    76000
3    86000
Name: Salary, dtype: int64
Using Vectorization:-
 0    56000
1    66000
2    76000
3    86000
Name: Salary, dtype: int64

### Loop VS Vectorization

In [50]:
result = []

for i in df["Salary"]:
    
    result.append(i + 1000)

print("Using Loop:-",result,"\n")

print("Using Vectorization:-\n",df["Salary"] + 1000) # Vectorization less Code + High Performance

Using Loop:- [56000, 66000, 76000, 86000]

Using Vectorization:-
 0    56000
1    66000
2    76000
3    86000
Name: Salary, dtype: int64

### Performance Example

In [51]:
large = pd.DataFrame({
    "A": np.random.randint(1,100,100000)
})

### Vector performance

In [52]:
large["A"] * 2

0        148
1        108
2        196
3        194
4        166
        ...
99995    174
99996     78
99997    188
99998      2
99999     14
Name: A, Length: 100000, dtype: int32

### eval()
    Fast Chaining Operations

In [53]:
df.eval(
    "Total = Salary + Bonus"
)

    Name Department  Salary  Bonus  Total Status  Bonus_10%
0   Aman         IT   55000   5000  60000    Low     5500.0
1  Rahul         HR   65000   6000  71000   High     6500.0
2  Sneha    Finance   75000   7000  82000   High     7500.0
3  Priya         IT   85000   8000  93000   High     8500.0

### query()

In [54]:
(
    df
    .query("Salary > 50000")
    .sort_values(by="Salary")
)

    Name Department  Salary  Bonus  Total Status  Bonus_10%
0   Aman         IT   55000   5000  60000    Low     5500.0
1  Rahul         HR   65000   6000  71000   High     6500.0
2  Sneha    Finance   75000   7000  82000   High     7500.0
3  Priya         IT   85000   8000  93000   High     8500.0

### np.select()

In [55]:
conditions = [
    df["Salary"] > 70000,
    df["Salary"] > 50000
]

choices = ["High", "Medium"]

df["Level"] = np.select(
    conditions,
    choices,
    default="Low"
)

df

    Name Department  Salary  Bonus  Total Status  Bonus_10%   Level
0   Aman         IT   55000   5000  60000    Low     5500.0  Medium
1  Rahul         HR   65000   6000  71000   High     6500.0  Medium
2  Sneha    Finance   75000   7000  82000   High     7500.0    High
3  Priya         IT   85000   8000  93000   High     8500.0    High

### clip()
    Limits values between min AND mav Boundary

In [57]:
df["Salary"].clip(
    lower=40000,
    
    upper=70000
)

0    55000
1    65000
2    70000
3    70000
Name: Salary, dtype: int64

### Chaining With GroupBy

In [58]:
(
    df
    .groupby("Department")
    ["Salary"]
    .mean()
    .sort_values()
)

Department
HR         65000.0
IT         70000.0
Finance    75000.0
Name: Salary, dtype: float64