## PANDAS-DATAFRAME
    DataFrame is a 2-dimensional labeled table.

In [2]:
import pandas as pd

### Create Dataframe

In [3]:
import pandas as pd

data = {
    'Name':['Ram','Sham','Amit'],
    'Age':[21,22,20],
    'Marks':[85,90,88]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ram   21     85
1  Sham   22     90
2  Amit   20     88

### Access Column

In [4]:
print(df['Name'])

0     Ram
1    Sham
2    Amit
Name: Name, dtype: object

### Access Multiple Column

In [5]:
print(df[['Name','Marks']])

   Name  Marks
0   Ram     85
1  Sham     90
2  Amit     88

### Access Row

In [6]:
print(df.loc[1]) #Index Row 1 displayed

Name     Sham
Age        22
Marks      90
Name: 1, dtype: object

In [8]:
print(df.iloc[-1]) # Access Last Row

Name     Amit
Age        20
Marks      88
Name: 2, dtype: object

### head() Function
    Show First Rows

In [12]:
df.head(2)

   Name  Age  Marks
0   Ram   21     85
1  Sham   22     90

### tail() Function
    Shows Last Rows

In [11]:
df.tail(2)

   Name  Age  Marks
1  Sham   22     90
2  Amit   20     88

### Shape() Function
    Returns rows and columns count

In [14]:
df.shape

(3, 3)

### Column Function
Gives Column Names

In [16]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='object')

### info() function
    Gives Summury of dataframe

In [17]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

### describe Function
    Gives statistics of numerical column

In [18]:
print(df.describe())

        Age      Marks
count   3.0   3.000000
mean   21.0  87.666667
std     1.0   2.516611
min    20.0  85.000000
25%    20.5  86.500000
50%    21.0  88.000000
75%    21.5  89.000000
max    22.0  90.000000

In [111]:
data = {
    'Name':['Ram','Sham','Amit','Riya'],
    'Age':[21,22,20,23],
    'Marks':[85,90,70,95]
}

df1 = pd.DataFrame(data)

print(df1)

   Name  Age  Marks
0   Ram   21     85
1  Sham   22     90
2  Amit   20     70
3  Riya   23     95

### loc[]
    Access data using labels/index names

In [112]:
print(df1.loc[1])

Name     Sham
Age        22
Marks      90
Name: 1, dtype: object

In [113]:
print(df1.loc[3,'Name'])  # Row + Column Labeled

Riya

### iloc[]
    Access data using integer position
    Syntax:-iloc[row_position , column_position]

In [114]:
print(df1.iloc[0]) # Gives 2 Index Data

Name     Ram
Age       21
Marks     85
Name: 0, dtype: object

In [115]:
print(df1.iloc[2,1]) # Row + Column Position

20

### Filtering Data

In [116]:
print(df1[df1['Marks'] > 80]) # Displaying Values Where Marks Greater Than 80

   Name  Age  Marks
0   Ram   21     85
1  Sham   22     90
3  Riya   23     95

#### Multiple Condition
    AND

In [118]:
print(
    df1[
        (df1['Marks'] > 80) &
        (df1['Age'] > 21)
    ]
)

   Name  Age  Marks
1  Sham   22     90
3  Riya   23     95

#### OR Condition

In [119]:
print(
    df1[
        (df1['Marks'] > 90) |
        (df1['Age'] < 21)
    ]
)

   Name  Age  Marks
2  Amit   20     70
3  Riya   23     95

#### Filtering Specific Column

In [120]:
print(
    df1.loc[
        df1['Marks'] > 70,
        ['Name','Age','Marks']
    ]
)

   Name  Age  Marks
0   Ram   21     85
1  Sham   22     90
3  Riya   23     95

In [130]:
data = {
    'Name':['Ram','Sham','Amit','Raj'],
    'Marks':[85,90,70,80]
}

df = pd.DataFrame(data)

print(df)

   Name  Marks
0   Ram     85
1  Sham     90
2  Amit     70
3   Raj     80

### Add New Column

In [103]:
df['Grade'] = ['A','A','B',"A"]

print(df)

   Name  Marks Grade
0   Ram     85     A
1  Sham     90     A
2  Amit     70     B
3   Raj     80     A

### Update Column

In [95]:
df['Marks'] = df['Marks'] + 5 # Marks 5 Added To Each Student
print(df)

   Name  Marks Grade
0   Ram     90     A
1  Sham     95     A
2  Amit     75     B
3   Raj     85     A

#### Update Specific Value

In [96]:
df.loc[2,'Marks'] = 60 # Marks Added To Index 2 Amit

print(df)

   Name  Marks Grade
0   Ram     90     A
1  Sham     95     A
2  Amit     60     B
3   Raj     85     A

### Delete Column
    drop() Function

In [104]:
df.drop('Grade', axis=1, inplace=True) # Grade Column Deleted Permenet From Dataframe

print(df)

   Name  Marks
0   Ram     85
1  Sham     90
2  Amit     70
3   Raj     80

### Delete Row

In [97]:
df=df.drop(2) 
df

   Name  Marks Grade
0   Ram     90     A
1  Sham     95     A
3   Raj     85     A

### Delete Multiple Rows

In [98]:
df = df.drop([0,1])
df

  Name  Marks Grade
3  Raj     85     A

### Rename Column
    rename() Function

In [49]:
df.rename(
    columns={'Marks':'Score'},
    inplace=True
)

print(df)

   Name  Score
0   Ram    100
1  Sham    105
2  Amit     60

### Insert Column
    insert(position, column_name, values)

In [131]:
df.insert(1,'Age',[21,22,20,25])

print(df)

   Name  Age  Marks
0   Ram   21     85
1  Sham   22     90
2  Amit   20     70
3   Raj   25     80