## Pandas Window Function
    - Moving average & analysis
    - Perform calculation on group of rows

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Day": [1,2,3,4,5,6,7,8],
    
    "Sales": [100,120,140,130,150,170,160,180],
    
    "Profit": [20,25,30,28,35,40,38,45]
}

df = pd.DataFrame(data)

df

   Day  Sales  Profit
0    1    100      20
1    2    120      25
2    3    140      30
3    4    130      28
4    5    150      35
5    6    170      40
6    7    160      38
7    8    180      45

### rolling()
    Creates Moving Window Calculation

### Rolling Mean

In [3]:
df["Rolling_Mean"] = df["Sales"].rolling(3).mean()

df

   Day  Sales  Profit  Rolling_Mean
0    1    100      20           NaN
1    2    120      25           NaN
2    3    140      30         120.0
3    4    130      28         130.0
4    5    150      35         140.0
5    6    170      40         150.0
6    7    160      38         160.0
7    8    180      45         170.0

### Rolling Sum

In [4]:
df["Rolling_Sum"] = df["Sales"].rolling(3).sum()

df

   Day  Sales  Profit  Rolling_Mean  Rolling_Sum
0    1    100      20           NaN          NaN
1    2    120      25           NaN          NaN
2    3    140      30         120.0        360.0
3    4    130      28         130.0        390.0
4    5    150      35         140.0        420.0
5    6    170      40         150.0        450.0
6    7    160      38         160.0        480.0
7    8    180      45         170.0        510.0

### Rolling Max

In [8]:
df["Rolling_Max"] = df["Sales"].rolling(3).max()

df

   Day  Sales  Profit  Rolling_Mean  Rolling_Sum  Rolling_Max  Rolling_Min
0    1    100      20           NaN          NaN          NaN          NaN
1    2    120      25           NaN          NaN          NaN          NaN
2    3    140      30         120.0        140.0        140.0        100.0
3    4    130      28         130.0        140.0        140.0        120.0
4    5    150      35         140.0        150.0        150.0        130.0
5    6    170      40         150.0        170.0        170.0        130.0
6    7    160      38         160.0        170.0        170.0        150.0
7    8    180      45         170.0        180.0        180.0        160.0

### Rolling Min

In [9]:
df["Rolling_Min"] = df["Sales"].rolling(3).min()

df

   Day  Sales  Profit  Rolling_Mean  Rolling_Sum  Rolling_Max  Rolling_Min
0    1    100      20           NaN          NaN          NaN          NaN
1    2    120      25           NaN          NaN          NaN          NaN
2    3    140      30         120.0        140.0        140.0        100.0
3    4    130      28         130.0        140.0        140.0        120.0
4    5    150      35         140.0        150.0        150.0        130.0
5    6    170      40         150.0        170.0        170.0        130.0
6    7    160      38         160.0        170.0        170.0        150.0
7    8    180      45         170.0        180.0        180.0        160.0

### Rolling Count

In [10]:
df["Rolling_Count"] = df["Sales"].rolling(3).count()

df

,Day,Sales,Profit,Rolling_Mean,Rolling_Sum,Rolling_Max,Rolling_Min,Rolling_Count
0,1,100,20,NaN,NaN,NaN,NaN,NaN
1,2,120,25,NaN,NaN,NaN,NaN,NaN
2,3,140,30,120.0,140.0,140.0,100.0,3.0
3,4,130,28,130.0,140.0,140.0,120.0,3.0
4,5,150,35,140.0,150.0,150.0,130.0,3.0
5,6,170,40,150.0,170.0,170.0,130.0,3.0
6,7,160,38,160.0,170.0,170.0,150.0,3.0
7,8,180,45,170.0,180.0,180.0,160.0,3.0

### Rolling STD

In [11]:
df["Rolling_STD"] = df["Sales"].rolling(3).std()

df

,Day,Sales,Profit,Rolling_Mean,Rolling_Sum,Rolling_Max,Rolling_Min,Rolling_Count,Rolling_STD
0,1,100,20,NaN,NaN,NaN,NaN,NaN,NaN
1,2,120,25,NaN,NaN,NaN,NaN,NaN,NaN
2,3,140,30,120.0,140.0,140.0,100.0,3.0,20.0
3,4,130,28,130.0,140.0,140.0,120.0,3.0,10.0
4,5,150,35,140.0,150.0,150.0,130.0,3.0,10.0
5,6,170,40,150.0,170.0,170.0,130.0,3.0,20.0
6,7,160,38,160.0,170.0,170.0,150.0,3.0,10.0
7,8,180,45,170.0,180.0,180.0,160.0,3.0,10.0

### Rolling VAR

In [12]:
df["Rolling_Var"] = df["Sales"].rolling(3).var()

df

,Day,Sales,Profit,Rolling_Mean,Rolling_Sum,Rolling_Max,Rolling_Min,Rolling_Count,Rolling_STD,Rolling_Var
0,1,100,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,120,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,140,30,120.0,140.0,140.0,100.0,3.0,20.0,400.0
3,4,130,28,130.0,140.0,140.0,120.0,3.0,10.0,100.0
4,5,150,35,140.0,150.0,150.0,130.0,3.0,10.0,100.0
5,6,170,40,150.0,170.0,170.0,130.0,3.0,20.0,400.0
6,7,160,38,160.0,170.0,170.0,150.0,3.0,10.0,100.0
7,8,180,45,170.0,180.0,180.0,160.0,3.0,10.0,100.0

### min_periods
    Starts calculation before full window size

In [13]:
df["Rolling_Mean_2"] = df["Sales"].rolling(
    window=3,
    min_periods=1
).mean()

df

,Day,Sales,Profit,Rolling_Mean,Rolling_Sum,Rolling_Max,Rolling_Min,Rolling_Count,Rolling_STD,Rolling_Var,Rolling_Mean_2
0,1,100,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
1,2,120,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0
2,3,140,30,120.0,140.0,140.0,100.0,3.0,20.0,400.0,120.0
3,4,130,28,130.0,140.0,140.0,120.0,3.0,10.0,100.0,130.0
4,5,150,35,140.0,150.0,150.0,130.0,3.0,10.0,100.0,140.0
5,6,170,40,150.0,170.0,170.0,130.0,3.0,20.0,400.0,150.0
6,7,160,38,160.0,170.0,170.0,150.0,3.0,10.0,100.0,160.0
7,8,180,45,170.0,180.0,180.0,160.0,3.0,10.0,100.0,170.0

### center=TRUE
    Places result in center row

In [14]:
df["Center_Mean"] = df["Sales"].rolling(
    3,
    center=True
).mean()

df

,Day,Sales,Profit,Rolling_Mean,Rolling_Sum,Rolling_Max,Rolling_Min,Rolling_Count,Rolling_STD,Rolling_Var,Rolling_Mean_2,Center_Mean
0,1,100,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN
1,2,120,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0,120.0
2,3,140,30,120.0,140.0,140.0,100.0,3.0,20.0,400.0,120.0,130.0
3,4,130,28,130.0,140.0,140.0,120.0,3.0,10.0,100.0,130.0,140.0
4,5,150,35,140.0,150.0,150.0,130.0,3.0,10.0,100.0,140.0,150.0
5,6,170,40,150.0,170.0,170.0,130.0,3.0,20.0,400.0,150.0,160.0
6,7,160,38,160.0,170.0,170.0,150.0,3.0,10.0,100.0,160.0,170.0
7,8,180,45,170.0,180.0,180.0,160.0,3.0,10.0,100.0,170.0,NaN

### expanding()
    Used for cumulative calculation

In [16]:
data = {
    "Day": [1,2,3,4,5,6,7,8],
    
    "Sales": [100,120,140,130,150,170,160,180],
    
    "Profit": [20,25,30,28,35,40,38,45]
}

df1 = pd.DataFrame(data)

df1

   Day  Sales  Profit
0    1    100      20
1    2    120      25
2    3    140      30
3    4    130      28
4    5    150      35
5    6    170      40
6    7    160      38
7    8    180      45

### Expanding Sum

In [17]:
df1["Expanding_Sum"] = df1["Sales"].expanding().sum()

df1

   Day  Sales  Profit  Expanding_Sum
0    1    100      20          100.0
1    2    120      25          220.0
2    3    140      30          360.0
3    4    130      28          490.0
4    5    150      35          640.0
5    6    170      40          810.0
6    7    160      38          970.0
7    8    180      45         1150.0

### Expanding Mean

In [18]:
df1["Expanding_Mean"] = df1["Sales"].expanding().mean()

df1

   Day  Sales  Profit  Expanding_Sum  Expanding_Mean
0    1    100      20          100.0      100.000000
1    2    120      25          220.0      110.000000
2    3    140      30          360.0      120.000000
3    4    130      28          490.0      122.500000
4    5    150      35          640.0      128.000000
5    6    170      40          810.0      135.000000
6    7    160      38          970.0      138.571429
7    8    180      45         1150.0      143.750000

### Expanding Max

In [19]:
df1["Expanding_Max"] = df1["Sales"].expanding().max()

df1

   Day  Sales  Profit  Expanding_Sum  Expanding_Mean  Expanding_Max
0    1    100      20          100.0      100.000000          100.0
1    2    120      25          220.0      110.000000          120.0
2    3    140      30          360.0      120.000000          140.0
3    4    130      28          490.0      122.500000          140.0
4    5    150      35          640.0      128.000000          150.0
5    6    170      40          810.0      135.000000          170.0
6    7    160      38          970.0      138.571429          170.0
7    8    180      45         1150.0      143.750000          180.0

### Expanding Min

In [20]:
df1["Expanding_Min"] = df1["Sales"].expanding().min()

df1

,Day,Sales,Profit,Expanding_Sum,Expanding_Mean,Expanding_Max,Expanding_Min
0,1,100,20,100.0,100.000000,100.0,100.0
1,2,120,25,220.0,110.000000,120.0,100.0
2,3,140,30,360.0,120.000000,140.0,100.0
3,4,130,28,490.0,122.500000,140.0,100.0
4,5,150,35,640.0,128.000000,150.0,100.0
5,6,170,40,810.0,135.000000,170.0,100.0
6,7,160,38,970.0,138.571429,170.0,100.0
7,8,180,45,1150.0,143.750000,180.0,100.0

### ewm()
    -Exponentially weighted function
    -Recent values get more importance

In [ ]:
EWM MEAN

In [23]:
data = {
    "Day": [1,2,3,4,5,6,7,8],
    
    "Sales": [100,120,140,130,150,170,160,180],
    
    "Profit": [20,25,30,28,35,40,38,45]
}

df2 = pd.DataFrame(data)

df2

   Day  Sales  Profit
0    1    100      20
1    2    120      25
2    3    140      30
3    4    130      28
4    5    150      35
5    6    170      40
6    7    160      38
7    8    180      45

In [24]:
df2["EWM_Mean"] = df2["Sales"].ewm(span=3).mean()

df2

   Day  Sales  Profit    EWM_Mean
0    1    100      20  100.000000
1    2    120      25  113.333333
2    3    140      30  128.571429
3    4    130      28  129.333333
4    5    150      35  140.000000
5    6    170      40  155.238095
6    7    160      38  157.637795
7    8    180      45  168.862745

### EWM STD

In [26]:
df2["EWM_STD"] = df2["Sales"].ewm(span=3).std()

df2

   Day  Sales  Profit   EWM_Mean    EWM_STD
0    1    100      20        NaN        NaN
1    2    120      25  14.142136  14.142136
2    3    140      30  19.272482  19.272482
3    4    130      28  12.649111  12.649111
4    5    150      35  15.491933  15.491933
5    6    170      40  21.423963  21.423963
6    7    160      38  15.310803  15.310803
7    8    180      45  17.451315  17.451315

### SHIFT()
    Moves values up or down

### SHIFT DOWN

In [28]:
df2["Shift_Down"] = df2["Sales"].shift(1)

df2

   Day  Sales  Profit   EWM_Mean    EWM_STD  Shift_Down
0    1    100      20        NaN        NaN         NaN
1    2    120      25  14.142136  14.142136       100.0
2    3    140      30  19.272482  19.272482       120.0
3    4    130      28  12.649111  12.649111       140.0
4    5    150      35  15.491933  15.491933       130.0
5    6    170      40  21.423963  21.423963       150.0
6    7    160      38  15.310803  15.310803       170.0
7    8    180      45  17.451315  17.451315       160.0

### SHIFT UP

In [29]:
df2["Shift_Up "]= df2["Sales"].shift(-1)

df2

   Day  Sales  Profit   EWM_Mean    EWM_STD  Shift_Down  Shift_Up
0    1    100      20        NaN        NaN         NaN      120.0
1    2    120      25  14.142136  14.142136       100.0      140.0
2    3    140      30  19.272482  19.272482       120.0      130.0
3    4    130      28  12.649111  12.649111       140.0      150.0
4    5    150      35  15.491933  15.491933       130.0      170.0
5    6    170      40  21.423963  21.423963       150.0      160.0
6    7    160      38  15.310803  15.310803       170.0      180.0
7    8    180      45  17.451315  17.451315       160.0        NaN

### Difference Using diff()
    Finds difference between rows

In [30]:
df2["Difference"] = df2["Sales"].diff()

df2

   Day  Sales  Profit   EWM_Mean    EWM_STD  Shift_Down  Shift_Up   Difference
0    1    100      20        NaN        NaN         NaN      120.0         NaN
1    2    120      25  14.142136  14.142136       100.0      140.0        20.0
2    3    140      30  19.272482  19.272482       120.0      130.0        20.0
3    4    130      28  12.649111  12.649111       140.0      150.0       -10.0
4    5    150      35  15.491933  15.491933       130.0      170.0        20.0
5    6    170      40  21.423963  21.423963       150.0      160.0        20.0
6    7    160      38  15.310803  15.310803       170.0      180.0       -10.0
7    8    180      45  17.451315  17.451315       160.0        NaN        20.0

### Percent Change

In [31]:
df2["Percent_Change"] = df2["Sales"].pct_change()

df2

,Day,Sales,Profit,EWM_Mean,EWM_STD,Shift_Down,Shift_Up,Difference,Percent_Change
0,1,100,20,NaN,NaN,NaN,120.0,NaN,NaN
1,2,120,25,14.142136,14.142136,100.0,140.0,20.0,0.200000
2,3,140,30,19.272482,19.272482,120.0,130.0,20.0,0.166667
3,4,130,28,12.649111,12.649111,140.0,150.0,-10.0,-0.071429
4,5,150,35,15.491933,15.491933,130.0,170.0,20.0,0.153846
5,6,170,40,21.423963,21.423963,150.0,160.0,20.0,0.133333
6,7,160,38,15.310803,15.310803,170.0,180.0,-10.0,-0.058824
7,8,180,45,17.451315,17.451315,160.0,NaN,20.0,0.125000

### CUMULATIVE FUNCTIONS

### cumsum()

In [33]:
data = {
    "Day": [1,2,3,4,5,6,7,8],
    
    "Sales": [100,120,140,130,150,170,160,180],
    
    "Profit": [20,25,30,28,35,40,38,45]
}

df3 = pd.DataFrame(data)

df3

   Day  Sales  Profit
0    1    100      20
1    2    120      25
2    3    140      30
3    4    130      28
4    5    150      35
5    6    170      40
6    7    160      38
7    8    180      45

### cumsum()

In [41]:
df3["Cumulative_Sum"] = df3["Sales"].cumsum()

df3

,Day,Sales,Profit,Cumulative_Sum,Cumulative_Max,Cumulative_Min,Cumulative_Product
0,1,100,20,100,100,100,100
1,2,120,25,220,120,100,12000
2,3,140,30,360,140,100,1680000
3,4,130,28,490,140,100,218400000
4,5,150,35,640,150,100,32760000000
5,6,170,40,810,170,100,5569200000000
6,7,160,38,970,170,100,891072000000000
7,8,180,45,1150,180,100,160392960000000000

### cummax()

In [36]:
df3["Cumulative_Max"] = df3["Sales"].cummax()

df3

   Day  Sales  Profit  Cumulative_Sum  Cumulative_Max
0    1    100      20             100             100
1    2    120      25             220             120
2    3    140      30             360             140
3    4    130      28             490             140
4    5    150      35             640             150
5    6    170      40             810             170
6    7    160      38             970             170
7    8    180      45            1150             180

### cummin()

In [37]:
df3["Cumulative_Min"] = df3["Sales"].cummin()

df3

   Day  Sales  Profit  Cumulative_Sum  Cumulative_Max  Cumulative_Min
0    1    100      20             100             100             100
1    2    120      25             220             120             100
2    3    140      30             360             140             100
3    4    130      28             490             140             100
4    5    150      35             640             150             100
5    6    170      40             810             170             100
6    7    160      38             970             170             100
7    8    180      45            1150             180             100

### cumprod()

In [42]:
df3["Cumulative_Product"] = df3["Sales"].cumprod()

df3

,Day,Sales,Profit,Cumulative_Sum,Cumulative_Max,Cumulative_Min,Cumulative_Product
0,1,100,20,100,100,100,100
1,2,120,25,220,120,100,12000
2,3,140,30,360,140,100,1680000
3,4,130,28,490,140,100,218400000
4,5,150,35,640,150,100,32760000000
5,6,170,40,810,170,100,5569200000000
6,7,160,38,970,170,100,891072000000000
7,8,180,45,1150,180,100,160392960000000000

### GROUPBY + WINDOW FUNCTION

In [43]:
data2 = {
    "Department": ["IT","IT","HR","HR","Finance","Finance"],
    
    "Salary": [50000,60000,45000,52000,70000,65000]
}

df2 = pd.DataFrame(data2)

df2

  Department  Salary
0         IT   50000
1         IT   60000
2         HR   45000
3         HR   52000
4    Finance   70000
5    Finance   65000

### Group Rolling Mean

In [44]:
df2["Rolling_Mean"] = df2.groupby(
    "Department"
)["Salary"].rolling(2).mean().reset_index(level=0, drop=True)

df2

  Department  Salary  Rolling_Mean
0         IT   50000           NaN
1         IT   60000       55000.0
2         HR   45000           NaN
3         HR   52000       48500.0
4    Finance   70000           NaN
5    Finance   65000       67500.0