### DATA CLEANING

In [2]:
import numpy as np
import pandas as pd

In [6]:
dfm=pd.read_csv(r"C:\Users\SANDESH\Downloads\dirty_rows_03.csv")

In [79]:
df=dfm.copy()
df

,Customer_ID,Customer_Name,City,Email,Phone,Purchase_Amount,Customer_Segment,Join_Date
0,10000,Akshay Kumar,mumbai,user@gmail.com,NaN,2500,retial,15/01/2024
1,10001,Akshay Kumar,mumbai,user@gmail.com,98765-43210,1000,Retail,2024-01-15
2,10002,rahul sharma,Pune,user@gmail.com,9123456780,five thousand,SMB,NaN
3,10003,rahul sharma,Belgaum,test@mail.com,9876543210,2500,corporate,Jan 15 2024
4,10004,Rahul Sharma,MUMBAI,USER@GMAIL.COM,NaN,1000,Retail,NaN
...,...,...,...,...,...,...,...,...
995,10995,pooja patil,Bangalore,test@mail.com,NaN,5000,Corporate,2024-01-15
996,10996,pooja patil,Bangalore,USER@GMAIL.COM,9876543210,2500,SMB,Jan 15 2024
997,10997,Rahul Sharma,Belgaum,NaN,NaN,2500,Retail,15/01/2024
998,10998,rahul sharma,belgaum,USER@GMAIL.COM,9123456780,5000,SMB,2024-01-15
999,10999,Pooja Patil,Belgaum,user@gmail.com,9876543210,2500,Retail,NaN

In [25]:
df.shape

(1000, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       1000 non-null   int64
 1   Customer_Name     1000 non-null   object
 2   City              1000 non-null   object
 3   Email             742 non-null    object
 4   Phone             758 non-null    object
 5   Purchase_Amount   823 non-null    object
 6   Customer_Segment  1000 non-null   object
 7   Join_Date         742 non-null    object
dtypes: int64(1), object(7)
memory usage: 62.6+ KB

In [9]:
df.describe().round()

       Customer_ID
count       1000.0
mean       10499.0
std          289.0
min        10000.0
25%        10250.0
50%        10500.0
75%        10749.0
max        10999.0

### Count Null Values In Percentage

In [11]:
df.isnull().sum()/len(df)*100

Customer_ID          0.0
Customer_Name        0.0
City                 0.0
Email               25.8
Phone               24.2
Purchase_Amount     17.7
Customer_Segment     0.0
Join_Date           25.8
dtype: float64

#### Checking Duplicates

In [18]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.duplicated().any()

np.False_

In [19]:
df[df.duplicated()] # Gives Us Duplicate Present Data

Empty DataFrame
Columns: [Customer_ID, Customer_Name, City, Email, Phone, Purchase_Amount, Customer_Segment, Join_Date]
Index: []

### Checking For Primary key
    i.e.Customer_ID

In [21]:
df['Customer_ID'].value_counts().head(10)

Customer_ID
10479    2
10239    2
10359    2
10119    2
10599    2
10719    2
10839    2
10959    2
10004    1
10005    1
Name: count, dtype: int64

### PK Duplicates
    Customer_ID is the business key, duplicate Customer_IDs with different customer names indicate a data integrity issue.

In [26]:
df[df['Customer_ID'] == 10599]

,Customer_ID,Customer_Name,City,Email,Phone,Purchase_Amount,Customer_Segment,Join_Date
599,10599,Akshay Kumar,belgaum,NaN,9123456780,5000,Corporate,2024-01-15
600,10599,Pooja Patil,Bengaluru,NaN,NaN,5000,Retail,2024-01-15

In [28]:
for col in df.columns:
    if df[col].nunique()<20:
        print(df[col].value_counts())
        print('-'*30)

Customer_Name
pooja patil      171
rahul sharma     170
Rahul Sharma     166
Akshay Kumar     165
Rahul  Sharma    165
Pooja Patil      163
Name: count, dtype: int64
------------------------------
City
belgaum      129
Bengaluru    117
mumbai       116
 MUMBAI      116
Bangalore    112
Mumbai       106
Belgaum      105
Pune         103
pune          96
Name: count, dtype: int64
------------------------------
Email
USER@GMAIL.COM     255
user@gmail.com     244
 test@mail.com     243
Name: count, dtype: int64
------------------------------
Phone
98765-43210    258
9123456780     258
9876543210     242
Name: count, dtype: int64
------------------------------
Purchase_Amount
2500             170
five thousand    168
5000             165
1000             162
5000             158
Name: count, dtype: int64
------------------------------
Customer_Segment
SMB          213
Corporate    210
Retail       197
corporate    193
retial       187
Name: count, dtype: int64
------------------------------
Join_Date
Jan 15 2024    268
2024-01-15     243
15/01/2024     231
Name: count, dtype: int64
------------------------------

### Handling Missing Data

#### Filling NAN Values

##### Purchase_Amount Column

In [99]:
df["Purchase_Amount"] = df["Purchase_Amount"].fillna(
    df["Purchase_Amount"].median()
)

In [100]:
df["Purchase_Amount"].unique()

array([2500., 1000., 5000.])

##### Email Column

In [107]:
df["Email"] = df["Email"].fillna("Not Available")

In [111]:
df["Email"].unique()

array(['user@gmail.com', 'test@mail.com', 'not available'], dtype=object)

#### Join_Date Column

In [80]:
df["Join_Date"].unique()

array(['15/01/2024', '2024-01-15', nan, 'Jan 15 2024'], dtype=object)

##### Fill With Most frequent Date

In [115]:
df["Join_Date"] = df["Join_Date"].fillna(
    df["Join_Date"].mode()[0]
)

In [127]:
df["Join_Date"].unique()

<DatetimeArray>
['2024-01-15 00:00:00']
Length: 1, dtype: datetime64[ns]

#### Phone Column

In [117]:
df["Phone"].unique()

array([nan, '98765-43210', '9123456780', '9876543210'], dtype=object)

In [123]:
df["Phone"] = df["Phone"].replace(
    "98765-43210","9876543210"
)

In [125]:
df["Phone"] = df["Phone"].fillna("0")

In [126]:
df["Phone"].unique()

array(['0', '9876543210', '9123456780'], dtype=object)

### Fixing Inconsistent Formating

#### Convert Email Lowercase

In [106]:
df["Email"].unique()

array(['user@gmail.com', 'test@mail.com', 'USER@GMAIL.COM',
       'Not Available'], dtype=object)

In [110]:
df["Email"] = df["Email"].str.lower()

#### Removing Spaces

In [130]:
df["Purchase_Amount"] = df["Purchase_Amount"].astype(str).str.strip()

#### Replacing Values

In [132]:
df["Purchase_Amount"] = df["Purchase_Amount"].replace(
    "five thousand","5000"
)

#### Checking Unique Values

In [133]:
df["Purchase_Amount"].unique()

array(['2500', '1000', '5000'], dtype=object)

In [113]:
df[df.duplicated(subset=["Email"], keep=False)]

df.head(10)

,Customer_ID,Customer_Name,City,Email,Phone,Purchase_Amount,Customer_Segment,Join_Date
0,10000,Akshay Kumar,mumbai,user@gmail.com,NaN,2500,retial,2024-01-15
1,10001,Akshay Kumar,mumbai,user@gmail.com,98765-43210,1000,Retail,NaT
2,10002,rahul sharma,Pune,user@gmail.com,9123456780,5000,SMB,NaT
3,10003,rahul sharma,Belgaum,test@mail.com,9876543210,2500,corporate,NaT
4,10004,Rahul Sharma,MUMBAI,user@gmail.com,NaN,1000,Retail,NaT
5,10005,Rahul Sharma,Bangalore,test@mail.com,NaN,1000,corporate,NaT
6,10006,Pooja Patil,mumbai,test@mail.com,NaN,5000,retial,NaT
7,10007,Rahul Sharma,Pune,test@mail.com,9876543210,2500,Retail,NaT
8,10008,Rahul Sharma,Belgaum,test@mail.com,9123456780,5000,Corporate,2024-01-15
9,10009,Akshay Kumar,pune,user@gmail.com,9123456780,5000,retial,2024-01-15

In [141]:
df["Customer_Name"] = df["Customer_Name"].str.title()
df.head(5)

,Customer_ID,Customer_Name,City,Email,Phone,Purchase_Amount,Customer_Segment,Join_Date
0,10000,Akshay Kumar,mumbai,user@gmail.com,0,2500,retial,2024-01-15
1,10001,Akshay Kumar,mumbai,user@gmail.com,9876543210,1000,Retail,2024-01-15
2,10002,Rahul Sharma,Pune,user@gmail.com,9123456780,5000,SMB,2024-01-15
3,10003,Rahul Sharma,Belgaum,test@mail.com,9876543210,2500,corporate,2024-01-15
4,10004,Rahul Sharma,MUMBAI,user@gmail.com,0,1000,Retail,2024-01-15

In [142]:
df["City"] = df["City"].str.title()
df.head(5)

,Customer_ID,Customer_Name,City,Email,Phone,Purchase_Amount,Customer_Segment,Join_Date
0,10000,Akshay Kumar,Mumbai,user@gmail.com,0,2500,retial,2024-01-15
1,10001,Akshay Kumar,Mumbai,user@gmail.com,9876543210,1000,Retail,2024-01-15
2,10002,Rahul Sharma,Pune,user@gmail.com,9123456780,5000,SMB,2024-01-15
3,10003,Rahul Sharma,Belgaum,test@mail.com,9876543210,2500,corporate,2024-01-15
4,10004,Rahul Sharma,Mumbai,user@gmail.com,0,1000,Retail,2024-01-15

In [143]:
df["Customer_Segment"] = df["Customer_Segment"].str.title()
df.head(5)

,Customer_ID,Customer_Name,City,Email,Phone,Purchase_Amount,Customer_Segment,Join_Date
0,10000,Akshay Kumar,Mumbai,user@gmail.com,0,2500,Retial,2024-01-15
1,10001,Akshay Kumar,Mumbai,user@gmail.com,9876543210,1000,Retail,2024-01-15
2,10002,Rahul Sharma,Pune,user@gmail.com,9123456780,5000,Smb,2024-01-15
3,10003,Rahul Sharma,Belgaum,test@mail.com,9876543210,2500,Corporate,2024-01-15
4,10004,Rahul Sharma,Mumbai,user@gmail.com,0,1000,Retail,2024-01-15

In [147]:
df.columns = df.columns.str.strip()

In [148]:
df = df.apply(
                lambda x: x.str.strip() if x.dtype == "object" else x
            )

#### Handling Duplicates

In [152]:
df[df.duplicated()].shape

(0, 8)

In [153]:
df['Customer_ID'].value_counts().head(10)

Customer_ID
10479    2
10239    2
10359    2
10119    2
10599    2
10719    2
10839    2
10959    2
10004    1
10005    1
Name: count, dtype: int64

In [154]:
df[df['Customer_ID'] == 10599]

,Customer_ID,Customer_Name,City,Email,Phone,Purchase_Amount,Customer_Segment,Join_Date
599,10599,Akshay Kumar,Belgaum,not available,9123456780,5000,Corporate,2024-01-15
600,10599,Pooja Patil,Bengaluru,not available,0,5000,Retail,2024-01-15

In [158]:
df.drop_duplicates(subset=['Customer_ID'],keep='first',inplace=True)

In [165]:
df.shape

(992, 8)

#### Duplicates Email

In [170]:
df['Email'].duplicated().sum()

np.int64(989)

### Converting Data Types

In [160]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'City', 'Email', 'Phone',
       'Purchase_Amount', 'Customer_Segment', 'Join_Date'],
      dtype='object')

In [134]:
df["Purchase_Amount"] = df["Purchase_Amount"].astype("int64")

In [135]:
df["Purchase_Amount"].dtype

dtype('int64')

In [163]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)                                    

          # errors="coerce" = Invalid or non-convertible values are automatically converted to NaN instead of raising an error

In [137]:
df["Join_Date"].dtype # dtype('<M8[ns]') = short/internal representation of datetime64[ns] datatype

dtype('<M8[ns]')

In [150]:
df.dtypes

Customer_ID                  int64
Customer_Name               object
City                        object
Email                       object
Phone                       object
Purchase_Amount              int64
Customer_Segment            object
Join_Date           datetime64[ns]
dtype: object

In [164]:
df.isnull().sum()

Customer_ID         0
Customer_Name       0
City                0
Email               0
Phone               0
Purchase_Amount     0
Customer_Segment    0
Join_Date           0
dtype: int64

In [171]:
df.to_save("Cleaned_03.csv",index=False)

AttributeError: 'DataFrame' object has no attribute 'to_save'