In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)

2.2.3

## PANDAS PIVOT TABLE
    It is used to summarize the data

In [2]:
data = {
    "Name": ["Aman", "Aman", "Rahul", "Rahul",
             "Sneha", "Sneha", "Priya", "Priya"],

    "Department": ["IT", "HR", "IT", "Finance",
                   "HR", "Finance", "IT", "Finance"],

    "City": ["Pune", "Mumbai", "Pune", "Delhi",
             "Mumbai", "Delhi", "Pune", "Delhi"],

    "Salary": [50000, 45000, 60000, 70000,
               48000, 65000, 72000, 80000],

    "Bonus": [5000, 4000, 6000, 7000,
              4500, 6500, 7200, 8500]
}

df = pd.DataFrame(data)

df

    Name Department    City  Salary  Bonus
0   Aman         IT    Pune   50000   5000
1   Aman         HR  Mumbai   45000   4000
2  Rahul         IT    Pune   60000   6000
3  Rahul    Finance   Delhi   70000   7000
4  Sneha         HR  Mumbai   48000   4500
5  Sneha    Finance   Delhi   65000   6500
6  Priya         IT    Pune   72000   7200
7  Priya    Finance   Delhi   80000   8500

### Basic pivot table

In [3]:
pivot1 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
)

pivot1

                  Salary
Department
Finance     71666.666667
HR          46500.000000
IT          60666.666667

### Multiple Aggfunc

In [4]:
pivot2 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc=["sum", "mean", "max", "min"]
)

pivot2

               sum          mean    max    min
            Salary        Salary Salary Salary
Department
Finance     215000  71666.666667  80000  65000
HR           93000  46500.000000  48000  45000
IT          182000  60666.666667  72000  50000

### Rows + Columns

In [5]:
pivot3 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="sum"
)

pivot3

City           Delhi   Mumbai      Pune
Department
Finance     215000.0      NaN       NaN
HR               NaN  93000.0       NaN
IT               NaN      NaN  182000.0

### Fill_value
    Fills missing values

In [6]:
pivot4 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="sum",
    fill_value=0
)

pivot4

City         Delhi  Mumbai    Pune
Department
Finance     215000       0       0
HR               0   93000       0
IT               0       0  182000

### margins=
    Adds total row/columns

In [7]:
pivot5 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="sum",
    margins=True
)

pivot5

City           Delhi   Mumbai      Pune     All
Department
Finance     215000.0      NaN       NaN  215000
HR               NaN  93000.0       NaN   93000
IT               NaN      NaN  182000.0  182000
All         215000.0  93000.0  182000.0  490000

### Multiple Values

In [8]:
pivot6 = pd.pivot_table(
    df,
    values=["Salary", "Bonus"],
    index="Department",
    aggfunc="sum"
)

pivot6

            Bonus  Salary
Department
Finance     22000  215000
HR           8500   93000
IT          18200  182000

### Multiple Index

In [9]:
pivot7 = pd.pivot_table(
    df,
    values="Salary",
    index=["Department", "City"],
    aggfunc="mean"
)

pivot7

                         Salary
Department City
Finance    Delhi   71666.666667
HR         Mumbai  46500.000000
IT         Pune    60666.666667

### Multiple Column

In [10]:
pivot8 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns=["City", "Name"],
    aggfunc="sum",
    fill_value=0
)

pivot8

City        Delhi               Mumbai          Pune
Name        Priya  Rahul  Sneha   Aman  Sneha   Aman  Priya  Rahul
Department
Finance     80000  70000  65000      0      0      0      0      0
HR              0      0      0  45000  48000      0      0      0
IT              0      0      0      0      0  50000  72000  60000

## Crosstab()
    -To compare the categories
    -Create Frequency Table

In [11]:
cross1 = pd.crosstab(
    df["Department"],
    df["City"]
)

cross1

City        Delhi  Mumbai  Pune
Department
Finance         3       0     0
HR              0       2     0
IT              0       0     3

### Crosstab with values

In [12]:
cross2 = pd.crosstab(
    df["Department"],
    df["City"],
    values=df["Salary"],
    aggfunc="sum"
)

cross2

City           Delhi   Mumbai      Pune
Department
Finance     215000.0      NaN       NaN
HR               NaN  93000.0       NaN
IT               NaN      NaN  182000.0

### Crosstab With margins

In [13]:
cross3 = pd.crosstab(
    df["Department"],
    df["City"],
    margins=True
)

cross3

City        Delhi  Mumbai  Pune  All
Department
Finance         3       0     0    3
HR              0       2     0    2
IT              0       0     3    3
All             3       2     3    8

### Normalize=True
    Shows percentage or proportion

In [17]:
cross3 = pd.crosstab(
    df["Department"],
    df["City"],
    margins=True
)

cross3

City        Delhi  Mumbai  Pune  All
Department
Finance         3       0     0    3
HR              0       2     0    2
IT              0       0     3    3
All             3       2     3    8

### Row-Wise Percentage

In [16]:
cross4 = pd.crosstab(
    df["Department"],
    df["City"],
    normalize="index"
)

cross4

City        Delhi  Mumbai  Pune
Department
Finance       1.0     0.0   0.0
HR            0.0     1.0   0.0
IT            0.0     0.0   1.0

### Column-Wise Percentage

In [18]:
cross5 = pd.crosstab(
    df["Department"],
    df["City"],
    normalize="columns"
)

cross5

City        Delhi  Mumbai  Pune
Department
Finance       1.0     0.0   0.0
HR            0.0     1.0   0.0
IT            0.0     0.0   1.0

### Complete Table Percentage

In [19]:
cross6 = pd.crosstab(
    df["Department"],
    df["City"],
    normalize=True
)

cross6

City        Delhi  Mumbai   Pune
Department
Finance     0.375    0.00  0.000
HR          0.000    0.25  0.000
IT          0.000    0.00  0.375

### fillna()

In [20]:
pivot9 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="sum"
)

pivot9.fillna(0)

City           Delhi   Mumbai      Pune
Department
Finance     215000.0      0.0       0.0
HR               0.0  93000.0       0.0
IT               0.0      0.0  182000.0

### DROPNA

In [21]:
pivot10 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="sum",
    dropna=True
)

pivot10

City           Delhi   Mumbai      Pune
Department
Finance     215000.0      NaN       NaN
HR               NaN  93000.0       NaN
IT               NaN      NaN  182000.0

### Count using pivot table

In [22]:
pivot12 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="count"
)

pivot12

            Salary
Department
Finance          3
HR               2
IT               3

### Unique Value Count

In [23]:
pivot13 = pd.pivot_table(
    df,
    values="City",
    index="Department",
    aggfunc="nunique"
)

pivot13

            City
Department
Finance        1
HR             1
IT             1

### Sort Values

In [24]:
pivot14 = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="sum"
)

pivot14.sort_values(by="Salary", ascending=False)

            Salary
Department
Finance     215000
IT          182000
HR           93000