## Pandas Concatenation
    To join two or more DataFrames.

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    'Name':['Ram','Sham'],
    'Marks':[85,90]
})


print(df1) # 1st DataFrame

   Name  Marks
0   Ram     85
1  Sham     90

In [4]:
df2 = pd.DataFrame({
    'Name':['Amit','Riya'],
    'Marks':[70,95]
})

print(df2) # 2nd Dataframe

   Name  Marks
0  Amit     70
1  Riya     95

### concat()
    Combine Dataframes

In [5]:
result = pd.concat([df1,df2])

print(result)

   Name  Marks
0   Ram     85
1  Sham     90
0  Amit     70
1  Riya     95

### ignore_index = True
    New contunious Index Formed

In [6]:
result = pd.concat(
    [df1,df2],
    ignore_index=True
)

print(result)

   Name  Marks
0   Ram     85
1  Sham     90
2  Amit     70
3  Riya     95

### Column Wise Concat

In [7]:
df3 = pd.DataFrame({
    'City':['Delhi','Mumbai']
})

print(
    pd.concat(
        [df1,df3],
        axis=1
    )
)

   Name  Marks    City
0   Ram     85   Delhi
1  Sham     90  Mumbai

### Keys
    Adds labels to dataframes

In [8]:
print(
    pd.concat(
        [df1,df2],
        keys=['Class1','Class2']
    )
)

          Name  Marks
Class1 0   Ram     85
       1  Sham     90
Class2 0  Amit     70
       1  Riya     95

## Pandas Apply Function
    Apply custom or built in functions.

In [9]:
data = {
    'Name':['Ram','Sham','Amit'],
    'Marks':[85,90,70]
}

df = pd.DataFrame(data)

print(df)

   Name  Marks
0   Ram     85
1  Sham     90
2  Amit     70

### apply()
    Applies function on data

In [10]:
df['Marks'] = df['Marks'].apply(
    lambda x: x + 5
)

print(df)

   Name  Marks
0   Ram     90
1  Sham     95
2  Amit     75

### apply on multiple column

In [13]:
df['Total'] = df.apply(
    lambda row: row['Marks'] + 10,
    axis=1
)

print(df)

   Name  Marks Grade  Total
0   Ram     90     A    100
1  Sham     95     A    105
2  Amit     75     B     85

### lambda Function
    small anonymous function
    Ex:-lambda x:x * 5 # Multiply by 5 to each data

### Custom Function

In [12]:
def grade(x):

    if x >= 90:
        return 'A'

    else:
        return 'B'

df['Grade'] = df['Marks'].apply(grade)

print(df)

   Name  Marks Grade
0   Ram     90     A
1  Sham     95     A
2  Amit     75     B

### map()
    Maps Values

In [14]:
df['Name'] = df['Name'].map(
    {
        'Ram':'RAM',
        'Sham':'SHAM',
        'Amit':'AMIT'
    }
)

print(df)

   Name  Marks Grade  Total
0   RAM     90     A    100
1  SHAM     95     A    105
2  AMIT     75     B     85

# QUISTIONS TASK
### Student Perforemence

In [17]:
df1 = pd.DataFrame({
    "Name": ["Ram", "Sam"],
    "Python": [78, 90]
})

df2 = pd.DataFrame({
    "Name": ["Amit", "Neha"],
    "Python": [67, 95]
})

df = pd.concat([df1, df2],ignore_index=True)

def performance(x):
    if x >= 80:
        return "Excellent"
    else:
        return "Average"

df["Performance"] = df["Python"].apply(performance)

df

   Name  Python Performance
0   Ram      78     Average
1   Sam      90   Excellent
2  Amit      67     Average
3  Neha      95   Excellent

### Employee Bonus

In [19]:
df = pd.DataFrame({
    "Employee": ["A", "B", "C"],
    "Salary": [25000, 70000, 50000],
    "Experience": [2, 8, 5]
})

def bonus(exp, salary):
    if exp > 5:
        return salary * 0.20
    else:
        return salary * 0.10

df["Bonus"] = df.apply(
    lambda x: bonus(x["Experience"], x["Salary"]),
    axis=1
)

print(df)

  Employee  Salary  Experience    Bonus
0        A   25000           2   2500.0
1        B   70000           8  14000.0
2        C   50000           5   5000.0

### Product Category

In [24]:
df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Mobile"],
    "Price": [50000, 500, 20000],
    "Quantity": [2, 5, 1]
})

df["Total"] = df["Price"] * df["Quantity"]

def category(x):
    if x > 50000:
        return "Premium"
    else:
        return "Normal"

df["Category"] = df["Total"].apply(category)

print(df)

  Product  Price  Quantity   Total Category
0  Laptop  50000         2  100000  Premium
1   Mouse    500         5    2500   Normal
2  Mobile  20000         1   20000   Normal

### map()
    Element wise function apply on full dataframe

In [27]:
df.map(lambda x: x * 2)

        Product   Price  Quantity   Total        Category
0  LaptopLaptop  100000         4  200000  PremiumPremium
1    MouseMouse    1000        10    5000    NormalNormal
2  MobileMobile   40000         2   40000    NormalNormal