## Mini Project

In [4]:
import numpy as np

import pandas as pd

print(np.__version__)
print(pd.__version__)

2.1.3
2.2.3

### Creation Of Data

In [5]:
data = {
    'Date': [
        '2025-01-01','2025-01-02','2025-01-03',
        '2025-01-04','2025-01-05','2025-01-06',
        '2025-01-07','2025-01-08','2025-01-09',
        '2025-01-10'
    ],

    'Product': [
        'Laptop','Mouse','Laptop',
        'Keyboard','Mouse','Monitor',
        'Laptop','Keyboard','Mouse',
        'Monitor'
    ],

    'Sales': [
        50000,1500,52000,None,1700,
        12000,55000,3000,None,
        14000
    ],

    'City': [
        'Pune','Mumbai','Delhi',
        'Bangalore','Chennai','Hyderabad',
        'Pune','Mumbai','Delhi',
        'Chennai'
    ],

    'Quantity': [
        2,5,1,3,4,
        2,1,2,6,
        1
    ],

    'Profit': [
        5000,200,6000,None,250,
        1500,7000,400,None,
        1800
    ]
}

df = pd.DataFrame(data)

### To SAVE CSV

In [12]:
df.to_csv('Mini.csv',index=False) # Without Index Saved

### Read From CSV

In [13]:
df=pd.read_csv("Mini.csv")
df

         Date   Product    Sales       City  Quantity  Profit
0  2025-01-01    Laptop  50000.0       Pune         2  5000.0
1  2025-01-02     Mouse   1500.0     Mumbai         5   200.0
2  2025-01-03    Laptop  52000.0      Delhi         1  6000.0
3  2025-01-04  Keyboard      NaN  Bangalore         3     NaN
4  2025-01-05     Mouse   1700.0    Chennai         4   250.0
5  2025-01-06   Monitor  12000.0  Hyderabad         2  1500.0
6  2025-01-07    Laptop  55000.0       Pune         1  7000.0
7  2025-01-08  Keyboard   3000.0     Mumbai         2   400.0
8  2025-01-09     Mouse      NaN      Delhi         6     NaN
9  2025-01-10   Monitor  14000.0    Chennai         1  1800.0

### Understanding Data

In [15]:
df.head() # First 5 Rows

         Date   Product    Sales       City  Quantity  Profit
0  2025-01-01    Laptop  50000.0       Pune         2  5000.0
1  2025-01-02     Mouse   1500.0     Mumbai         5   200.0
2  2025-01-03    Laptop  52000.0      Delhi         1  6000.0
3  2025-01-04  Keyboard      NaN  Bangalore         3     NaN
4  2025-01-05     Mouse   1700.0    Chennai         4   250.0

In [16]:
df.tail() # Last 5 Rows

         Date   Product    Sales       City  Quantity  Profit
5  2025-01-06   Monitor  12000.0  Hyderabad         2  1500.0
6  2025-01-07    Laptop  55000.0       Pune         1  7000.0
7  2025-01-08  Keyboard   3000.0     Mumbai         2   400.0
8  2025-01-09     Mouse      NaN      Delhi         6     NaN
9  2025-01-10   Monitor  14000.0    Chennai         1  1800.0

### Shape

In [33]:
print(df.shape)

(10, 7)

### Column Names

In [36]:
print(df.columns)

Index(['Date', 'Product', 'Sales', 'City', 'Quantity', 'Profit', 'Category'], dtype='object')

### Datatypes

In [37]:
print(df.dtypes)

Date        datetime64[ns]
Product             object
Sales              float64
City                object
Quantity             int64
Profit             float64
Category          category
dtype: object

In [18]:
df.describe()

              Sales   Quantity       Profit
count      8.000000  10.000000     8.000000
mean   23650.000000   2.700000  2768.750000
std    24226.785648   1.766981  2788.360694
min     1500.000000   1.000000   200.000000
25%     2675.000000   1.250000   362.500000
50%    13000.000000   2.000000  1650.000000
75%    50500.000000   3.750000  5250.000000
max    55000.000000   6.000000  7000.000000

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      10 non-null     object
 1   Product   10 non-null     object
 2   Sales     8 non-null      float64
 3   City      10 non-null     object
 4   Quantity  10 non-null     int64
 5   Profit    8 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 612.0+ bytes

### Checks Duplicates

In [63]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

### Convert Date Column

In [20]:
df['Date'] = pd.to_datetime(df['Date'])
df

        Date   Product    Sales       City  Quantity  Profit
0 2025-01-01    Laptop  50000.0       Pune         2  5000.0
1 2025-01-02     Mouse   1500.0     Mumbai         5   200.0
2 2025-01-03    Laptop  52000.0      Delhi         1  6000.0
3 2025-01-04  Keyboard      NaN  Bangalore         3     NaN
4 2025-01-05     Mouse   1700.0    Chennai         4   250.0
5 2025-01-06   Monitor  12000.0  Hyderabad         2  1500.0
6 2025-01-07    Laptop  55000.0       Pune         1  7000.0
7 2025-01-08  Keyboard   3000.0     Mumbai         2   400.0
8 2025-01-09     Mouse      NaN      Delhi         6     NaN
9 2025-01-10   Monitor  14000.0    Chennai         1  1800.0

### Check Missing Values

In [21]:
df.isnull().sum()

Date        0
Product     0
Sales       2
City        0
Quantity    0
Profit      2
dtype: int64

### Fill Missing 
    Filled With Mean

In [22]:
df['Sales'] = df['Sales'].fillna(
    df['Sales'].mean()
)

df['Profit'] = df['Profit'].fillna(
    df['Profit'].mean()
)

df

        Date   Product    Sales       City  Quantity   Profit
0 2025-01-01    Laptop  50000.0       Pune         2  5000.00
1 2025-01-02     Mouse   1500.0     Mumbai         5   200.00
2 2025-01-03    Laptop  52000.0      Delhi         1  6000.00
3 2025-01-04  Keyboard  23650.0  Bangalore         3  2768.75
4 2025-01-05     Mouse   1700.0    Chennai         4   250.00
5 2025-01-06   Monitor  12000.0  Hyderabad         2  1500.00
6 2025-01-07    Laptop  55000.0       Pune         1  7000.00
7 2025-01-08  Keyboard   3000.0     Mumbai         2   400.00
8 2025-01-09     Mouse  23650.0      Delhi         6  2768.75
9 2025-01-10   Monitor  14000.0    Chennai         1  1800.00

### Total Sales

In [23]:
Total=df['Sales'].sum()
print(Total)

236500.0

### Average Sales

In [38]:
print(df['Sales'].mean())

23650.0

### Product-Wise Sales

In [24]:
df.groupby('Product')['Sales'].sum()

Product
Keyboard     26650.0
Laptop      157000.0
Monitor      26000.0
Mouse        26850.0
Name: Sales, dtype: float64

### City-Wise Sales

In [39]:
print(df.groupby('City')['Sales'].sum())

City
Bangalore     23650.0
Chennai       15700.0
Delhi         75650.0
Hyderabad     12000.0
Mumbai         4500.0
Pune         105000.0
Name: Sales, dtype: float64

#### Highest Selling Product

In [25]:
df.groupby('Product')['Sales'].sum().idxmax()

'Laptop'

### Lowest Selling Product

In [26]:
df.groupby('Product')['Sales'].sum().idxmin()

'Monitor'

### Daily Sales Trend

In [27]:
df.groupby('Date')['Sales'].sum()

Date
2025-01-01    50000.0
2025-01-02     1500.0
2025-01-03    52000.0
2025-01-04    23650.0
2025-01-05     1700.0
2025-01-06    12000.0
2025-01-07    55000.0
2025-01-08     3000.0
2025-01-09    23650.0
2025-01-10    14000.0
Name: Sales, dtype: float64

### Sales Category

In [28]:
df['Category'] = pd.cut(
    df['Sales'],
    bins=[0,5000,50000,100000],
    labels=['Low','Medium','High']
)

df

        Date   Product    Sales       City  Quantity   Profit Category
0 2025-01-01    Laptop  50000.0       Pune         2  5000.00   Medium
1 2025-01-02     Mouse   1500.0     Mumbai         5   200.00      Low
2 2025-01-03    Laptop  52000.0      Delhi         1  6000.00     High
3 2025-01-04  Keyboard  23650.0  Bangalore         3  2768.75   Medium
4 2025-01-05     Mouse   1700.0    Chennai         4   250.00      Low
5 2025-01-06   Monitor  12000.0  Hyderabad         2  1500.00   Medium
6 2025-01-07    Laptop  55000.0       Pune         1  7000.00     High
7 2025-01-08  Keyboard   3000.0     Mumbai         2   400.00      Low
8 2025-01-09     Mouse  23650.0      Delhi         6  2768.75   Medium
9 2025-01-10   Monitor  14000.0    Chennai         1  1800.00   Medium

### Highest Sales

In [29]:
print(df['Sales'].max())

55000.0

### Lowest Sales

In [30]:
print(df['Sales'].min())

1500.0

### Filter Data

In [31]:
print(df[df['Sales'] > 10000])

        Date   Product    Sales       City  Quantity   Profit Category
0 2025-01-01    Laptop  50000.0       Pune         2  5000.00   Medium
2 2025-01-03    Laptop  52000.0      Delhi         1  6000.00     High
3 2025-01-04  Keyboard  23650.0  Bangalore         3  2768.75   Medium
5 2025-01-06   Monitor  12000.0  Hyderabad         2  1500.00   Medium
6 2025-01-07    Laptop  55000.0       Pune         1  7000.00     High
8 2025-01-09     Mouse  23650.0      Delhi         6  2768.75   Medium
9 2025-01-10   Monitor  14000.0    Chennai         1  1800.00   Medium

### Multiple Conditions

In [41]:
print(df[(df['Sales'] > 10000) & (df['City']=='Pune')])

        Date Product    Sales  City  Quantity  Profit Category
0 2025-01-01  Laptop  50000.0  Pune         2  5000.0   Medium
6 2025-01-07  Laptop  55000.0  Pune         1  7000.0     High

### Unique Product

In [42]:
print(df['Product'].unique())

['Laptop' 'Mouse' 'Keyboard' 'Monitor']

### Value Counts

In [43]:
print(df['Product'].value_counts())

Product
Laptop      3
Mouse       3
Keyboard    2
Monitor     2
Name: count, dtype: int64

### Sort values

In [32]:
print(df.sort_values(by='Sales'))

        Date   Product    Sales       City  Quantity   Profit Category
1 2025-01-02     Mouse   1500.0     Mumbai         5   200.00      Low
4 2025-01-05     Mouse   1700.0    Chennai         4   250.00      Low
7 2025-01-08  Keyboard   3000.0     Mumbai         2   400.00      Low
5 2025-01-06   Monitor  12000.0  Hyderabad         2  1500.00   Medium
9 2025-01-10   Monitor  14000.0    Chennai         1  1800.00   Medium
3 2025-01-04  Keyboard  23650.0  Bangalore         3  2768.75   Medium
8 2025-01-09     Mouse  23650.0      Delhi         6  2768.75   Medium
0 2025-01-01    Laptop  50000.0       Pune         2  5000.00   Medium
2 2025-01-03    Laptop  52000.0      Delhi         1  6000.00     High
6 2025-01-07    Laptop  55000.0       Pune         1  7000.00     High

### IN Descending Order

In [40]:
print(df.sort_values(by='Sales',ascending=False))

        Date   Product    Sales       City  Quantity   Profit Category
6 2025-01-07    Laptop  55000.0       Pune         1  7000.00     High
2 2025-01-03    Laptop  52000.0      Delhi         1  6000.00     High
0 2025-01-01    Laptop  50000.0       Pune         2  5000.00   Medium
8 2025-01-09     Mouse  23650.0      Delhi         6  2768.75   Medium
3 2025-01-04  Keyboard  23650.0  Bangalore         3  2768.75   Medium
9 2025-01-10   Monitor  14000.0    Chennai         1  1800.00   Medium
5 2025-01-06   Monitor  12000.0  Hyderabad         2  1500.00   Medium
7 2025-01-08  Keyboard   3000.0     Mumbai         2   400.00      Low
4 2025-01-05     Mouse   1700.0    Chennai         4   250.00      Low
1 2025-01-02     Mouse   1500.0     Mumbai         5   200.00      Low

### GST Column Added

In [45]:
df['GST'] = df['Sales'] * 0.18
df

        Date   Product    Sales       City  Quantity   Profit Category     GST
0 2025-01-01    Laptop  50000.0       Pune         2  5000.00   Medium  9000.0
1 2025-01-02     Mouse   1500.0     Mumbai         5   200.00      Low   270.0
2 2025-01-03    Laptop  52000.0      Delhi         1  6000.00     High  9360.0
3 2025-01-04  Keyboard  23650.0  Bangalore         3  2768.75   Medium  4257.0
4 2025-01-05     Mouse   1700.0    Chennai         4   250.00      Low   306.0
5 2025-01-06   Monitor  12000.0  Hyderabad         2  1500.00   Medium  2160.0
6 2025-01-07    Laptop  55000.0       Pune         1  7000.00     High  9900.0
7 2025-01-08  Keyboard   3000.0     Mumbai         2   400.00      Low   540.0
8 2025-01-09     Mouse  23650.0      Delhi         6  2768.75   Medium  4257.0
9 2025-01-10   Monitor  14000.0    Chennai         1  1800.00   Medium  2520.0

### Discount Column Added

In [47]:
df['Discount'] = df['Sales'] * 0.05
df

,Date,Product,Sales,City,Quantity,Profit,Category,GST,Discount
0,2025-01-01,Laptop,50000.0,Pune,2,5000.00,Medium,9000.0,2500.0
1,2025-01-02,Mouse,1500.0,Mumbai,5,200.00,Low,270.0,75.0
2,2025-01-03,Laptop,52000.0,Delhi,1,6000.00,High,9360.0,2600.0
3,2025-01-04,Keyboard,23650.0,Bangalore,3,2768.75,Medium,4257.0,1182.5
4,2025-01-05,Mouse,1700.0,Chennai,4,250.00,Low,306.0,85.0
5,2025-01-06,Monitor,12000.0,Hyderabad,2,1500.00,Medium,2160.0,600.0
6,2025-01-07,Laptop,55000.0,Pune,1,7000.00,High,9900.0,2750.0
7,2025-01-08,Keyboard,3000.0,Mumbai,2,400.00,Low,540.0,150.0
8,2025-01-09,Mouse,23650.0,Delhi,6,2768.75,Medium,4257.0,1182.5
9,2025-01-10,Monitor,14000.0,Chennai,1,1800.00,Medium,2520.0,700.0

### Profit Percentage

In [53]:
df['Profit_Percentage'] = np.round(((df['Profit']/df['Sales'])*100),2)
df

,Date,Product,Sales,City,Quantity,Profit,Category,GST,Discount,Profit_Percentage
0,2025-01-01,Laptop,50000.0,Pune,2,5000.00,Medium,9000.0,2500.0,10.00
1,2025-01-02,Mouse,1500.0,Mumbai,5,200.00,Low,270.0,75.0,13.33
2,2025-01-03,Laptop,52000.0,Delhi,1,6000.00,High,9360.0,2600.0,11.54
3,2025-01-04,Keyboard,23650.0,Bangalore,3,2768.75,Medium,4257.0,1182.5,11.71
4,2025-01-05,Mouse,1700.0,Chennai,4,250.00,Low,306.0,85.0,14.71
5,2025-01-06,Monitor,12000.0,Hyderabad,2,1500.00,Medium,2160.0,600.0,12.50
6,2025-01-07,Laptop,55000.0,Pune,1,7000.00,High,9900.0,2750.0,12.73
7,2025-01-08,Keyboard,3000.0,Mumbai,2,400.00,Low,540.0,150.0,13.33
8,2025-01-09,Mouse,23650.0,Delhi,6,2768.75,Medium,4257.0,1182.5,11.71
9,2025-01-10,Monitor,14000.0,Chennai,1,1800.00,Medium,2520.0,700.0,12.86

### Extract Year

In [58]:
df['Year'] = df['Date'].dt.year
df

,Date,Product,Sales,City,Quantity,Profit,Category,GST,Discount,Profit_Percentage,Year,Month
0,2025-01-01,Laptop,50000.0,Pune,2,5000.00,Medium,9000.0,2500.0,10.00,2025,1
1,2025-01-02,Mouse,1500.0,Mumbai,5,200.00,Low,270.0,75.0,13.33,2025,1
2,2025-01-03,Laptop,52000.0,Delhi,1,6000.00,High,9360.0,2600.0,11.54,2025,1
3,2025-01-04,Keyboard,23650.0,Bangalore,3,2768.75,Medium,4257.0,1182.5,11.71,2025,1
4,2025-01-05,Mouse,1700.0,Chennai,4,250.00,Low,306.0,85.0,14.71,2025,1
5,2025-01-06,Monitor,12000.0,Hyderabad,2,1500.00,Medium,2160.0,600.0,12.50,2025,1
6,2025-01-07,Laptop,55000.0,Pune,1,7000.00,High,9900.0,2750.0,12.73,2025,1
7,2025-01-08,Keyboard,3000.0,Mumbai,2,400.00,Low,540.0,150.0,13.33,2025,1
8,2025-01-09,Mouse,23650.0,Delhi,6,2768.75,Medium,4257.0,1182.5,11.71,2025,1
9,2025-01-10,Monitor,14000.0,Chennai,1,1800.00,Medium,2520.0,700.0,12.86,2025,1

### Extract Month

In [59]:
df['Month'] = df['Date'].dt.month
df

,Date,Product,Sales,City,Quantity,Profit,Category,GST,Discount,Profit_Percentage,Year,Month
0,2025-01-01,Laptop,50000.0,Pune,2,5000.00,Medium,9000.0,2500.0,10.00,2025,1
1,2025-01-02,Mouse,1500.0,Mumbai,5,200.00,Low,270.0,75.0,13.33,2025,1
2,2025-01-03,Laptop,52000.0,Delhi,1,6000.00,High,9360.0,2600.0,11.54,2025,1
3,2025-01-04,Keyboard,23650.0,Bangalore,3,2768.75,Medium,4257.0,1182.5,11.71,2025,1
4,2025-01-05,Mouse,1700.0,Chennai,4,250.00,Low,306.0,85.0,14.71,2025,1
5,2025-01-06,Monitor,12000.0,Hyderabad,2,1500.00,Medium,2160.0,600.0,12.50,2025,1
6,2025-01-07,Laptop,55000.0,Pune,1,7000.00,High,9900.0,2750.0,12.73,2025,1
7,2025-01-08,Keyboard,3000.0,Mumbai,2,400.00,Low,540.0,150.0,13.33,2025,1
8,2025-01-09,Mouse,23650.0,Delhi,6,2768.75,Medium,4257.0,1182.5,11.71,2025,1
9,2025-01-10,Monitor,14000.0,Chennai,1,1800.00,Medium,2520.0,700.0,12.86,2025,1

### Extract Day

In [61]:
df['Day'] = df['Date'].dt.day
df

,Date,Product,Sales,City,Quantity,Profit,Category,GST,Discount,Profit_Percentage,Year,Month,Day
0,2025-01-01,Laptop,50000.0,Pune,2,5000.00,Medium,9000.0,2500.0,10.00,2025,1,1
1,2025-01-02,Mouse,1500.0,Mumbai,5,200.00,Low,270.0,75.0,13.33,2025,1,2
2,2025-01-03,Laptop,52000.0,Delhi,1,6000.00,High,9360.0,2600.0,11.54,2025,1,3
3,2025-01-04,Keyboard,23650.0,Bangalore,3,2768.75,Medium,4257.0,1182.5,11.71,2025,1,4
4,2025-01-05,Mouse,1700.0,Chennai,4,250.00,Low,306.0,85.0,14.71,2025,1,5
5,2025-01-06,Monitor,12000.0,Hyderabad,2,1500.00,Medium,2160.0,600.0,12.50,2025,1,6
6,2025-01-07,Laptop,55000.0,Pune,1,7000.00,High,9900.0,2750.0,12.73,2025,1,7
7,2025-01-08,Keyboard,3000.0,Mumbai,2,400.00,Low,540.0,150.0,13.33,2025,1,8
8,2025-01-09,Mouse,23650.0,Delhi,6,2768.75,Medium,4257.0,1182.5,11.71,2025,1,9
9,2025-01-10,Monitor,14000.0,Chennai,1,1800.00,Medium,2520.0,700.0,12.86,2025,1,10

### Pivot Table

In [69]:
print(pd.pivot_table(df,
                     values='Sales',
                     index='Product',
                     columns='City',
                     aggfunc='sum'))

print("\n\nMising Values Fill with Zero:-\n\n",pd.pivot_table(df,
                     values='Sales',
                     index='Product',
                     columns='City',
                     aggfunc='sum',
                     fill_value=0
                    ))

City      Bangalore  Chennai    Delhi  Hyderabad  Mumbai      Pune
Product
Keyboard    23650.0      NaN      NaN        NaN  3000.0       NaN
Laptop          NaN      NaN  52000.0        NaN     NaN  105000.0
Monitor         NaN  14000.0      NaN    12000.0     NaN       NaN
Mouse           NaN   1700.0  23650.0        NaN  1500.0       NaN


Mising Values Fill with Zero:-

 City      Bangalore  Chennai    Delhi  Hyderabad  Mumbai      Pune
Product
Keyboard    23650.0      0.0      0.0        0.0  3000.0       0.0
Laptop          0.0      0.0  52000.0        0.0     0.0  105000.0
Monitor         0.0  14000.0      0.0    12000.0     0.0       0.0
Mouse           0.0   1700.0  23650.0        0.0  1500.0       0.0

### Correlation

In [62]:
print(df.corr(numeric_only=True))

                      Sales  Quantity    Profit       GST  Discount  \
Sales              1.000000 -0.472070  0.990286  1.000000  1.000000
Quantity          -0.472070  1.000000 -0.491923 -0.472070 -0.472070
Profit             0.990286 -0.491923  1.000000  0.990286  0.990286
GST                1.000000 -0.472070  0.990286  1.000000  1.000000
Discount           1.000000 -0.472070  0.990286  1.000000  1.000000
Profit_Percentage -0.702418  0.183010 -0.623725 -0.702418 -0.702418
Year                    NaN       NaN       NaN       NaN       NaN
Month                   NaN       NaN       NaN       NaN       NaN
Day               -0.265888 -0.051923 -0.185613 -0.265888 -0.265888

                   Profit_Percentage  Year  Month       Day
Sales                      -0.702418   NaN    NaN -0.265888
Quantity                    0.183010   NaN    NaN -0.051923
Profit                     -0.623725   NaN    NaN -0.185613
GST                        -0.702418   NaN    NaN -0.265888
Discount                   -0.702418   NaN    NaN -0.265888
Profit_Percentage           1.000000   NaN    NaN  0.345923
Year                             NaN   NaN    NaN       NaN
Month                            NaN   NaN    NaN       NaN
Day                         0.345923   NaN    NaN  1.000000