## IMPORTANT DATA ANALYSIS FUNCTION

In [1]:
import pandas as pd

import numpy as np

In [2]:
data = {
    "Name": ["Aman", "Rahul", "Sneha", "Priya"],
    
    "Department": ["IT", "HR", "Finance", "IT"],
    
    "Salary": [50000, 60000, 70000, 80000],
    
    "Skills": [
        ["Python", "SQL"],
        ["Excel", "Power BI"],
        ["Finance", "Excel"],
        ["Python", "ML"]
    ]
}

df = pd.DataFrame(data)

df

    Name Department  Salary             Skills
0   Aman         IT   50000      [Python, SQL]
1  Rahul         HR   60000  [Excel, Power BI]
2  Sneha    Finance   70000   [Finance, Excel]
3  Priya         IT   80000       [Python, ML]

### NORMALIZE

### Normalize Using value_counts()
    Gives percentage distribution

In [3]:
df["Department"].value_counts(normalize=True)

Department
IT         0.50
HR         0.25
Finance    0.25
Name: proportion, dtype: float64

### Convert Into Percentage Distribution

In [4]:
df["Department"].value_counts(normalize=True) * 100

Department
IT         50.0
HR         25.0
Finance    25.0
Name: proportion, dtype: float64

### DATA TYPE CONVERSATION

#### Check Datatype

In [6]:
df.dtypes

Name          object
Department    object
Salary         int64
Skills        object
dtype: object

#### Convert To Float

In [7]:
df["Salary"] = df["Salary"].astype(float)

df.dtypes

Name           object
Department     object
Salary        float64
Skills         object
dtype: object

#### Convert To String

In [8]:
df["Salary"] = df["Salary"].astype(str)

df.dtypes

Name          object
Department    object
Salary        object
Skills        object
dtype: object

#### to_numeric()

In [9]:
df["Salary"] = pd.to_numeric(df["Salary"])

df.dtypes

Name           object
Department     object
Salary        float64
Skills         object
dtype: object

#### to_datetime()

In [10]:
date_df = pd.DataFrame({
    "Date": ["2025-01-01", "2025-02-10"]
})

date_df["Date"] = pd.to_datetime(date_df["Date"])

date_df.dtypes

Date    datetime64[ns]
dtype: object

## query()
    Used for filtering data

#### Filter Salary > 60000

In [14]:
df.query("Salary > 60000")

    Name Department   Salary            Skills
2  Sneha    Finance  70000.0  [Finance, Excel]
3  Priya         IT  80000.0      [Python, ML]

#### Multiple Conditions

In [12]:
df.query("Salary > 50000 and Department == 'IT'")

    Name Department   Salary        Skills
3  Priya         IT  80000.0  [Python, ML]

#### VARIABLE IN query()

In [13]:
value = 60000

df.query("Salary >= @value")

    Name Department   Salary             Skills
1  Rahul         HR  60000.0  [Excel, Power BI]
2  Sneha    Finance  70000.0   [Finance, Excel]
3  Priya         IT  80000.0       [Python, ML]

### explode()
    Used to separate list values into rows

#### BEFORE explode()

In [15]:
df

    Name Department   Salary             Skills
0   Aman         IT  50000.0      [Python, SQL]
1  Rahul         HR  60000.0  [Excel, Power BI]
2  Sneha    Finance  70000.0   [Finance, Excel]
3  Priya         IT  80000.0       [Python, ML]

#### AFTER explode()

In [16]:
df.explode("Skills")

    Name Department   Salary    Skills
0   Aman         IT  50000.0    Python
0   Aman         IT  50000.0       SQL
1  Rahul         HR  60000.0     Excel
1  Rahul         HR  60000.0  Power BI
2  Sneha    Finance  70000.0   Finance
2  Sneha    Finance  70000.0     Excel
3  Priya         IT  80000.0    Python
3  Priya         IT  80000.0        ML

### melt()
    Converts wide data into long data

In [17]:
sales_df = pd.DataFrame({
    "Name": ["Aman", "Rahul"],
    
    "Jan": [100, 200],
    
    "Feb": [150, 250]
})

sales_df

    Name  Jan  Feb
0   Aman  100  150
1  Rahul  200  250

In [18]:
sales_df.melt(
    id_vars="Name",
    
    var_name="Month",
    
    value_name="Sales"
)

    Name Month  Sales
0   Aman   Jan    100
1  Rahul   Jan    200
2   Aman   Feb    150
3  Rahul   Feb    250

### stack()
    Column TO rows

In [19]:
stack_df = pd.DataFrame({
    "A": [1,2],
    "B": [3,4]
})

stack_df

   A  B
0  1  3
1  2  4

In [20]:
stack_df.stack()

0  A    1
   B    3
1  A    2
   B    4
dtype: int64

### unstack()
    Rows To Columns

In [21]:
stack_df.stack().unstack()

   A  B
0  1  3
1  2  4

### MEMORY USAGE
    For Memory Optimization Is Usefull

#### Memory Usage of each column

In [22]:
df.memory_usage()

Index         132
Name           32
Department     32
Salary         32
Skills         32
dtype: int64

#### Total Memory

In [24]:
df.memory_usage().sum()

np.int64(260)

#### Deep Memory Check
    Exact Used Shows

In [25]:
df.memory_usage(deep=True)

Index         132
Name          215
Department    209
Salary         32
Skills        320
dtype: int64

#### MEMORY OPTIMIZATION
    category uses less memory

In [26]:
df["Department"] = df["Department"].astype("category")

df.dtypes

Name            object
Department    category
Salary         float64
Skills          object
dtype: object

### select_dtypes()

In [27]:
df.select_dtypes(include="object")

    Name             Skills
0   Aman      [Python, SQL]
1  Rahul  [Excel, Power BI]
2  Sneha   [Finance, Excel]
3  Priya       [Python, ML]

#### Rename()

In [28]:
df.rename(columns={"Salary": "Income"})

    Name Department   Income             Skills
0   Aman         IT  50000.0      [Python, SQL]
1  Rahul         HR  60000.0  [Excel, Power BI]
2  Sneha    Finance  70000.0   [Finance, Excel]
3  Priya         IT  80000.0       [Python, ML]

#### sort_values()

In [29]:
df.sort_values(by="Salary")

    Name Department   Salary             Skills
0   Aman         IT  50000.0      [Python, SQL]
1  Rahul         HR  60000.0  [Excel, Power BI]
2  Sneha    Finance  70000.0   [Finance, Excel]
3  Priya         IT  80000.0       [Python, ML]

#### isin()

In [32]:
df[df["Department"].isin(["IT", "HR"])]

    Name Department   Salary             Skills
0   Aman         IT  50000.0      [Python, SQL]
1  Rahul         HR  60000.0  [Excel, Power BI]
3  Priya         IT  80000.0       [Python, ML]

#### between()

In [34]:
df[df["Salary"].between(50000, 70000)]

    Name Department   Salary             Skills
0   Aman         IT  50000.0      [Python, SQL]
1  Rahul         HR  60000.0  [Excel, Power BI]
2  Sneha    Finance  70000.0   [Finance, Excel]

#### clip()
    Limits Values

In [35]:
df["Salary"].clip(upper=70000)

0    50000.0
1    60000.0
2    70000.0
3    70000.0
Name: Salary, dtype: float64

#### where()

In [37]:
df["Salary"].where(df["Salary"] > 60000)

0        NaN
1        NaN
2    70000.0
3    80000.0
Name: Salary, dtype: float64

#### mask()
    Opposite of where()

In [38]:
df["Salary"].mask(df["Salary"] > 60000)

0    50000.0
1    60000.0
2        NaN
3        NaN
Name: Salary, dtype: float64

#### info

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Department  4 non-null      category
 2   Salary      4 non-null      float64
 3   Skills      4 non-null      object
dtypes: category(1), float64(1), object(2)
memory usage: 364.0+ bytes

#### describe()

In [30]:
df.describe()

             Salary
count      4.000000
mean   65000.000000
std    12909.944487
min    50000.000000
25%    57500.000000
50%    65000.000000
75%    72500.000000
max    80000.000000