### PANDAS MULTIINDEX
    Access hierachical rows

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Department": ["IT", "IT", "HR", "HR", "Finance", "Finance"],
    "Employee": ["Aman", "Rahul", "Sneha", "Priya", "Karan", "Rohit"],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Delhi", "Mumbai"],
    "Salary": [50000, 60000, 45000, 52000, 70000, 65000],
    "Bonus": [5000, 6000, 4000, 4500, 7000, 6500]
}

df = pd.DataFrame(data)

df

  Department Employee    City  Salary  Bonus
0         IT     Aman    Pune   50000   5000
1         IT    Rahul  Mumbai   60000   6000
2         HR    Sneha   Delhi   45000   4000
3         HR    Priya    Pune   52000   4500
4    Finance    Karan   Delhi   70000   7000
5    Finance    Rohit  Mumbai   65000   6500

### Set Single index

In [3]:
df1 = df.set_index("Department")

df1

           Employee    City  Salary  Bonus
Department
IT             Aman    Pune   50000   5000
IT            Rahul  Mumbai   60000   6000
HR            Sneha   Delhi   45000   4000
HR            Priya    Pune   52000   4500
Finance       Karan   Delhi   70000   7000
Finance       Rohit  Mumbai   65000   6500

### Set MultiIndex

In [4]:
df2 = df.set_index(["Department", "Employee"])

df2

                       City  Salary  Bonus
Department Employee
IT         Aman        Pune   50000   5000
           Rahul     Mumbai   60000   6000
HR         Sneha      Delhi   45000   4000
           Priya       Pune   52000   4500
Finance    Karan      Delhi   70000   7000
           Rohit     Mumbai   65000   6500

### Check Index

In [5]:
df2.index

MultiIndex([(     'IT',  'Aman'),
            (     'IT', 'Rahul'),
            (     'HR', 'Sneha'),
            (     'HR', 'Priya'),
            ('Finance', 'Karan'),
            ('Finance', 'Rohit')],
           names=['Department', 'Employee'])

### Access data using loc[]

In [6]:
df2.loc["IT"]

            City  Salary  Bonus
Employee
Aman        Pune   50000   5000
Rahul     Mumbai   60000   6000

### Access particular Rows

In [7]:
df2.loc[("IT", "Aman")]

City       Pune
Salary    50000
Bonus      5000
Name: (IT, Aman), dtype: object

### Access Multiple Rows

In [8]:
df2.loc[[("IT", "Aman"), ("HR", "Sneha")]]

                      City  Salary  Bonus
Department Employee
IT         Aman       Pune   50000   5000
HR         Sneha     Delhi   45000   4000

### Reset Index

In [9]:
df2.reset_index()

  Department Employee    City  Salary  Bonus
0         IT     Aman    Pune   50000   5000
1         IT    Rahul  Mumbai   60000   6000
2         HR    Sneha   Delhi   45000   4000
3         HR    Priya    Pune   52000   4500
4    Finance    Karan   Delhi   70000   7000
5    Finance    Rohit  Mumbai   65000   6500

### Sort Index

In [11]:
df2.sort_index()

                       City  Salary  Bonus
Department Employee
Finance    Karan      Delhi   70000   7000
           Rohit     Mumbai   65000   6500
HR         Priya       Pune   52000   4500
           Sneha      Delhi   45000   4000
IT         Aman        Pune   50000   5000
           Rahul     Mumbai   60000   6000

### Sort Index Using Level

In [12]:
df2.sort_index(level="Department")

                       City  Salary  Bonus
Department Employee
Finance    Karan      Delhi   70000   7000
           Rohit     Mumbai   65000   6500
HR         Priya       Pune   52000   4500
           Sneha      Delhi   45000   4000
IT         Aman        Pune   50000   5000
           Rahul     Mumbai   60000   6000

### Get Level Values

In [13]:
df2.index.get_level_values(0)

Index(['IT', 'IT', 'HR', 'HR', 'Finance', 'Finance'], dtype='object', name='Department')

### Get First Level Values

In [14]:
df2.index.get_level_values(1)

Index(['Aman', 'Rahul', 'Sneha', 'Priya', 'Karan', 'Rohit'], dtype='object', name='Employee')

### MultiIndex with Column

In [15]:
pivot1 = pd.pivot_table(
    df,
    values=["Salary", "Bonus"],
    index=["Department", "Employee"],
    columns="City",
    aggfunc="sum",
    fill_value=0
)

pivot1

                    Bonus              Salary
City                Delhi Mumbai  Pune  Delhi Mumbai   Pune
Department Employee
Finance    Karan     7000      0     0  70000      0      0
           Rohit        0   6500     0      0  65000      0
HR         Priya        0      0  4500      0      0  52000
           Sneha     4000      0     0  45000      0      0
IT         Aman         0      0  5000      0      0  50000
           Rahul        0   6000     0      0  60000      0

### Swap Level
    Used to interchange index levels.

In [16]:
df2.swaplevel()

                       City  Salary  Bonus
Employee Department
Aman     IT            Pune   50000   5000
Rahul    IT          Mumbai   60000   6000
Sneha    HR           Delhi   45000   4000
Priya    HR            Pune   52000   4500
Karan    Finance      Delhi   70000   7000
Rohit    Finance     Mumbai   65000   6500

### Remove Level
    Used to remove one index level

In [17]:
df2.droplevel(0)

            City  Salary  Bonus
Employee
Aman        Pune   50000   5000
Rahul     Mumbai   60000   6000
Sneha      Delhi   45000   4000
Priya       Pune   52000   4500
Karan      Delhi   70000   7000
Rohit     Mumbai   65000   6500

### Groupby with multindex

In [18]:
group1 = df.groupby(
    ["Department", "City"]
)["Salary"].mean()

group1

Department  City
Finance     Delhi     70000.0
            Mumbai    65000.0
HR          Delhi     45000.0
            Pune      52000.0
IT          Mumbai    60000.0
            Pune      50000.0
Name: Salary, dtype: float64

### Convert series to dataframe

In [19]:
group1.to_frame()

                    Salary
Department City
Finance    Delhi   70000.0
           Mumbai  65000.0
HR         Delhi   45000.0
           Pune    52000.0
IT         Mumbai  60000.0
           Pune    50000.0

### Access multiindex column

In [24]:
pivot2 = pd.pivot_table(
    df,
    values=["Salary", "Bonus"],
    index="Department",
    aggfunc=["sum", "mean"]
)
pivot2

              sum            mean
            Bonus  Salary   Bonus   Salary
Department
Finance     13500  135000  6750.0  67500.0
HR           8500   97000  4250.0  48500.0
IT          11000  110000  5500.0  55000.0

In [26]:
pivot2['sum']

            Bonus  Salary
Department
Finance     13500  135000
HR           8500   97000
IT          11000  110000

### Access particular column

In [22]:
pivot2["sum"]["Salary"]

Department
Finance    135000
HR          97000
IT         110000
Name: Salary, dtype: int64

### Flatten multiindex column

In [23]:
pivot2.columns = ['_'.join(col) for col in pivot2.columns]

pivot2

            sum_Bonus  sum_Salary  mean_Bonus  mean_Salary
Department
Finance         13500      135000      6750.0      67500.0
HR               8500       97000      4250.0      48500.0
IT              11000      110000      5500.0      55000.0

### Rename Index

In [25]:
df2.rename_axis(
    ["Dept", "Emp"]
)

                 City  Salary  Bonus
Dept    Emp
IT      Aman     Pune   50000   5000
        Rahul  Mumbai   60000   6000
HR      Sneha   Delhi   45000   4000
        Priya    Pune   52000   4500
Finance Karan   Delhi   70000   7000
        Rohit  Mumbai   65000   6500

### xs()
    xs = Cross Section
    Used to filter specific level data from MultiIndex.

In [28]:
df2.xs("IT")

            City  Salary  Bonus
Employee
Aman        Pune   50000   5000
Rahul     Mumbai   60000   6000

### Filter second level

In [29]:
df2.xs("Aman", level="Employee")

            City  Salary  Bonus
Department
IT          Pune   50000   5000