In [69]:
import pandas as pd
import numpy as np

In [70]:
import pandas as pd
import random

random.seed(42)

names = [
    "rahul sharma", "RAHUL SHARMA", "Rahul  Sharma",
    "pooja patil", "AKSHAY kumar", "Sanjay Patil"
]

genders = ["M", "F", "Male", "Female", "male", "female", None]

departments = [
    "Data Analyst",
    "data analyst",
    "DATA ANALYST",
    "Busines Analyst",
    "Business Analyst",
    None
]

cities = [
    "Mumbai",
    "mumbai",
    " MUMBAI ",
    "Pune",
    "pune",
    "Bangalore",
    "belgaum",
    None
]

emails = [
    "USER@GMAIL.COM",
    " test@mail.com ",
    "employee@company.com",
    "invalid_email",
    None
]

dates = [
    "2024-01-15",
    "15/01/2024",
    "Jan 15 2024",
    None
]

rows = []

for i in range(2000):

    emp_id = 10000 + i

    if i % 150 == 0 and i > 0:
        emp_id = 10000 + i - 1   # duplicate IDs

    rows.append({
        "Employee_ID": emp_id,
        "Name": random.choice(names),
        "Age": random.choice([22, 25, 30, 35, 45, None, -5, 150]),
        "Gender": random.choice(genders),
        "Department": random.choice(departments),
        "City": random.choice(cities),
        "Salary": random.choice([25000, 30000, 45000, 60000, None, 5000000]),
        "Experience_Years": random.choice([1, 2, 5, 8, None, -3, 40]),
        "Email": random.choice(emails),
        "Joining_Date": random.choice(dates)
    })

df = pd.DataFrame(rows)

df.to_csv("employee_dirty_2000_rows.csv", index=False)

print("CSV Created Successfully")

CSV Created Successfully

In [41]:
df=pd.read_csv("employee_dirty_2000_rows.csv")

In [42]:
df.head(10)

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience_Years,Email,Joining_Date
0,10000,Sanjay Patil,25.0,M,NaN,pune,30000.0,2.0,test@mail.com,2024-01-15
1,10001,Sanjay Patil,25.0,male,Busines Analyst,Mumbai,25000.0,1.0,test@mail.com,15/01/2024
2,10002,AKSHAY kumar,22.0,male,data analyst,belgaum,30000.0,8.0,NaN,Jan 15 2024
3,10003,rahul sharma,30.0,female,Busines Analyst,Bangalore,45000.0,2.0,test@mail.com,Jan 15 2024
4,10004,rahul sharma,25.0,Female,Data Analyst,Bangalore,45000.0,NaN,employee@company.com,2024-01-15
5,10005,Sanjay Patil,150.0,male,Data Analyst,belgaum,25000.0,NaN,employee@company.com,Jan 15 2024
6,10006,AKSHAY kumar,35.0,female,Data Analyst,Mumbai,5000000.0,2.0,employee@company.com,2024-01-15
7,10007,RAHUL SHARMA,25.0,Female,DATA ANALYST,NaN,5000000.0,40.0,employee@company.com,15/01/2024
8,10008,Rahul Sharma,NaN,F,NaN,pune,5000000.0,-3.0,USER@GMAIL.COM,15/01/2024
9,10009,AKSHAY kumar,35.0,F,Busines Analyst,belgaum,45000.0,-3.0,NaN,15/01/2024

In [43]:
df.shape

(2000, 10)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       2000 non-null   int64
 1   Name              2000 non-null   object
 2   Age               1767 non-null   float64
 3   Gender            1702 non-null   object
 4   Department        1630 non-null   object
 5   City              1748 non-null   object
 6   Salary            1679 non-null   float64
 7   Experience_Years  1723 non-null   float64
 8   Email             1617 non-null   object
 9   Joining_Date      1506 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 156.4+ KB

In [45]:
df.describe()

        Employee_ID          Age        Salary  Experience_Years
count   2000.000000  1767.000000  1.679000e+03       1723.000000
mean   10999.493500    45.221279  9.615992e+05          8.864771
std      577.494026    47.430109  1.929926e+06         14.506386
min    10000.000000    -5.000000  2.500000e+04         -3.000000
25%    10499.750000    22.000000  3.000000e+04          1.000000
50%    10999.500000    30.000000  4.500000e+04          2.000000
75%    11499.000000    45.000000  6.000000e+04          8.000000
max    11999.000000   150.000000  5.000000e+06         40.000000

In [46]:
df.isnull().sum()

Employee_ID           0
Name                  0
Age                 233
Gender              298
Department          370
City                252
Salary              321
Experience_Years    277
Email               383
Joining_Date        494
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(0)

### Formating Inconsistent Values

In [92]:
df.columns = df.columns.str.strip()

In [93]:
df["Name"] = df["Name"].str.strip().str.title()
df.head()

,Employee_ID,Name,Age,Gender,Department,City,Salary,Experience_Years,Email,Joining_Date
0,10000,Sanjay Patil,25,M,None,Pune,30000.0,2.0,test@mail.com,2024-01-15
1,10001,Sanjay Patil,25,Male,Busines Analyst,Mumbai,25000.0,1.0,test@mail.com,NaT
2,10002,Akshay Kumar,22,Male,Data Analyst,Belgaum,30000.0,8.0,None,NaT
3,10003,Rahul Sharma,30,Female,Busines Analyst,Bangalore,45000.0,2.0,test@mail.com,NaT
6,10006,Akshay Kumar,35,Female,Data Analyst,Mumbai,5000000.0,2.0,employee@company.com,2024-01-15

In [94]:
df["Department"] = df["Department"].str.strip().str.title()

In [95]:
df["City"] = df["City"].str.strip().str.title()

In [96]:
df["Email"] = df["Email"].str.strip().str.lower()

In [97]:
df["Email"].unique()

array(['test@mail.com', None, 'employee@company.com', 'invalid_email',
       'user@gmail.com'], dtype=object)

In [98]:
df["Gender"] = df["Gender"].str.strip().str.title()

### Removing Invalid Age

In [99]:
df = df[
((df["Age"] >= 18) &
(df["Age"] <= 60))
]

In [100]:
df['Age'].unique()

array([25, 22, 30, 35, 45])

In [101]:
# Invalid Experience Years
df = df[
df["Experience_Years"] >= 0
]

### Spliting And Removing

In [102]:
Name_split = df["Name"].str.split(" ", expand=True)

In [103]:
df.insert(1, "First_Name", Name_split[0])

df.insert(2, "Last_Name", Name_split[1])
df.head()

,Employee_ID,First_Name,Last_Name,Name,Age,Gender,Department,City,Salary,Experience_Years,Email,Joining_Date
0,10000,Sanjay,Patil,Sanjay Patil,25,M,None,Pune,30000.0,2.0,test@mail.com,2024-01-15
1,10001,Sanjay,Patil,Sanjay Patil,25,Male,Busines Analyst,Mumbai,25000.0,1.0,test@mail.com,NaT
2,10002,Akshay,Kumar,Akshay Kumar,22,Male,Data Analyst,Belgaum,30000.0,8.0,None,NaT
3,10003,Rahul,Sharma,Rahul Sharma,30,Female,Busines Analyst,Bangalore,45000.0,2.0,test@mail.com,NaT
6,10006,Akshay,Kumar,Akshay Kumar,35,Female,Data Analyst,Mumbai,5000000.0,2.0,employee@company.com,2024-01-15

#### Drop Full Name Column

In [104]:
df.drop("Name",axis=1,inplace=True)
df.head()

,Employee_ID,First_Name,Last_Name,Age,Gender,Department,City,Salary,Experience_Years,Email,Joining_Date
0,10000,Sanjay,Patil,25,M,None,Pune,30000.0,2.0,test@mail.com,2024-01-15
1,10001,Sanjay,Patil,25,Male,Busines Analyst,Mumbai,25000.0,1.0,test@mail.com,NaT
2,10002,Akshay,Kumar,22,Male,Data Analyst,Belgaum,30000.0,8.0,None,NaT
3,10003,Rahul,Sharma,30,Female,Busines Analyst,Bangalore,45000.0,2.0,test@mail.com,NaT
6,10006,Akshay,Kumar,35,Female,Data Analyst,Mumbai,5000000.0,2.0,employee@company.com,2024-01-15

#### Removing Duplicates

In [143]:
df[df.duplicated(subset=["Employee_ID"], keep=False)]

,Employee_ID,First_Name,Last_Name,Age,Gender,Department,City,Salary,Experience_Years,Email,Joining_Date
299,10299,Rahul,Sharma,35,Female,Business Analyst,Pune,60000.0,2.0,employee@company.com,NaT
300,10299,Rahul,Sharma,35,Female,Data Analyst,Mumbai,5000000.0,40.0,invalid_email,NaT
1799,11799,Akshay,Kumar,22,Male,Data Analyst,Mumbai,5000000.0,5.0,employee@company.com,2024-01-15
1800,11799,Rahul,Sharma,25,Female,Data Analyst,Mumbai,60000.0,1.0,Not Available,2024-01-15

In [144]:
df["Employee_ID"].duplicated().sum()

np.int64(2)

In [145]:
df = df.drop_duplicates(
    subset=["Employee_ID"],
    keep="first"
)

In [147]:
df["Employee_ID"].duplicated().any()

np.False_

### Replacing Values

In [105]:
df["Gender"].unique()

array(['M', 'Male', 'Female', None, 'F'], dtype=object)

In [106]:
df["Gender"] = df["Gender"].replace(
{
"M":"Male",
"male":"Male",
"F":"Female",
"female":"Female"
}
)

In [107]:
df["Gender"].unique()

array(['Male', 'Female', None], dtype=object)

In [108]:
df["Department"].unique()

array([None, 'Busines Analyst', 'Data Analyst', 'Business Analyst'],
      dtype=object)

In [109]:
df["Department"] = df["Department"].replace(
{
"Busines Analyst":"Business Analyst"
}
)

In [110]:
df["Department"].unique()

array([None, 'Business Analyst', 'Data Analyst'], dtype=object)

### Filling NAN Values

In [111]:
df["Salary"] = df["Salary"].fillna(
df["Salary"].median()
)

In [118]:
df["Gender"] = df["Gender"].fillna(
    df["Gender"].mode()[0]
)

In [119]:
df["Department"] = df["Department"].fillna(
    df["Department"].mode()[0]
)

In [122]:
df["City"] = df["City"].fillna(
    df["City"].mode()[0]
)

In [124]:
df["Email"] = df["Email"].fillna("Not Available")

In [125]:
df["Email"] = df["Email"].fillna("Not Available")

### Convert Data Types

In [112]:
df["Joining_Date"] = pd.to_datetime(
df["Joining_Date"],
errors="coerce"
)

df["Joining_Date"].dtypes  # NaT (Not a Time) is Pandas' standard representation for missing or invalid values in datetime columns, 
                           # similar to how NaN represents missing values in numeric columns.

dtype('<M8[ns]')

In [113]:
df["Age"] = df["Age"].astype(int)

In [133]:
df["Gender"]= df["Gender"].astype("category")

In [134]:
df["City"]= df["City"].astype("category")

In [135]:
df["Department"]= df["Department"].astype("category")

In [136]:
df.dtypes

Employee_ID                  int64
First_Name                  object
Last_Name                   object
Age                          int64
Gender                    category
Department                category
City                      category
Salary                     float64
Experience_Years           float64
Email                       object
Joining_Date        datetime64[ns]
dtype: object

In [141]:
df['Employee_ID'].duplicated().sum()

np.int64(2)

In [148]:
df.to_csv("Cleaned_04",index=False)
print("Data Saved Succesufully")

Data Saved Succesufully