# Pandas Practice Quistions

In [1]:
import pandas as pd

### 1.Reading CSV File

In [99]:
df = pd.read_csv("D:\Ex\Customer_Data.csv")

df

   CusID  Age Gender   Location  Spending Score  Quantity
0   A001   25      M  Bangalore             135       500
1   A002   32      M  Bangalore             145       400
2   A003   65      F  Bangalore             300       500
3   A004   14      F  Bangalore             600       300
4   A005   39      F  Bangalore             450       500
5   A006   28      F  Bangalore              75       200
6   A007   49      F    Chennai             100       400
7   A008   56      F  New Delhi             650        30
8   A009   82      F    Kolkota             432       400
9   A010   97      F    Kolkota             690       800
10  A011   55      F    Kolkota             150       800
11  A012   21      F    Kolkota             100       900
12  A013   18      F    Kolkota             150       200
13  A014   59      F  New Delhi             167       500
14  A015   72      F  New Delhi              92       600
15  A016   47      F  New Delhi             550       500
16  A017   26      F  New Delhi             500       500
17  A018   81      F  New Delhi             765       700
18  A019   22      F     Mumbai             143       500
19  A020   23      M     Mumbai              56       200
20  A021   67      M     Mumbai             165       400
21  A022   45      M     Mumbai             105       300
22  A023   29      M  Hyderabad             180       400
23  A024   71      M    Chennai             455       500
24  A025   17      M  New Delhi             555       300
25  A026   41      M  Hyderabad             197       500
26  A027   69      M    Chennai             435       300

### 2.First Five Row

In [5]:
print(df.head())

  CusID  Age Gender   Location  Spending Score  Quantity
0  A001   25      M  Bangalore             135       500
1  A002   32      M  Bangalore             145       400
2  A003   65      F  Bangalore             300       500
3  A004   14      F  Bangalore             600       300
4  A005   39      F  Bangalore             450       500

In [6]:
df.head(10) # First 10 Rows

  CusID  Age Gender   Location  Spending Score  Quantity
0  A001   25      M  Bangalore             135       500
1  A002   32      M  Bangalore             145       400
2  A003   65      F  Bangalore             300       500
3  A004   14      F  Bangalore             600       300
4  A005   39      F  Bangalore             450       500
5  A006   28      F  Bangalore              75       200
6  A007   49      F    Chennai             100       400
7  A008   56      F  New Delhi             650        30
8  A009   82      F    Kolkota             432       400
9  A010   97      F    Kolkota             690       800

### 3.Last Five Row

In [7]:
print(df.tail())

   CusID  Age Gender   Location  Spending Score  Quantity
22  A023   29      M  Hyderabad             180       400
23  A024   71      M    Chennai             455       500
24  A025   17      M  New Delhi             555       300
25  A026   41      M  Hyderabad             197       500
26  A027   69      M    Chennai             435       300

In [8]:
df.tail(10) # Last 10 Rows

   CusID  Age Gender   Location  Spending Score  Quantity
17  A018   81      F  New Delhi             765       700
18  A019   22      F     Mumbai             143       500
19  A020   23      M     Mumbai              56       200
20  A021   67      M     Mumbai             165       400
21  A022   45      M     Mumbai             105       300
22  A023   29      M  Hyderabad             180       400
23  A024   71      M    Chennai             455       500
24  A025   17      M  New Delhi             555       300
25  A026   41      M  Hyderabad             197       500
26  A027   69      M    Chennai             435       300

### 4.Show Column Names

In [46]:
print(df.columns)

Index(['CusID', 'Age', 'Gender', 'Location', 'Spending Score', 'Quantity'], dtype='object')

### 5.Show Shape of Dataframe

In [11]:
print(df.shape ) # 27 Rows and 6 Column

(27, 6)

### 6.Filtering

In [12]:
print(df[df["Age"] > 30])

   CusID  Age Gender   Location  Spending Score  Quantity
1   A002   32      M  Bangalore             145       400
2   A003   65      F  Bangalore             300       500
4   A005   39      F  Bangalore             450       500
6   A007   49      F    Chennai             100       400
7   A008   56      F  New Delhi             650        30
8   A009   82      F    Kolkota             432       400
9   A010   97      F    Kolkota             690       800
10  A011   55      F    Kolkota             150       800
13  A014   59      F  New Delhi             167       500
14  A015   72      F  New Delhi              92       600
15  A016   47      F  New Delhi             550       500
17  A018   81      F  New Delhi             765       700
20  A021   67      M     Mumbai             165       400
21  A022   45      M     Mumbai             105       300
23  A024   71      M    Chennai             455       500
25  A026   41      M  Hyderabad             197       500
26  A027   69      M    Chennai             435       300

#### Female Customer

In [13]:
print(df[df["Gender"] == "F"])

   CusID  Age Gender   Location  Spending Score  Quantity
2   A003   65      F  Bangalore             300       500
3   A004   14      F  Bangalore             600       300
4   A005   39      F  Bangalore             450       500
5   A006   28      F  Bangalore              75       200
6   A007   49      F    Chennai             100       400
7   A008   56      F  New Delhi             650        30
8   A009   82      F    Kolkota             432       400
9   A010   97      F    Kolkota             690       800
10  A011   55      F    Kolkota             150       800
11  A012   21      F    Kolkota             100       900
12  A013   18      F    Kolkota             150       200
13  A014   59      F  New Delhi             167       500
14  A015   72      F  New Delhi              92       600
15  A016   47      F  New Delhi             550       500
16  A017   26      F  New Delhi             500       500
17  A018   81      F  New Delhi             765       700
18  A019   22      F     Mumbai             143       500

#### Male Customer

In [14]:
print(df[df["Gender"] == "M"])

   CusID  Age Gender   Location  Spending Score  Quantity
0   A001   25      M  Bangalore             135       500
1   A002   32      M  Bangalore             145       400
19  A020   23      M     Mumbai              56       200
20  A021   67      M     Mumbai             165       400
21  A022   45      M     Mumbai             105       300
22  A023   29      M  Hyderabad             180       400
23  A024   71      M    Chennai             455       500
24  A025   17      M  New Delhi             555       300
25  A026   41      M  Hyderabad             197       500
26  A027   69      M    Chennai             435       300

#### High Spending Score

In [15]:
print(df[df["Spending Score"] > 300])

   CusID  Age Gender   Location  Spending Score  Quantity
3   A004   14      F  Bangalore             600       300
4   A005   39      F  Bangalore             450       500
7   A008   56      F  New Delhi             650        30
8   A009   82      F    Kolkota             432       400
9   A010   97      F    Kolkota             690       800
15  A016   47      F  New Delhi             550       500
16  A017   26      F  New Delhi             500       500
17  A018   81      F  New Delhi             765       700
23  A024   71      M    Chennai             455       500
24  A025   17      M  New Delhi             555       300
26  A027   69      M    Chennai             435       300

#### Bangalore Customer

In [16]:
print(df[df["Location"] == "Bangalore"])

  CusID  Age Gender   Location  Spending Score  Quantity
0  A001   25      M  Bangalore             135       500
1  A002   32      M  Bangalore             145       400
2  A003   65      F  Bangalore             300       500
3  A004   14      F  Bangalore             600       300
4  A005   39      F  Bangalore             450       500
5  A006   28      F  Bangalore              75       200

### 7.Adding New Column

In [100]:
df["Bonus"] = df["Spending Score"] * 0.10

print(df)

   CusID  Age Gender   Location  Spending Score  Quantity  Bonus
0   A001   25      M  Bangalore             135       500   13.5
1   A002   32      M  Bangalore             145       400   14.5
2   A003   65      F  Bangalore             300       500   30.0
3   A004   14      F  Bangalore             600       300   60.0
4   A005   39      F  Bangalore             450       500   45.0
5   A006   28      F  Bangalore              75       200    7.5
6   A007   49      F    Chennai             100       400   10.0
7   A008   56      F  New Delhi             650        30   65.0
8   A009   82      F    Kolkota             432       400   43.2
9   A010   97      F    Kolkota             690       800   69.0
10  A011   55      F    Kolkota             150       800   15.0
11  A012   21      F    Kolkota             100       900   10.0
12  A013   18      F    Kolkota             150       200   15.0
13  A014   59      F  New Delhi             167       500   16.7
14  A015   72      F  New Delhi              92       600    9.2
15  A016   47      F  New Delhi             550       500   55.0
16  A017   26      F  New Delhi             500       500   50.0
17  A018   81      F  New Delhi             765       700   76.5
18  A019   22      F     Mumbai             143       500   14.3
19  A020   23      M     Mumbai              56       200    5.6
20  A021   67      M     Mumbai             165       400   16.5
21  A022   45      M     Mumbai             105       300   10.5
22  A023   29      M  Hyderabad             180       400   18.0
23  A024   71      M    Chennai             455       500   45.5
24  A025   17      M  New Delhi             555       300   55.5
25  A026   41      M  Hyderabad             197       500   19.7
26  A027   69      M    Chennai             435       300   43.5

#### Applying Lambada

In [101]:
df["Category"] = df["Spending Score"].apply(
    lambda x: "VIP" if x > 300 else "Normal"
)

df

   CusID  Age Gender   Location  Spending Score  Quantity  Bonus Category
0   A001   25      M  Bangalore             135       500   13.5   Normal
1   A002   32      M  Bangalore             145       400   14.5   Normal
2   A003   65      F  Bangalore             300       500   30.0   Normal
3   A004   14      F  Bangalore             600       300   60.0      VIP
4   A005   39      F  Bangalore             450       500   45.0      VIP
5   A006   28      F  Bangalore              75       200    7.5   Normal
6   A007   49      F    Chennai             100       400   10.0   Normal
7   A008   56      F  New Delhi             650        30   65.0      VIP
8   A009   82      F    Kolkota             432       400   43.2      VIP
9   A010   97      F    Kolkota             690       800   69.0      VIP
10  A011   55      F    Kolkota             150       800   15.0   Normal
11  A012   21      F    Kolkota             100       900   10.0   Normal
12  A013   18      F    Kolkota             150       200   15.0   Normal
13  A014   59      F  New Delhi             167       500   16.7   Normal
14  A015   72      F  New Delhi              92       600    9.2   Normal
15  A016   47      F  New Delhi             550       500   55.0      VIP
16  A017   26      F  New Delhi             500       500   50.0      VIP
17  A018   81      F  New Delhi             765       700   76.5      VIP
18  A019   22      F     Mumbai             143       500   14.3   Normal
19  A020   23      M     Mumbai              56       200    5.6   Normal
20  A021   67      M     Mumbai             165       400   16.5   Normal
21  A022   45      M     Mumbai             105       300   10.5   Normal
22  A023   29      M  Hyderabad             180       400   18.0   Normal
23  A024   71      M    Chennai             455       500   45.5      VIP
24  A025   17      M  New Delhi             555       300   55.5      VIP
25  A026   41      M  Hyderabad             197       500   19.7   Normal
26  A027   69      M    Chennai             435       300   43.5      VIP

#### Age Group

In [102]:
df["Age_Group"] = df["Age"].apply(
    lambda x: "Teen" if x < 18
    else "Adult" if x < 60
    else "Senior"
)
df

,CusID,Age,Gender,Location,Spending Score,Quantity,Bonus,Category,Age_Group
0,A001,25,M,Bangalore,135,500,13.5,Normal,Adult
1,A002,32,M,Bangalore,145,400,14.5,Normal,Adult
2,A003,65,F,Bangalore,300,500,30.0,Normal,Senior
3,A004,14,F,Bangalore,600,300,60.0,VIP,Teen
4,A005,39,F,Bangalore,450,500,45.0,VIP,Adult
5,A006,28,F,Bangalore,75,200,7.5,Normal,Adult
6,A007,49,F,Chennai,100,400,10.0,Normal,Adult
7,A008,56,F,New Delhi,650,30,65.0,VIP,Adult
8,A009,82,F,Kolkota,432,400,43.2,VIP,Senior
9,A010,97,F,Kolkota,690,800,69.0,VIP,Senior
10,A011,55,F,Kolkota,150,800,15.0,Normal,Adult
11,A012,21,F,Kolkota,100,900,10.0,Normal,Adult
12,A013,18,F,Kolkota,150,200,15.0,Normal,Adult
13,A014,59,F,New Delhi,167,500,16.7,Normal,Adult
14,A015,72,F,New Delhi,92,600,9.2,Normal,Senior
15,A016,47,F,New Delhi,550,500,55.0,VIP,Adult
16,A017,26,F,New Delhi,500,500,50.0,VIP,Adult
17,A018,81,F,New Delhi,765,700,76.5,VIP,Senior
18,A019,22,F,Mumbai,143,500,14.3,Normal,Adult
19,A020,23,M,Mumbai,56,200,5.6,Normal,Adult
20,A021,67,M,Mumbai,165,400,16.5,Normal,Senior
21,A022,45,M,Mumbai,105,300,10.5,Normal,Adult
22,A023,29,M,Hyderabad,180,400,18.0,Normal,Adult
23,A024,71,M,Chennai,455,500,45.5,VIP,Senior
24,A025,17,M,New Delhi,555,300,55.5,VIP,Teen
25,A026,41,M,Hyderabad,197,500,19.7,Normal,Adult
26,A027,69,M,Chennai,435,300,43.5,VIP,Senior

### GST

In [103]:
df["GST"] = df["Spending Score"] * 0.18

df

,CusID,Age,Gender,Location,Spending Score,Quantity,Bonus,Category,Age_Group,GST
0,A001,25,M,Bangalore,135,500,13.5,Normal,Adult,24.30
1,A002,32,M,Bangalore,145,400,14.5,Normal,Adult,26.10
2,A003,65,F,Bangalore,300,500,30.0,Normal,Senior,54.00
3,A004,14,F,Bangalore,600,300,60.0,VIP,Teen,108.00
4,A005,39,F,Bangalore,450,500,45.0,VIP,Adult,81.00
5,A006,28,F,Bangalore,75,200,7.5,Normal,Adult,13.50
6,A007,49,F,Chennai,100,400,10.0,Normal,Adult,18.00
7,A008,56,F,New Delhi,650,30,65.0,VIP,Adult,117.00
8,A009,82,F,Kolkota,432,400,43.2,VIP,Senior,77.76
9,A010,97,F,Kolkota,690,800,69.0,VIP,Senior,124.20
10,A011,55,F,Kolkota,150,800,15.0,Normal,Adult,27.00
11,A012,21,F,Kolkota,100,900,10.0,Normal,Adult,18.00
12,A013,18,F,Kolkota,150,200,15.0,Normal,Adult,27.00
13,A014,59,F,New Delhi,167,500,16.7,Normal,Adult,30.06
14,A015,72,F,New Delhi,92,600,9.2,Normal,Senior,16.56
15,A016,47,F,New Delhi,550,500,55.0,VIP,Adult,99.00
16,A017,26,F,New Delhi,500,500,50.0,VIP,Adult,90.00
17,A018,81,F,New Delhi,765,700,76.5,VIP,Senior,137.70
18,A019,22,F,Mumbai,143,500,14.3,Normal,Adult,25.74
19,A020,23,M,Mumbai,56,200,5.6,Normal,Adult,10.08
20,A021,67,M,Mumbai,165,400,16.5,Normal,Senior,29.70
21,A022,45,M,Mumbai,105,300,10.5,Normal,Adult,18.90
22,A023,29,M,Hyderabad,180,400,18.0,Normal,Adult,32.40
23,A024,71,M,Chennai,455,500,45.5,VIP,Senior,81.90
24,A025,17,M,New Delhi,555,300,55.5,VIP,Teen,99.90
25,A026,41,M,Hyderabad,197,500,19.7,Normal,Adult,35.46
26,A027,69,M,Chennai,435,300,43.5,VIP,Senior,78.30

### Total Purchase

In [104]:
df["Total"] = (
    df["Spending Score"] *
    df["Quantity"]
)

df

,CusID,Age,Gender,Location,Spending Score,Quantity,Bonus,Category,Age_Group,GST,Total
0,A001,25,M,Bangalore,135,500,13.5,Normal,Adult,24.30,67500
1,A002,32,M,Bangalore,145,400,14.5,Normal,Adult,26.10,58000
2,A003,65,F,Bangalore,300,500,30.0,Normal,Senior,54.00,150000
3,A004,14,F,Bangalore,600,300,60.0,VIP,Teen,108.00,180000
4,A005,39,F,Bangalore,450,500,45.0,VIP,Adult,81.00,225000
5,A006,28,F,Bangalore,75,200,7.5,Normal,Adult,13.50,15000
6,A007,49,F,Chennai,100,400,10.0,Normal,Adult,18.00,40000
7,A008,56,F,New Delhi,650,30,65.0,VIP,Adult,117.00,19500
8,A009,82,F,Kolkota,432,400,43.2,VIP,Senior,77.76,172800
9,A010,97,F,Kolkota,690,800,69.0,VIP,Senior,124.20,552000
10,A011,55,F,Kolkota,150,800,15.0,Normal,Adult,27.00,120000
11,A012,21,F,Kolkota,100,900,10.0,Normal,Adult,18.00,90000
12,A013,18,F,Kolkota,150,200,15.0,Normal,Adult,27.00,30000
13,A014,59,F,New Delhi,167,500,16.7,Normal,Adult,30.06,83500
14,A015,72,F,New Delhi,92,600,9.2,Normal,Senior,16.56,55200
15,A016,47,F,New Delhi,550,500,55.0,VIP,Adult,99.00,275000
16,A017,26,F,New Delhi,500,500,50.0,VIP,Adult,90.00,250000
17,A018,81,F,New Delhi,765,700,76.5,VIP,Senior,137.70,535500
18,A019,22,F,Mumbai,143,500,14.3,Normal,Adult,25.74,71500
19,A020,23,M,Mumbai,56,200,5.6,Normal,Adult,10.08,11200
20,A021,67,M,Mumbai,165,400,16.5,Normal,Senior,29.70,66000
21,A022,45,M,Mumbai,105,300,10.5,Normal,Adult,18.90,31500
22,A023,29,M,Hyderabad,180,400,18.0,Normal,Adult,32.40,72000
23,A024,71,M,Chennai,455,500,45.5,VIP,Senior,81.90,227500
24,A025,17,M,New Delhi,555,300,55.5,VIP,Teen,99.90,166500
25,A026,41,M,Hyderabad,197,500,19.7,Normal,Adult,35.46,98500
26,A027,69,M,Chennai,435,300,43.5,VIP,Senior,78.30,130500

### Discount %

In [105]:
df["Discount"] = df["Spending Score"].apply(
    lambda x: "20%" if x > 300 else "5%"
)

df

,CusID,Age,Gender,Location,Spending Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount
0,A001,25,M,Bangalore,135,500,13.5,Normal,Adult,24.30,67500,5%
1,A002,32,M,Bangalore,145,400,14.5,Normal,Adult,26.10,58000,5%
2,A003,65,F,Bangalore,300,500,30.0,Normal,Senior,54.00,150000,5%
3,A004,14,F,Bangalore,600,300,60.0,VIP,Teen,108.00,180000,20%
4,A005,39,F,Bangalore,450,500,45.0,VIP,Adult,81.00,225000,20%
5,A006,28,F,Bangalore,75,200,7.5,Normal,Adult,13.50,15000,5%
6,A007,49,F,Chennai,100,400,10.0,Normal,Adult,18.00,40000,5%
7,A008,56,F,New Delhi,650,30,65.0,VIP,Adult,117.00,19500,20%
8,A009,82,F,Kolkota,432,400,43.2,VIP,Senior,77.76,172800,20%
9,A010,97,F,Kolkota,690,800,69.0,VIP,Senior,124.20,552000,20%
10,A011,55,F,Kolkota,150,800,15.0,Normal,Adult,27.00,120000,5%
11,A012,21,F,Kolkota,100,900,10.0,Normal,Adult,18.00,90000,5%
12,A013,18,F,Kolkota,150,200,15.0,Normal,Adult,27.00,30000,5%
13,A014,59,F,New Delhi,167,500,16.7,Normal,Adult,30.06,83500,5%
14,A015,72,F,New Delhi,92,600,9.2,Normal,Senior,16.56,55200,5%
15,A016,47,F,New Delhi,550,500,55.0,VIP,Adult,99.00,275000,20%
16,A017,26,F,New Delhi,500,500,50.0,VIP,Adult,90.00,250000,20%
17,A018,81,F,New Delhi,765,700,76.5,VIP,Senior,137.70,535500,20%
18,A019,22,F,Mumbai,143,500,14.3,Normal,Adult,25.74,71500,5%
19,A020,23,M,Mumbai,56,200,5.6,Normal,Adult,10.08,11200,5%
20,A021,67,M,Mumbai,165,400,16.5,Normal,Senior,29.70,66000,5%
21,A022,45,M,Mumbai,105,300,10.5,Normal,Adult,18.90,31500,5%
22,A023,29,M,Hyderabad,180,400,18.0,Normal,Adult,32.40,72000,5%
23,A024,71,M,Chennai,455,500,45.5,VIP,Senior,81.90,227500,20%
24,A025,17,M,New Delhi,555,300,55.5,VIP,Teen,99.90,166500,20%
25,A026,41,M,Hyderabad,197,500,19.7,Normal,Adult,35.46,98500,5%
26,A027,69,M,Chennai,435,300,43.5,VIP,Senior,78.30,130500,20%

### 8.Sorting

In [106]:
df.sort_values( "Spending Score") # Ascending

,CusID,Age,Gender,Location,Spending Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount
19,A020,23,M,Mumbai,56,200,5.6,Normal,Adult,10.08,11200,5%
5,A006,28,F,Bangalore,75,200,7.5,Normal,Adult,13.50,15000,5%
14,A015,72,F,New Delhi,92,600,9.2,Normal,Senior,16.56,55200,5%
11,A012,21,F,Kolkota,100,900,10.0,Normal,Adult,18.00,90000,5%
6,A007,49,F,Chennai,100,400,10.0,Normal,Adult,18.00,40000,5%
21,A022,45,M,Mumbai,105,300,10.5,Normal,Adult,18.90,31500,5%
0,A001,25,M,Bangalore,135,500,13.5,Normal,Adult,24.30,67500,5%
18,A019,22,F,Mumbai,143,500,14.3,Normal,Adult,25.74,71500,5%
1,A002,32,M,Bangalore,145,400,14.5,Normal,Adult,26.10,58000,5%
10,A011,55,F,Kolkota,150,800,15.0,Normal,Adult,27.00,120000,5%
12,A013,18,F,Kolkota,150,200,15.0,Normal,Adult,27.00,30000,5%
20,A021,67,M,Mumbai,165,400,16.5,Normal,Senior,29.70,66000,5%
13,A014,59,F,New Delhi,167,500,16.7,Normal,Adult,30.06,83500,5%
22,A023,29,M,Hyderabad,180,400,18.0,Normal,Adult,32.40,72000,5%
25,A026,41,M,Hyderabad,197,500,19.7,Normal,Adult,35.46,98500,5%
2,A003,65,F,Bangalore,300,500,30.0,Normal,Senior,54.00,150000,5%
8,A009,82,F,Kolkota,432,400,43.2,VIP,Senior,77.76,172800,20%
26,A027,69,M,Chennai,435,300,43.5,VIP,Senior,78.30,130500,20%
4,A005,39,F,Bangalore,450,500,45.0,VIP,Adult,81.00,225000,20%
23,A024,71,M,Chennai,455,500,45.5,VIP,Senior,81.90,227500,20%
16,A017,26,F,New Delhi,500,500,50.0,VIP,Adult,90.00,250000,20%
15,A016,47,F,New Delhi,550,500,55.0,VIP,Adult,99.00,275000,20%
24,A025,17,M,New Delhi,555,300,55.5,VIP,Teen,99.90,166500,20%
3,A004,14,F,Bangalore,600,300,60.0,VIP,Teen,108.00,180000,20%
7,A008,56,F,New Delhi,650,30,65.0,VIP,Adult,117.00,19500,20%
9,A010,97,F,Kolkota,690,800,69.0,VIP,Senior,124.20,552000,20%
17,A018,81,F,New Delhi,765,700,76.5,VIP,Senior,137.70,535500,20%

In [107]:
df.sort_values( "Spending Score",ascending=False) # Descending

,CusID,Age,Gender,Location,Spending Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount
17,A018,81,F,New Delhi,765,700,76.5,VIP,Senior,137.70,535500,20%
9,A010,97,F,Kolkota,690,800,69.0,VIP,Senior,124.20,552000,20%
7,A008,56,F,New Delhi,650,30,65.0,VIP,Adult,117.00,19500,20%
3,A004,14,F,Bangalore,600,300,60.0,VIP,Teen,108.00,180000,20%
24,A025,17,M,New Delhi,555,300,55.5,VIP,Teen,99.90,166500,20%
15,A016,47,F,New Delhi,550,500,55.0,VIP,Adult,99.00,275000,20%
16,A017,26,F,New Delhi,500,500,50.0,VIP,Adult,90.00,250000,20%
23,A024,71,M,Chennai,455,500,45.5,VIP,Senior,81.90,227500,20%
4,A005,39,F,Bangalore,450,500,45.0,VIP,Adult,81.00,225000,20%
26,A027,69,M,Chennai,435,300,43.5,VIP,Senior,78.30,130500,20%
8,A009,82,F,Kolkota,432,400,43.2,VIP,Senior,77.76,172800,20%
2,A003,65,F,Bangalore,300,500,30.0,Normal,Senior,54.00,150000,5%
25,A026,41,M,Hyderabad,197,500,19.7,Normal,Adult,35.46,98500,5%
22,A023,29,M,Hyderabad,180,400,18.0,Normal,Adult,32.40,72000,5%
13,A014,59,F,New Delhi,167,500,16.7,Normal,Adult,30.06,83500,5%
20,A021,67,M,Mumbai,165,400,16.5,Normal,Senior,29.70,66000,5%
10,A011,55,F,Kolkota,150,800,15.0,Normal,Adult,27.00,120000,5%
12,A013,18,F,Kolkota,150,200,15.0,Normal,Adult,27.00,30000,5%
1,A002,32,M,Bangalore,145,400,14.5,Normal,Adult,26.10,58000,5%
18,A019,22,F,Mumbai,143,500,14.3,Normal,Adult,25.74,71500,5%
0,A001,25,M,Bangalore,135,500,13.5,Normal,Adult,24.30,67500,5%
21,A022,45,M,Mumbai,105,300,10.5,Normal,Adult,18.90,31500,5%
6,A007,49,F,Chennai,100,400,10.0,Normal,Adult,18.00,40000,5%
11,A012,21,F,Kolkota,100,900,10.0,Normal,Adult,18.00,90000,5%
14,A015,72,F,New Delhi,92,600,9.2,Normal,Senior,16.56,55200,5%
5,A006,28,F,Bangalore,75,200,7.5,Normal,Adult,13.50,15000,5%
19,A020,23,M,Mumbai,56,200,5.6,Normal,Adult,10.08,11200,5%

### 9.Average Of Age

In [92]:
print(df["Age"].mean())

46.2962962962963

### 10.Maximum Spending Score

In [93]:
print(df["Spending Score"].max())

765

### 11.Minimum Spending Score

In [94]:
print(df["Spending Score"].min())

56

### 12.Grouping

In [30]:
# Group By Gender
print(
    df.groupby("Gender")[
        "Spending Score"
    ].mean()
)

Gender
F    347.882353
M    242.800000
Name: Spending Score, dtype: float64

In [31]:
# Group By Location
print(
    df.groupby("Location")[
        "Quantity"
    ].sum()
)

Location
Bangalore    2400
Chennai      1200
Hyderabad     900
Kolkota      3100
Mumbai       1400
New Delhi    3130
Name: Quantity, dtype: int64

### 13.Value Counts

In [32]:
print(df["Location"].value_counts())

Location
New Delhi    7
Bangalore    6
Kolkota      5
Mumbai       4
Chennai      3
Hyderabad    2
Name: count, dtype: int64

### 14.Unique Locations

In [36]:
print(df["Location"].unique())

['Bangalore' 'Chennai' 'New Delhi' 'Kolkota' 'Mumbai' 'Hyderabad']

### 15.Rename Column

In [108]:
df.rename(
    columns={
        "Spending Score": "Score"
    },
    inplace=True
)

df

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount
0,A001,25,M,Bangalore,135,500,13.5,Normal,Adult,24.30,67500,5%
1,A002,32,M,Bangalore,145,400,14.5,Normal,Adult,26.10,58000,5%
2,A003,65,F,Bangalore,300,500,30.0,Normal,Senior,54.00,150000,5%
3,A004,14,F,Bangalore,600,300,60.0,VIP,Teen,108.00,180000,20%
4,A005,39,F,Bangalore,450,500,45.0,VIP,Adult,81.00,225000,20%
5,A006,28,F,Bangalore,75,200,7.5,Normal,Adult,13.50,15000,5%
6,A007,49,F,Chennai,100,400,10.0,Normal,Adult,18.00,40000,5%
7,A008,56,F,New Delhi,650,30,65.0,VIP,Adult,117.00,19500,20%
8,A009,82,F,Kolkota,432,400,43.2,VIP,Senior,77.76,172800,20%
9,A010,97,F,Kolkota,690,800,69.0,VIP,Senior,124.20,552000,20%
10,A011,55,F,Kolkota,150,800,15.0,Normal,Adult,27.00,120000,5%
11,A012,21,F,Kolkota,100,900,10.0,Normal,Adult,18.00,90000,5%
12,A013,18,F,Kolkota,150,200,15.0,Normal,Adult,27.00,30000,5%
13,A014,59,F,New Delhi,167,500,16.7,Normal,Adult,30.06,83500,5%
14,A015,72,F,New Delhi,92,600,9.2,Normal,Senior,16.56,55200,5%
15,A016,47,F,New Delhi,550,500,55.0,VIP,Adult,99.00,275000,20%
16,A017,26,F,New Delhi,500,500,50.0,VIP,Adult,90.00,250000,20%
17,A018,81,F,New Delhi,765,700,76.5,VIP,Senior,137.70,535500,20%
18,A019,22,F,Mumbai,143,500,14.3,Normal,Adult,25.74,71500,5%
19,A020,23,M,Mumbai,56,200,5.6,Normal,Adult,10.08,11200,5%
20,A021,67,M,Mumbai,165,400,16.5,Normal,Senior,29.70,66000,5%
21,A022,45,M,Mumbai,105,300,10.5,Normal,Adult,18.90,31500,5%
22,A023,29,M,Hyderabad,180,400,18.0,Normal,Adult,32.40,72000,5%
23,A024,71,M,Chennai,455,500,45.5,VIP,Senior,81.90,227500,20%
24,A025,17,M,New Delhi,555,300,55.5,VIP,Teen,99.90,166500,20%
25,A026,41,M,Hyderabad,197,500,19.7,Normal,Adult,35.46,98500,5%
26,A027,69,M,Chennai,435,300,43.5,VIP,Senior,78.30,130500,20%

### 16.query() Function

In [50]:
print(
    df.query(
        "Age > 25 and Quantity > 400"
    )
)

   CusID  Age Gender   Location  Score  Quantity     GST   Total
2   A003   65      F  Bangalore    300       500   54.00  150000
4   A005   39      F  Bangalore    450       500   81.00  225000
9   A010   97      F    Kolkota    690       800  124.20  552000
10  A011   55      F    Kolkota    150       800   27.00  120000
13  A014   59      F  New Delhi    167       500   30.06   83500
14  A015   72      F  New Delhi     92       600   16.56   55200
15  A016   47      F  New Delhi    550       500   99.00  275000
16  A017   26      F  New Delhi    500       500   90.00  250000
17  A018   81      F  New Delhi    765       700  137.70  535500
23  A024   71      M    Chennai    455       500   81.90  227500
25  A026   41      M  Hyderabad    197       500   35.46   98500

### 17.Top 3 Spending Customers

In [52]:
print(
    df.nlargest(
        3,
        "Score"
    )
)

   CusID  Age Gender   Location  Score  Quantity    GST   Total
17  A018   81      F  New Delhi    765       700  137.7  535500
9   A010   97      F    Kolkota    690       800  124.2  552000
7   A008   56      F  New Delhi    650        30  117.0   19500

### 18.Lowest 3 Spending Customers

In [55]:
print(
    df.nsmallest(
        3,
        "Score"
    )
)

   CusID  Age Gender   Location  Score  Quantity    GST  Total
19  A020   23      M     Mumbai     56       200  10.08  11200
5   A006   28      F  Bangalore     75       200  13.50  15000
14  A015   72      F  New Delhi     92       600  16.56  55200

### 19.Map Gender

In [109]:
df["Gender"] = df["Gender"].map({
    "M": "Male",
    "F": "Female"
})
df

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount
0,A001,25,Male,Bangalore,135,500,13.5,Normal,Adult,24.30,67500,5%
1,A002,32,Male,Bangalore,145,400,14.5,Normal,Adult,26.10,58000,5%
2,A003,65,Female,Bangalore,300,500,30.0,Normal,Senior,54.00,150000,5%
3,A004,14,Female,Bangalore,600,300,60.0,VIP,Teen,108.00,180000,20%
4,A005,39,Female,Bangalore,450,500,45.0,VIP,Adult,81.00,225000,20%
5,A006,28,Female,Bangalore,75,200,7.5,Normal,Adult,13.50,15000,5%
6,A007,49,Female,Chennai,100,400,10.0,Normal,Adult,18.00,40000,5%
7,A008,56,Female,New Delhi,650,30,65.0,VIP,Adult,117.00,19500,20%
8,A009,82,Female,Kolkota,432,400,43.2,VIP,Senior,77.76,172800,20%
9,A010,97,Female,Kolkota,690,800,69.0,VIP,Senior,124.20,552000,20%
10,A011,55,Female,Kolkota,150,800,15.0,Normal,Adult,27.00,120000,5%
11,A012,21,Female,Kolkota,100,900,10.0,Normal,Adult,18.00,90000,5%
12,A013,18,Female,Kolkota,150,200,15.0,Normal,Adult,27.00,30000,5%
13,A014,59,Female,New Delhi,167,500,16.7,Normal,Adult,30.06,83500,5%
14,A015,72,Female,New Delhi,92,600,9.2,Normal,Senior,16.56,55200,5%
15,A016,47,Female,New Delhi,550,500,55.0,VIP,Adult,99.00,275000,20%
16,A017,26,Female,New Delhi,500,500,50.0,VIP,Adult,90.00,250000,20%
17,A018,81,Female,New Delhi,765,700,76.5,VIP,Senior,137.70,535500,20%
18,A019,22,Female,Mumbai,143,500,14.3,Normal,Adult,25.74,71500,5%
19,A020,23,Male,Mumbai,56,200,5.6,Normal,Adult,10.08,11200,5%
20,A021,67,Male,Mumbai,165,400,16.5,Normal,Senior,29.70,66000,5%
21,A022,45,Male,Mumbai,105,300,10.5,Normal,Adult,18.90,31500,5%
22,A023,29,Male,Hyderabad,180,400,18.0,Normal,Adult,32.40,72000,5%
23,A024,71,Male,Chennai,455,500,45.5,VIP,Senior,81.90,227500,20%
24,A025,17,Male,New Delhi,555,300,55.5,VIP,Teen,99.90,166500,20%
25,A026,41,Male,Hyderabad,197,500,19.7,Normal,Adult,35.46,98500,5%
26,A027,69,Male,Chennai,435,300,43.5,VIP,Senior,78.30,130500,20%

### 20.Customer Type

In [110]:
def customer_type(x):
    if x > 500:
        return "Premium"
    else:
        return "Regular"

df["Customer_Type"] = df["Quantity"].apply(customer_type)

df

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type
0,A001,25,Male,Bangalore,135,500,13.5,Normal,Adult,24.30,67500,5%,Regular
1,A002,32,Male,Bangalore,145,400,14.5,Normal,Adult,26.10,58000,5%,Regular
2,A003,65,Female,Bangalore,300,500,30.0,Normal,Senior,54.00,150000,5%,Regular
3,A004,14,Female,Bangalore,600,300,60.0,VIP,Teen,108.00,180000,20%,Regular
4,A005,39,Female,Bangalore,450,500,45.0,VIP,Adult,81.00,225000,20%,Regular
5,A006,28,Female,Bangalore,75,200,7.5,Normal,Adult,13.50,15000,5%,Regular
6,A007,49,Female,Chennai,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular
7,A008,56,Female,New Delhi,650,30,65.0,VIP,Adult,117.00,19500,20%,Regular
8,A009,82,Female,Kolkota,432,400,43.2,VIP,Senior,77.76,172800,20%,Regular
9,A010,97,Female,Kolkota,690,800,69.0,VIP,Senior,124.20,552000,20%,Premium
10,A011,55,Female,Kolkota,150,800,15.0,Normal,Adult,27.00,120000,5%,Premium
11,A012,21,Female,Kolkota,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium
12,A013,18,Female,Kolkota,150,200,15.0,Normal,Adult,27.00,30000,5%,Regular
13,A014,59,Female,New Delhi,167,500,16.7,Normal,Adult,30.06,83500,5%,Regular
14,A015,72,Female,New Delhi,92,600,9.2,Normal,Senior,16.56,55200,5%,Premium
15,A016,47,Female,New Delhi,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular
16,A017,26,Female,New Delhi,500,500,50.0,VIP,Adult,90.00,250000,20%,Regular
17,A018,81,Female,New Delhi,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium
18,A019,22,Female,Mumbai,143,500,14.3,Normal,Adult,25.74,71500,5%,Regular
19,A020,23,Male,Mumbai,56,200,5.6,Normal,Adult,10.08,11200,5%,Regular
20,A021,67,Male,Mumbai,165,400,16.5,Normal,Senior,29.70,66000,5%,Regular
21,A022,45,Male,Mumbai,105,300,10.5,Normal,Adult,18.90,31500,5%,Regular
22,A023,29,Male,Hyderabad,180,400,18.0,Normal,Adult,32.40,72000,5%,Regular
23,A024,71,Male,Chennai,455,500,45.5,VIP,Senior,81.90,227500,20%,Regular
24,A025,17,Male,New Delhi,555,300,55.5,VIP,Teen,99.90,166500,20%,Regular
25,A026,41,Male,Hyderabad,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular
26,A027,69,Male,Chennai,435,300,43.5,VIP,Senior,78.30,130500,20%,Regular

### 21.Convert Uppercase

In [111]:
df["Location"] = df["Location"].str.upper()

df

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type
0,A001,25,Male,BANGALORE,135,500,13.5,Normal,Adult,24.30,67500,5%,Regular
1,A002,32,Male,BANGALORE,145,400,14.5,Normal,Adult,26.10,58000,5%,Regular
2,A003,65,Female,BANGALORE,300,500,30.0,Normal,Senior,54.00,150000,5%,Regular
3,A004,14,Female,BANGALORE,600,300,60.0,VIP,Teen,108.00,180000,20%,Regular
4,A005,39,Female,BANGALORE,450,500,45.0,VIP,Adult,81.00,225000,20%,Regular
5,A006,28,Female,BANGALORE,75,200,7.5,Normal,Adult,13.50,15000,5%,Regular
6,A007,49,Female,CHENNAI,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular
7,A008,56,Female,NEW DELHI,650,30,65.0,VIP,Adult,117.00,19500,20%,Regular
8,A009,82,Female,KOLKOTA,432,400,43.2,VIP,Senior,77.76,172800,20%,Regular
9,A010,97,Female,KOLKOTA,690,800,69.0,VIP,Senior,124.20,552000,20%,Premium
10,A011,55,Female,KOLKOTA,150,800,15.0,Normal,Adult,27.00,120000,5%,Premium
11,A012,21,Female,KOLKOTA,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium
12,A013,18,Female,KOLKOTA,150,200,15.0,Normal,Adult,27.00,30000,5%,Regular
13,A014,59,Female,NEW DELHI,167,500,16.7,Normal,Adult,30.06,83500,5%,Regular
14,A015,72,Female,NEW DELHI,92,600,9.2,Normal,Senior,16.56,55200,5%,Premium
15,A016,47,Female,NEW DELHI,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular
16,A017,26,Female,NEW DELHI,500,500,50.0,VIP,Adult,90.00,250000,20%,Regular
17,A018,81,Female,NEW DELHI,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium
18,A019,22,Female,MUMBAI,143,500,14.3,Normal,Adult,25.74,71500,5%,Regular
19,A020,23,Male,MUMBAI,56,200,5.6,Normal,Adult,10.08,11200,5%,Regular
20,A021,67,Male,MUMBAI,165,400,16.5,Normal,Senior,29.70,66000,5%,Regular
21,A022,45,Male,MUMBAI,105,300,10.5,Normal,Adult,18.90,31500,5%,Regular
22,A023,29,Male,HYDERABAD,180,400,18.0,Normal,Adult,32.40,72000,5%,Regular
23,A024,71,Male,CHENNAI,455,500,45.5,VIP,Senior,81.90,227500,20%,Regular
24,A025,17,Male,NEW DELHI,555,300,55.5,VIP,Teen,99.90,166500,20%,Regular
25,A026,41,Male,HYDERABAD,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular
26,A027,69,Male,CHENNAI,435,300,43.5,VIP,Senior,78.30,130500,20%,Regular

### 22.String Contains

In [113]:
df[
    df["Location"].str.contains("BAN")
  ]

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type
0,A001,25,Male,BANGALORE,135,500,13.5,Normal,Adult,24.3,67500,5%,Regular
1,A002,32,Male,BANGALORE,145,400,14.5,Normal,Adult,26.1,58000,5%,Regular
2,A003,65,Female,BANGALORE,300,500,30.0,Normal,Senior,54.0,150000,5%,Regular
3,A004,14,Female,BANGALORE,600,300,60.0,VIP,Teen,108.0,180000,20%,Regular
4,A005,39,Female,BANGALORE,450,500,45.0,VIP,Adult,81.0,225000,20%,Regular
5,A006,28,Female,BANGALORE,75,200,7.5,Normal,Adult,13.5,15000,5%,Regular

### 23.Sample Rows

In [117]:
df.sample(5) # Randomly Select

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type
6,A007,49,Female,CHENNAI,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular
15,A016,47,Female,NEW DELHI,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular
17,A018,81,Female,NEW DELHI,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium
11,A012,21,Female,KOLKOTA,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium
25,A026,41,Male,HYDERABAD,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular

### 24.Reset Index

In [119]:
df.reset_index()

,index,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type
0,0,A001,25,Male,BANGALORE,135,500,13.5,Normal,Adult,24.30,67500,5%,Regular
1,1,A002,32,Male,BANGALORE,145,400,14.5,Normal,Adult,26.10,58000,5%,Regular
2,2,A003,65,Female,BANGALORE,300,500,30.0,Normal,Senior,54.00,150000,5%,Regular
3,3,A004,14,Female,BANGALORE,600,300,60.0,VIP,Teen,108.00,180000,20%,Regular
4,4,A005,39,Female,BANGALORE,450,500,45.0,VIP,Adult,81.00,225000,20%,Regular
5,5,A006,28,Female,BANGALORE,75,200,7.5,Normal,Adult,13.50,15000,5%,Regular
6,6,A007,49,Female,CHENNAI,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular
7,7,A008,56,Female,NEW DELHI,650,30,65.0,VIP,Adult,117.00,19500,20%,Regular
8,8,A009,82,Female,KOLKOTA,432,400,43.2,VIP,Senior,77.76,172800,20%,Regular
9,9,A010,97,Female,KOLKOTA,690,800,69.0,VIP,Senior,124.20,552000,20%,Premium
10,10,A011,55,Female,KOLKOTA,150,800,15.0,Normal,Adult,27.00,120000,5%,Premium
11,11,A012,21,Female,KOLKOTA,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium
12,12,A013,18,Female,KOLKOTA,150,200,15.0,Normal,Adult,27.00,30000,5%,Regular
13,13,A014,59,Female,NEW DELHI,167,500,16.7,Normal,Adult,30.06,83500,5%,Regular
14,14,A015,72,Female,NEW DELHI,92,600,9.2,Normal,Senior,16.56,55200,5%,Premium
15,15,A016,47,Female,NEW DELHI,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular
16,16,A017,26,Female,NEW DELHI,500,500,50.0,VIP,Adult,90.00,250000,20%,Regular
17,17,A018,81,Female,NEW DELHI,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium
18,18,A019,22,Female,MUMBAI,143,500,14.3,Normal,Adult,25.74,71500,5%,Regular
19,19,A020,23,Male,MUMBAI,56,200,5.6,Normal,Adult,10.08,11200,5%,Regular
20,20,A021,67,Male,MUMBAI,165,400,16.5,Normal,Senior,29.70,66000,5%,Regular
21,21,A022,45,Male,MUMBAI,105,300,10.5,Normal,Adult,18.90,31500,5%,Regular
22,22,A023,29,Male,HYDERABAD,180,400,18.0,Normal,Adult,32.40,72000,5%,Regular
23,23,A024,71,Male,CHENNAI,455,500,45.5,VIP,Senior,81.90,227500,20%,Regular
24,24,A025,17,Male,NEW DELHI,555,300,55.5,VIP,Teen,99.90,166500,20%,Regular
25,25,A026,41,Male,HYDERABAD,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular
26,26,A027,69,Male,CHENNAI,435,300,43.5,VIP,Senior,78.30,130500,20%,Regular

### 25.Set Index As CusID

In [121]:
df.set_index("CusID")

,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type
CusID,,,,,,,,,,,,
A001,25,Male,BANGALORE,135,500,13.5,Normal,Adult,24.30,67500,5%,Regular
A002,32,Male,BANGALORE,145,400,14.5,Normal,Adult,26.10,58000,5%,Regular
A003,65,Female,BANGALORE,300,500,30.0,Normal,Senior,54.00,150000,5%,Regular
A004,14,Female,BANGALORE,600,300,60.0,VIP,Teen,108.00,180000,20%,Regular
A005,39,Female,BANGALORE,450,500,45.0,VIP,Adult,81.00,225000,20%,Regular
A006,28,Female,BANGALORE,75,200,7.5,Normal,Adult,13.50,15000,5%,Regular
A007,49,Female,CHENNAI,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular
A008,56,Female,NEW DELHI,650,30,65.0,VIP,Adult,117.00,19500,20%,Regular
A009,82,Female,KOLKOTA,432,400,43.2,VIP,Senior,77.76,172800,20%,Regular
A010,97,Female,KOLKOTA,690,800,69.0,VIP,Senior,124.20,552000,20%,Premium
A011,55,Female,KOLKOTA,150,800,15.0,Normal,Adult,27.00,120000,5%,Premium
A012,21,Female,KOLKOTA,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium
A013,18,Female,KOLKOTA,150,200,15.0,Normal,Adult,27.00,30000,5%,Regular
A014,59,Female,NEW DELHI,167,500,16.7,Normal,Adult,30.06,83500,5%,Regular
A015,72,Female,NEW DELHI,92,600,9.2,Normal,Senior,16.56,55200,5%,Premium
A016,47,Female,NEW DELHI,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular
A017,26,Female,NEW DELHI,500,500,50.0,VIP,Adult,90.00,250000,20%,Regular
A018,81,Female,NEW DELHI,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium
A019,22,Female,MUMBAI,143,500,14.3,Normal,Adult,25.74,71500,5%,Regular
A020,23,Male,MUMBAI,56,200,5.6,Normal,Adult,10.08,11200,5%,Regular
A021,67,Male,MUMBAI,165,400,16.5,Normal,Senior,29.70,66000,5%,Regular
A022,45,Male,MUMBAI,105,300,10.5,Normal,Adult,18.90,31500,5%,Regular
A023,29,Male,HYDERABAD,180,400,18.0,Normal,Adult,32.40,72000,5%,Regular
A024,71,Male,CHENNAI,455,500,45.5,VIP,Senior,81.90,227500,20%,Regular
A025,17,Male,NEW DELHI,555,300,55.5,VIP,Teen,99.90,166500,20%,Regular
A026,41,Male,HYDERABAD,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular
A027,69,Male,CHENNAI,435,300,43.5,VIP,Senior,78.30,130500,20%,Regular

### 26.Count Duplicates Rows

In [123]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
dtype: bool

### 27.Age Bins

In [124]:
df["Age_Category"] = pd.cut(
    df["Age"],
    bins=[0,18,60,100],
    labels=["Teen","Adult","Senior"]
)

df

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type,Age_Category
0,A001,25,Male,BANGALORE,135,500,13.5,Normal,Adult,24.30,67500,5%,Regular,Adult
1,A002,32,Male,BANGALORE,145,400,14.5,Normal,Adult,26.10,58000,5%,Regular,Adult
2,A003,65,Female,BANGALORE,300,500,30.0,Normal,Senior,54.00,150000,5%,Regular,Senior
3,A004,14,Female,BANGALORE,600,300,60.0,VIP,Teen,108.00,180000,20%,Regular,Teen
4,A005,39,Female,BANGALORE,450,500,45.0,VIP,Adult,81.00,225000,20%,Regular,Adult
5,A006,28,Female,BANGALORE,75,200,7.5,Normal,Adult,13.50,15000,5%,Regular,Adult
6,A007,49,Female,CHENNAI,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular,Adult
7,A008,56,Female,NEW DELHI,650,30,65.0,VIP,Adult,117.00,19500,20%,Regular,Adult
8,A009,82,Female,KOLKOTA,432,400,43.2,VIP,Senior,77.76,172800,20%,Regular,Senior
9,A010,97,Female,KOLKOTA,690,800,69.0,VIP,Senior,124.20,552000,20%,Premium,Senior
10,A011,55,Female,KOLKOTA,150,800,15.0,Normal,Adult,27.00,120000,5%,Premium,Adult
11,A012,21,Female,KOLKOTA,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium,Adult
12,A013,18,Female,KOLKOTA,150,200,15.0,Normal,Adult,27.00,30000,5%,Regular,Teen
13,A014,59,Female,NEW DELHI,167,500,16.7,Normal,Adult,30.06,83500,5%,Regular,Adult
14,A015,72,Female,NEW DELHI,92,600,9.2,Normal,Senior,16.56,55200,5%,Premium,Senior
15,A016,47,Female,NEW DELHI,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular,Adult
16,A017,26,Female,NEW DELHI,500,500,50.0,VIP,Adult,90.00,250000,20%,Regular,Adult
17,A018,81,Female,NEW DELHI,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium,Senior
18,A019,22,Female,MUMBAI,143,500,14.3,Normal,Adult,25.74,71500,5%,Regular,Adult
19,A020,23,Male,MUMBAI,56,200,5.6,Normal,Adult,10.08,11200,5%,Regular,Adult
20,A021,67,Male,MUMBAI,165,400,16.5,Normal,Senior,29.70,66000,5%,Regular,Senior
21,A022,45,Male,MUMBAI,105,300,10.5,Normal,Adult,18.90,31500,5%,Regular,Adult
22,A023,29,Male,HYDERABAD,180,400,18.0,Normal,Adult,32.40,72000,5%,Regular,Adult
23,A024,71,Male,CHENNAI,455,500,45.5,VIP,Senior,81.90,227500,20%,Regular,Senior
24,A025,17,Male,NEW DELHI,555,300,55.5,VIP,Teen,99.90,166500,20%,Regular,Teen
25,A026,41,Male,HYDERABAD,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular,Adult
26,A027,69,Male,CHENNAI,435,300,43.5,VIP,Senior,78.30,130500,20%,Regular,Senior

### 28.Transform Score

In [125]:
df["Double_Score"] = df[
    "Score"
].transform(
    lambda x: x * 2
)

df

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type,Age_Category,Double_Score
0,A001,25,Male,BANGALORE,135,500,13.5,Normal,Adult,24.30,67500,5%,Regular,Adult,270
1,A002,32,Male,BANGALORE,145,400,14.5,Normal,Adult,26.10,58000,5%,Regular,Adult,290
2,A003,65,Female,BANGALORE,300,500,30.0,Normal,Senior,54.00,150000,5%,Regular,Senior,600
3,A004,14,Female,BANGALORE,600,300,60.0,VIP,Teen,108.00,180000,20%,Regular,Teen,1200
4,A005,39,Female,BANGALORE,450,500,45.0,VIP,Adult,81.00,225000,20%,Regular,Adult,900
5,A006,28,Female,BANGALORE,75,200,7.5,Normal,Adult,13.50,15000,5%,Regular,Adult,150
6,A007,49,Female,CHENNAI,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular,Adult,200
7,A008,56,Female,NEW DELHI,650,30,65.0,VIP,Adult,117.00,19500,20%,Regular,Adult,1300
8,A009,82,Female,KOLKOTA,432,400,43.2,VIP,Senior,77.76,172800,20%,Regular,Senior,864
9,A010,97,Female,KOLKOTA,690,800,69.0,VIP,Senior,124.20,552000,20%,Premium,Senior,1380
10,A011,55,Female,KOLKOTA,150,800,15.0,Normal,Adult,27.00,120000,5%,Premium,Adult,300
11,A012,21,Female,KOLKOTA,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium,Adult,200
12,A013,18,Female,KOLKOTA,150,200,15.0,Normal,Adult,27.00,30000,5%,Regular,Teen,300
13,A014,59,Female,NEW DELHI,167,500,16.7,Normal,Adult,30.06,83500,5%,Regular,Adult,334
14,A015,72,Female,NEW DELHI,92,600,9.2,Normal,Senior,16.56,55200,5%,Premium,Senior,184
15,A016,47,Female,NEW DELHI,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular,Adult,1100
16,A017,26,Female,NEW DELHI,500,500,50.0,VIP,Adult,90.00,250000,20%,Regular,Adult,1000
17,A018,81,Female,NEW DELHI,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium,Senior,1530
18,A019,22,Female,MUMBAI,143,500,14.3,Normal,Adult,25.74,71500,5%,Regular,Adult,286
19,A020,23,Male,MUMBAI,56,200,5.6,Normal,Adult,10.08,11200,5%,Regular,Adult,112
20,A021,67,Male,MUMBAI,165,400,16.5,Normal,Senior,29.70,66000,5%,Regular,Senior,330
21,A022,45,Male,MUMBAI,105,300,10.5,Normal,Adult,18.90,31500,5%,Regular,Adult,210
22,A023,29,Male,HYDERABAD,180,400,18.0,Normal,Adult,32.40,72000,5%,Regular,Adult,360
23,A024,71,Male,CHENNAI,455,500,45.5,VIP,Senior,81.90,227500,20%,Regular,Senior,910
24,A025,17,Male,NEW DELHI,555,300,55.5,VIP,Teen,99.90,166500,20%,Regular,Teen,1110
25,A026,41,Male,HYDERABAD,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular,Adult,394
26,A027,69,Male,CHENNAI,435,300,43.5,VIP,Senior,78.30,130500,20%,Regular,Senior,870

### Apply Row Wise

In [126]:
df["Final"] = df.apply(
    lambda x:
    x["Score"] +
    x["Quantity"],
    axis=1
)

df

,CusID,Age,Gender,Location,Score,Quantity,Bonus,Category,Age_Group,GST,Total,Discount,Customer_Type,Age_Category,Double_Score,Final
0,A001,25,Male,BANGALORE,135,500,13.5,Normal,Adult,24.30,67500,5%,Regular,Adult,270,635
1,A002,32,Male,BANGALORE,145,400,14.5,Normal,Adult,26.10,58000,5%,Regular,Adult,290,545
2,A003,65,Female,BANGALORE,300,500,30.0,Normal,Senior,54.00,150000,5%,Regular,Senior,600,800
3,A004,14,Female,BANGALORE,600,300,60.0,VIP,Teen,108.00,180000,20%,Regular,Teen,1200,900
4,A005,39,Female,BANGALORE,450,500,45.0,VIP,Adult,81.00,225000,20%,Regular,Adult,900,950
5,A006,28,Female,BANGALORE,75,200,7.5,Normal,Adult,13.50,15000,5%,Regular,Adult,150,275
6,A007,49,Female,CHENNAI,100,400,10.0,Normal,Adult,18.00,40000,5%,Regular,Adult,200,500
7,A008,56,Female,NEW DELHI,650,30,65.0,VIP,Adult,117.00,19500,20%,Regular,Adult,1300,680
8,A009,82,Female,KOLKOTA,432,400,43.2,VIP,Senior,77.76,172800,20%,Regular,Senior,864,832
9,A010,97,Female,KOLKOTA,690,800,69.0,VIP,Senior,124.20,552000,20%,Premium,Senior,1380,1490
10,A011,55,Female,KOLKOTA,150,800,15.0,Normal,Adult,27.00,120000,5%,Premium,Adult,300,950
11,A012,21,Female,KOLKOTA,100,900,10.0,Normal,Adult,18.00,90000,5%,Premium,Adult,200,1000
12,A013,18,Female,KOLKOTA,150,200,15.0,Normal,Adult,27.00,30000,5%,Regular,Teen,300,350
13,A014,59,Female,NEW DELHI,167,500,16.7,Normal,Adult,30.06,83500,5%,Regular,Adult,334,667
14,A015,72,Female,NEW DELHI,92,600,9.2,Normal,Senior,16.56,55200,5%,Premium,Senior,184,692
15,A016,47,Female,NEW DELHI,550,500,55.0,VIP,Adult,99.00,275000,20%,Regular,Adult,1100,1050
16,A017,26,Female,NEW DELHI,500,500,50.0,VIP,Adult,90.00,250000,20%,Regular,Adult,1000,1000
17,A018,81,Female,NEW DELHI,765,700,76.5,VIP,Senior,137.70,535500,20%,Premium,Senior,1530,1465
18,A019,22,Female,MUMBAI,143,500,14.3,Normal,Adult,25.74,71500,5%,Regular,Adult,286,643
19,A020,23,Male,MUMBAI,56,200,5.6,Normal,Adult,10.08,11200,5%,Regular,Adult,112,256
20,A021,67,Male,MUMBAI,165,400,16.5,Normal,Senior,29.70,66000,5%,Regular,Senior,330,565
21,A022,45,Male,MUMBAI,105,300,10.5,Normal,Adult,18.90,31500,5%,Regular,Adult,210,405
22,A023,29,Male,HYDERABAD,180,400,18.0,Normal,Adult,32.40,72000,5%,Regular,Adult,360,580
23,A024,71,Male,CHENNAI,455,500,45.5,VIP,Senior,81.90,227500,20%,Regular,Senior,910,955
24,A025,17,Male,NEW DELHI,555,300,55.5,VIP,Teen,99.90,166500,20%,Regular,Teen,1110,855
25,A026,41,Male,HYDERABAD,197,500,19.7,Normal,Adult,35.46,98500,5%,Regular,Adult,394,697
26,A027,69,Male,CHENNAI,435,300,43.5,VIP,Senior,78.30,130500,20%,Regular,Senior,870,735

### 29.Describe Data

In [127]:
df.describe()

,Age,Score,Quantity,Bonus,GST,Total,Double_Score,Final
count,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
mean,46.296296,308.962963,449.259259,30.896296,55.613333,140525.925926,617.925926,758.222222
std,23.382793,222.021046,198.202032,22.202105,39.963788,138302.393306,444.042091,303.566661
min,14.000000,56.000000,30.000000,5.600000,10.080000,11200.000000,112.000000,256.000000
25%,25.500000,139.000000,300.000000,13.900000,25.020000,56600.000000,278.000000,572.500000
50%,45.000000,180.000000,500.000000,18.000000,32.400000,90000.000000,360.000000,697.000000
75%,66.000000,477.500000,500.000000,47.750000,85.950000,176400.000000,955.000000,950.000000
max,97.000000,765.000000,900.000000,76.500000,137.700000,552000.000000,1530.000000,1490.000000

### 30.Export CSV

In [129]:
df.to_csv(
    "New_customer.csv",
    index=False
)
New=pd.read_csv("New_cu")

## SUMMARY

In [131]:
print("Total Customers :", len(df))
print("Average Age :", df["Age"].mean())
print("Max Spending :", df["Score"].max())
print("Total Quantity :", df["Quantity"].sum())
print("Locations :", df["Location"].unique())

Total Customers : 27
Average Age : 46.2962962962963
Max Spending : 765
Total Quantity : 12130
Locations : ['BANGALORE' 'CHENNAI' 'NEW DELHI' 'KOLKOTA' 'MUMBAI' 'HYDERABAD']